use std::{env, path::PathBuf};

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let out_dir = PathBuf::from(&crate_dir);

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("MICROSANDBOX_GO_FFI_H")
        .with_autogen_warning(
            "/* THIS FILE IS AUTO-GENERATED BY cbindgen — DO NOT EDIT. \
             Run `cargo build -p microsandbox-go` to regenerate. */",
        )
        .with_documentation(true)
        .generate()
        .expect("cbindgen failed to generate microsandbox_go_ffi.h")
        .write_to_file(out_dir.join("microsandbox_go_ffi.h"));

    // Re-run only when the FFI source changes.
    println!("cargo:rerun-if-changed=src/lib.rs");
}
