"""microsandbox — Python SDK for secure, fast microVM-based sandboxing."""

# Wire bundled msb path into the Rust resolver's env var so the Rust SDK
# finds msb from the wheel bundle. libkrunfw is resolved relative to msb
# automatically (../lib/ from the msb binary).
import os as _os

from microsandbox._runtime import msb_path as _msb_path

if "MSB_PATH" not in _os.environ:
    _bundled_msb = _msb_path()
    if _bundled_msb.exists():
        _os.environ["MSB_PATH"] = str(_bundled_msb)

from microsandbox._microsandbox import (
    ExecHandle,
    ExecOutput,
    ExecSink,
    FsEntry,
    FsMetadata,
    FsReadStream,
    FsWriteSink,
    MetricsStream,
    PullSession,
    Sandbox,
    SandboxFs,
    SandboxHandle,
    SandboxMetrics,
    Volume,
    VolumeHandle,
    all_sandbox_metrics,
    install,
    is_installed,
    version,
)
from microsandbox.errors import (
    ExecFailedError,
    ExecTimeoutError,
    FilesystemError,
    ImageNotFoundError,
    ImagePullFailedError,
    InvalidConfigError,
    IoError,
    MicrosandboxError,
    NetworkPolicyError,
    PathNotFoundError,
    SandboxAlreadyExistsError,
    SandboxNotFoundError,
    SandboxNotRunningError,
    SandboxStillRunningError,
    SecretViolationError,
    TlsError,
    VolumeNotFoundError,
)
from microsandbox.events import (
    ExecEvent,
    ExitedEvent,
    LayerDownloadComplete,
    LayerDownloadProgress,
    LayerExtractComplete,
    LayerExtractProgress,
    LayerExtractStarted,
    LayerIndexComplete,
    LayerIndexStarted,
    PullComplete,
    PullProgress,
    Resolved,
    Resolving,
    StartedEvent,
    StderrEvent,
    StdoutEvent,
)
from microsandbox.types import (
    Action,
    AttachOptions,
    DestGroup,
    Direction,
    DiskImageFormat,
    ExecOptions,
    ExitStatus,
    FsEntryKind,
    GiB,
    Image,
    ImageSource,
    LogLevel,
    MiB,
    MountConfig,
    MountKind,
    Network,
    NetworkPolicy,
    Patch,
    PatchConfig,
    PortProtocol,
    Protocol,
    PullPolicy,
    RegistryAuth,
    Rlimit,
    RlimitResource,
    Rule,
    SandboxStatus,
    Secret,
    SecretEntry,
    Size,
    Stdin,
    TlsConfig,
    ViolationAction,
)

__all__ = [
    # Sandbox lifecycle (native)
    "Sandbox",
    "SandboxHandle",
    "PullSession",
    "SandboxStatus",
    # Execution (native)
    "ExecHandle",
    "ExecOutput",
    "ExecSink",
    "MetricsStream",
    "ExecOptions",
    "ExitStatus",
    "Stdin",
    "Rlimit",
    "RlimitResource",
    # Events (sealed unions)
    "ExecEvent",
    "StartedEvent",
    "StdoutEvent",
    "StderrEvent",
    "ExitedEvent",
    # Pull progress events
    "PullProgress",
    "Resolving",
    "Resolved",
    "LayerDownloadProgress",
    "LayerDownloadComplete",
    "LayerExtractStarted",
    "LayerExtractProgress",
    "LayerExtractComplete",
    "LayerIndexStarted",
    "LayerIndexComplete",
    "PullComplete",
    # Filesystem (native)
    "SandboxFs",
    "FsReadStream",
    "FsWriteSink",
    "FsEntry",
    "FsMetadata",
    # Filesystem (Python enums)
    "FsEntryKind",
    # Volumes
    "Volume",
    "VolumeHandle",
    "MountConfig",
    "MountKind",
    # Network
    "Network",
    "NetworkPolicy",
    "Rule",
    "Action",
    "Direction",
    "Protocol",
    "PortProtocol",
    "DestGroup",
    # Secrets & TLS
    "Secret",
    "SecretEntry",
    "TlsConfig",
    "ViolationAction",
    # Images / rootfs
    "Image",
    "ImageSource",
    "DiskImageFormat",
    "PullPolicy",
    "RegistryAuth",
    "LogLevel",
    # Patches
    "Patch",
    "PatchConfig",
    "AttachOptions",
    # Metrics
    "SandboxMetrics",
    "all_sandbox_metrics",
    # Size helpers
    "Size",
    "MiB",
    "GiB",
    # Errors
    "MicrosandboxError",
    "InvalidConfigError",
    "SandboxNotFoundError",
    "SandboxNotRunningError",
    "SandboxAlreadyExistsError",
    "SandboxStillRunningError",
    "ExecTimeoutError",
    "ExecFailedError",
    "FilesystemError",
    "PathNotFoundError",
    "VolumeNotFoundError",
    "ImageNotFoundError",
    "ImagePullFailedError",
    "NetworkPolicyError",
    "SecretViolationError",
    "TlsError",
    "IoError",
    # Setup
    "install",
    "is_installed",
    "version",
]
