[package]
name = "microsandbox-libsql"
description = "libSQL server proxy backend for microsandbox-db."
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "microsandbox_libsql"
path = "lib/lib.rs"

[dependencies]
async-trait = "0.1"
chrono.workspace = true
libsql = { version = "0.9", default-features = false, features = ["remote", "tls"] }
sea-orm = { workspace = true, features = ["proxy"] }
tokio.workspace = true
tracing.workspace = true
