/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Fluent builder for DNS interception settings.
 *
 * Mirrors `microsandbox_network::builder::DnsBuilder` 1:1; setters
 * mutate in place and return `this`. Errors from invalid block-domain
 * strings accumulate and surface from the terminal `.build()` call.
 */
export declare class DnsBuilder {
  constructor()
  /** Block a specific FQDN (returns REFUSED at the resolver). */
  blockDomain(domain: string): this
  /** Block any name ending in `suffix`. */
  blockDomainSuffix(suffix: string): this
  /** Enable or disable DNS rebinding protection. Default: true. */
  rebindProtection(enabled: boolean): this
  /**
   * Set the upstream nameservers. Replaces any previous set.
   * Each entry accepts the same forms as Rust: `"1.1.1.1"`,
   * `"1.1.1.1:53"`, `"dns.google"`, `"dns.google:53"`.
   */
  nameservers(servers: Array<string>): this
  /** Set the per-query timeout in milliseconds. Default: 5000. */
  queryTimeoutMs(ms: number): this
  /**
   * Materialize the accumulated state into a `DnsConfig`. Surfaces
   * the first invalid-domain error accumulated by `blockDomain` /
   * `blockDomainSuffix`, if any.
   */
  build(): DnsConfig
}
export type JsDnsBuilder = DnsBuilder

/**
 * Handle for a streaming command execution.
 *
 * Use `recv()` to get events one at a time, or iterate with a loop:
 * ```js
 * const handle = await sandbox.execStream("tail", ["-f", "/var/log/app.log"]);
 * let event;
 * while ((event = await handle.recv()) !== null) {
 *   if (event.eventType === "stdout") process.stdout.write(event.data);
 * }
 * ```
 */
export declare class ExecHandle {
  /** Get the correlation ID for this execution. */
  get id(): Promise<string>
  /** Receive the next event. Returns `null` when the stream ends. */
  recv(): Promise<ExecEvent | null>
  /** Take the stdin writer. Can only be called once; returns `null` on subsequent calls. */
  takeStdin(): Promise<ExecSink | null>
  /** Wait for the process to exit and return the exit status. */
  wait(): Promise<ExitStatus>
  /** Wait for completion and collect all output. */
  collect(): Promise<ExecOutput>
  /** Send a signal to the running process. */
  signal(signal: number): Promise<void>
  /** Kill the running process (SIGKILL). */
  kill(): Promise<void>
}
export type JsExecHandle = ExecHandle

/**
 * Output of a completed command execution.
 *
 * Provides both string and raw byte access to stdout/stderr:
 * ```js
 * const output = await sandbox.shell("echo hello");
 * console.log(output.stdout());       // "hello
"
 * console.log(output.stdoutBytes());   // <Buffer 68 65 6c 6c 6f 0a>
 * console.log(output.code);            // 0
 * console.log(output.success);         // true
 * ```
 */
export declare class ExecOutput {
  /** Exit code of the process. */
  get code(): number
  /** Whether the process exited successfully (code == 0). */
  get success(): boolean
  /** Get stdout as a UTF-8 string. */
  stdout(): string
  /** Get stderr as a UTF-8 string. */
  stderr(): string
  /** Get stdout as raw bytes. */
  stdoutBytes(): Buffer
  /** Get stderr as raw bytes. */
  stderrBytes(): Buffer
  /** Get the exit status. */
  status(): ExitStatus
}

/** Stdin writer for a running process. */
export declare class ExecSink {
  /** Write data to the process stdin. */
  write(data: Buffer): Promise<void>
  /** Close stdin (sends EOF to the process). */
  close(): Promise<void>
}
export type JsExecSink = ExecSink

/**
 * A streaming reader for file data from the sandbox.
 *
 * Supports both manual `recv()` calls and `for await...of` iteration:
 * ```js
 * const stream = await sb.fs().readStream("/app/data.bin");
 * for await (const chunk of stream) {
 *   processChunk(chunk);
 * }
 * ```
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class FsReadStream {
  /** Receive the next chunk of data. Returns `null` when the stream ends. */
  recv(): Promise<Buffer | null>
  [Symbol.asyncIterator](): AsyncGenerator<Buffer, void, undefined>
}
export type JsFsReadStream = FsReadStream

/** Streaming writer for guest files. */
export declare class FsWriteSink {
  /** Write a chunk to the underlying file. */
  write(data: Buffer): Promise<void>
  /** Flush and close the sink. Idempotent. */
  close(): Promise<void>
}
export type JsFsWriteSink = FsWriteSink

/** A lightweight handle to a cached image. */
export declare class ImageHandle {
  get reference(): string
  get sizeBytes(): number | null
  get manifestDigest(): string | null
  get architecture(): string | null
  get os(): string | null
  get layerCount(): number
  get lastUsedAt(): number | null
  get createdAt(): number | null
}
export type JsImageHandle = ImageHandle

/**
 * A streaming subscription for sandbox metrics at a regular interval.
 *
 * Supports both manual `recv()` calls and `for await...of` iteration:
 * ```js
 * const stream = await sb.metricsStream(1000);
 * for await (const m of stream) {
 *   console.log(`CPU: ${m.cpuPercent.toFixed(1)}%`);
 * }
 * ```
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MetricsStream {
  /** Receive the next metrics snapshot. Returns `null` when the stream ends. */
  recv(): Promise<SandboxMetrics | null>
  [Symbol.asyncIterator](): AsyncGenerator<SandboxMetrics, void, undefined>
}
export type JsMetricsStream = MetricsStream

/**
 * Factory for creating volume mount configurations.
 *
 * ```js
 * import { Mount, Sandbox } from 'microsandbox'
 *
 * const sb = await Sandbox.create({
 *     name: "worker",
 *     image: "python",
 *     volumes: {
 *         "/app/src": Mount.bind("./src", { readonly: true }),
 *         "/data": Mount.named("my-data"),
 *         "/tmp": Mount.tmpfs({ sizeMib: 100 }),
 *     },
 * })
 * ```
 */
export declare class Mount {
  /** Create a bind mount (host directory → guest path). */
  static bind(path: string, opts?: MountOptions | undefined | null): MountConfig
  /** Create a named volume mount. */
  static named(name: string, opts?: MountOptions | undefined | null): MountConfig
  /** Create a tmpfs (in-memory) mount. */
  static tmpfs(opts?: TmpfsOptions | undefined | null): MountConfig
  /**
   * Mount a host disk image as a virtio-blk device at a guest path.
   *
   * Format defaults to the file extension (`.qcow2` → Qcow2, `.vmdk` →
   * Vmdk, anything else → Raw). Use `opts.format` to override. `fstype`
   * (e.g. `"ext4"`) is the inner filesystem agentd will mount; when
   * omitted, agentd probes `/proc/filesystems`.
   */
  static disk(path: string, opts?: DiskOptions | undefined | null): MountConfig
}

/**
 * Fluent builder for a sandbox volume mount.
 *
 * Pick exactly one mount kind via `.bind()`, `.named()`, `.tmpfs()`, or
 * `.disk(...)`, then chain modifiers (`.readonly()`, `.size(mib)` for
 * tmpfs, `.format(fmt)` / `.fstype(s)` for disk). Validation is deferred
 * to the terminal `.build()` call.
 */
export declare class MountBuilder {
  constructor(guest: string)
  /** Bind a host directory at the guest path. */
  bind(host: string): this
  /** Mount a named volume created via `Volume.builder(name).create()`. */
  named(name: string): this
  /** Mount an in-memory tmpfs at the guest path. */
  tmpfs(): this
  /** Mount a host disk image file as a virtio-blk device. */
  disk(host: string): this
  /**
   * Override the disk image format (`"qcow2" | "raw" | "vmdk"`). Only
   * valid when paired with `.disk()`.
   */
  format(format: string): this
  /** Inner filesystem type for a `.disk()` mount (e.g. `"ext4"`). */
  fstype(fstype: string): this
  /** Mark the mount read-only. */
  readonly(): this
  /** Tmpfs size cap in MiB (only valid with `.tmpfs()`). */
  size(mib: number): this
}
export type JsMountBuilder = MountBuilder

/**
 * Factory for creating rootfs patch configurations.
 *
 * ```js
 * import { Patch, Sandbox } from 'microsandbox'
 *
 * const sb = await Sandbox.create({
 *     name: "worker",
 *     image: "alpine",
 *     patches: [
 *         Patch.text("/etc/greeting.txt", "Hello!
"),
 *         Patch.mkdir("/app", { mode: 0o755 }),
 *         Patch.append("/etc/hosts", "127.0.0.1 myapp.local
"),
 *         Patch.copyFile("./config.json", "/app/config.json"),
 *         Patch.copyDir("./scripts", "/app/scripts"),
 *         Patch.symlink("/usr/bin/python3", "/usr/bin/python"),
 *         Patch.remove("/etc/motd"),
 *     ],
 * })
 * ```
 */
export declare class Patch {
  /** Write text content to a file in the guest filesystem. */
  static text(path: string, content: string, opts?: PatchOptions | undefined | null): PatchConfig
  /** Create a directory in the guest filesystem (idempotent). */
  static mkdir(path: string, opts?: PatchOptions | undefined | null): PatchConfig
  /** Append content to an existing file in the guest filesystem. */
  static append(path: string, content: string): PatchConfig
  /** Copy a file from the host into the guest filesystem. */
  static copyFile(src: string, dst: string, opts?: PatchOptions | undefined | null): PatchConfig
  /** Copy a directory from the host into the guest filesystem. */
  static copyDir(src: string, dst: string, opts?: PatchReplaceOptions | undefined | null): PatchConfig
  /** Create a symlink in the guest filesystem. */
  static symlink(target: string, link: string, opts?: PatchReplaceOptions | undefined | null): PatchConfig
  /** Remove a file or directory from the guest filesystem (idempotent). */
  static remove(path: string): PatchConfig
}

/** Fluent builder for an ordered list of pre-boot rootfs patches. */
export declare class PatchBuilder {
  constructor()
  /** Write a text file (UTF-8) at `path`. */
  text(path: string, content: string, opts?: PatchFileOptions | undefined | null): this
  /** Write raw bytes at `path`. */
  file(path: string, content: Buffer, opts?: PatchFileOptions | undefined | null): this
  /** Copy a host file into the rootfs at `dst`. */
  copyFile(src: string, dst: string, opts?: PatchFileOptions | undefined | null): this
  /** Copy a host directory into the rootfs at `dst`. */
  copyDir(src: string, dst: string, opts?: PatchReplaceOnly | undefined | null): this
  /** Create a symlink at `link` pointing to `target`. */
  symlink(target: string, link: string, opts?: PatchReplaceOnly | undefined | null): this
  /** Create a directory (idempotent). */
  mkdir(path: string, opts?: PatchModeOnly | undefined | null): this
  /** Remove a file or directory (idempotent). */
  remove(path: string): this
  /** Append text to an existing file. */
  append(path: string, content: string): this
  /** Materialize into the ordered list of patches. */
  build(): Array<BuiltPatch>
}
export type JsPatchBuilder = PatchBuilder

/** Fluent builder for OCI registry connection settings. */
export declare class RegistryConfigBuilder {
  constructor()
  /** Set authentication credentials. */
  auth(auth: RegistryAuthInput): this
  /** Use plain HTTP (no TLS). */
  insecure(): this
  /** Add a PEM-encoded CA root certificate to trust. May be called repeatedly. */
  caCerts(pemData: Buffer): this
}
export type JsRegistryConfigBuilder = RegistryConfigBuilder

/**
 * A running sandbox instance.
 *
 * Created via `Sandbox.create()` or `Sandbox.start()`. Holds a live connection
 * to the guest VM and can execute commands, access the filesystem, and query metrics.
 */
export declare class Sandbox {
  /** Create a sandbox from configuration (attached mode — stops on GC/process exit). */
  static create(config: SandboxConfig): Promise<Sandbox>
  /** Create a sandbox that survives the parent process (detached mode). */
  static createDetached(config: SandboxConfig): Promise<Sandbox>
  /** Start an existing stopped sandbox (attached mode). */
  static start(name: string): Promise<Sandbox>
  /** Start an existing stopped sandbox (detached mode). */
  static startDetached(name: string): Promise<Sandbox>
  /** Get a lightweight handle to an existing sandbox. */
  static get(name: string): Promise<JsSandboxHandle>
  /** List all sandboxes. */
  static list(): Promise<Array<SandboxInfo>>
  /** Remove a stopped sandbox from the database. */
  static remove(name: string): Promise<void>
  /** Sandbox name. */
  get name(): Promise<string>
  /** Whether this handle owns the sandbox lifecycle (attached mode). */
  get ownsLifecycle(): Promise<boolean>
  /** Execute a command and wait for completion. */
  exec(cmd: string, args?: Array<string> | undefined | null): Promise<ExecOutput>
  /** Execute a command with full configuration and wait for completion. */
  execWithConfig(config: ExecConfig): Promise<ExecOutput>
  /** Execute a command with streaming I/O. */
  execStream(cmd: string, args?: Array<string> | undefined | null): Promise<ExecHandle>
  /**
   * Execute a command with streaming I/O and full configuration.
   *
   * Unlike `execStream`, this accepts an `ExecConfig` so callers can enable
   * a piped stdin (`stdin: "pipe"`), set a TTY, pass env vars, etc. Required
   * for bidirectional streaming protocols where the host writes to the
   * running process's stdin via `ExecHandle.takeStdin()` while concurrently
   * reading events via `ExecHandle.recv()`.
   */
  execStreamWithConfig(config: ExecConfig): Promise<ExecHandle>
  /** Execute a shell command using the sandbox's configured shell. */
  shell(script: string): Promise<ExecOutput>
  /** Execute a shell command with streaming I/O. */
  shellStream(script: string): Promise<ExecHandle>
  /** Get a filesystem handle for operations on the running sandbox. */
  fs(): SandboxFs
  /** Get point-in-time resource metrics. */
  metrics(): Promise<SandboxMetrics>
  /** Stream metrics snapshots at the requested interval (in milliseconds). */
  metricsStream(intervalMs: number): Promise<MetricsStream>
  /**
   * Attach to an interactive PTY session inside the sandbox.
   *
   * Bridges the host terminal to the guest process. Returns the exit code.
   */
  attach(cmd: string, args?: Array<string> | undefined | null): Promise<number>
  /** Attach with full configuration options. */
  attachWithConfig(config: AttachConfig): Promise<number>
  /** Attach to the sandbox's default shell. */
  attachShell(): Promise<number>
  /** Stop the sandbox gracefully (SIGTERM). */
  stop(): Promise<void>
  /** Stop and wait for exit, returning the exit status. */
  stopAndWait(): Promise<ExitStatus>
  /** Kill the sandbox immediately (SIGKILL). */
  kill(): Promise<void>
  /** Graceful drain (SIGUSR1 — for load balancing). */
  drain(): Promise<void>
  /** Wait for the sandbox process to exit. */
  wait(): Promise<ExitStatus>
  /** Detach from the sandbox — it will continue running after this handle is dropped. */
  detach(): Promise<void>
  /** Remove the persisted database record after stopping. */
  removePersisted(): Promise<void>
}

/** Filesystem operations on a running sandbox (via agent protocol). */
export declare class SandboxFs {
  /** Read a file as a Buffer. */
  read(path: string): Promise<Buffer>
  /** Read a file as a UTF-8 string. */
  readString(path: string): Promise<string>
  /** Write data to a file (accepts Buffer or string). */
  write(path: string, data: Buffer): Promise<void>
  /** List directory contents. */
  list(path: string): Promise<Array<FsEntry>>
  /** Create a directory. */
  mkdir(path: string): Promise<void>
  /** Remove a directory. */
  removeDir(path: string): Promise<void>
  /** Remove a file. */
  remove(path: string): Promise<void>
  /** Copy a file within the sandbox. */
  copy(from: string, to: string): Promise<void>
  /** Rename a file within the sandbox. */
  rename(from: string, to: string): Promise<void>
  /** Get file or directory metadata. */
  stat(path: string): Promise<FsMetadata>
  /** Check if a path exists. */
  exists(path: string): Promise<boolean>
  /** Copy a file from the host into the sandbox. */
  copyFromHost(hostPath: string, guestPath: string): Promise<void>
  /** Copy a file from the sandbox to the host. */
  copyToHost(guestPath: string, hostPath: string): Promise<void>
  /** Read a file with streaming (~3 MiB chunks). */
  readStream(path: string): Promise<FsReadStream>
  /** Write a file with streaming. Returns a sink the caller writes to. */
  writeStream(path: string): Promise<FsWriteSink>
}
export type JsSandboxFs = SandboxFs

/**
 * A lightweight handle to a sandbox from the database.
 *
 * Does NOT hold a live connection — use `connect()` or `start()` to get a live `Sandbox`.
 */
export declare class SandboxHandle {
  /** Sandbox name. */
  get name(): string
  /** Status at time of query: "running", "stopped", "crashed", or "draining". */
  get status(): string
  /** Raw config JSON string from the database. */
  get configJson(): string
  /** Creation timestamp as ms since Unix epoch. */
  get createdAt(): number | null
  /** Last update timestamp as ms since Unix epoch. */
  get updatedAt(): number | null
  /** Get point-in-time metrics from the database. */
  metrics(): Promise<SandboxMetrics>
  /** Start the sandbox (attached mode) — returns a live Sandbox handle. */
  start(): Promise<Sandbox>
  /** Start the sandbox (detached mode). */
  startDetached(): Promise<Sandbox>
  /** Connect to an already-running sandbox (no lifecycle ownership). */
  connect(): Promise<Sandbox>
  /** Stop the sandbox (SIGTERM). */
  stop(): Promise<void>
  /** Kill the sandbox (SIGKILL). */
  kill(): Promise<void>
  /** Remove the sandbox from the database. */
  remove(): Promise<void>
}
export type JsSandboxHandle = SandboxHandle

/**
 * Factory for creating secret entries.
 *
 * ```js
 * import { Secret, Sandbox } from 'microsandbox'
 *
 * const sb = await Sandbox.create({
 *     name: "agent",
 *     image: "python",
 *     secrets: [
 *         Secret.env("OPENAI_API_KEY", {
 *             value: process.env.OPENAI_API_KEY,
 *             allowHosts: ["api.openai.com"],
 *         }),
 *     ],
 * })
 * ```
 */
export declare class Secret {
  /** Create a secret bound to an environment variable. */
  static env(envVar: string, opts: SecretEnvOptions): SecretEntry
}

/** Fluent builder for a single secret entry. */
export declare class SecretBuilder {
  constructor()
  /** Environment variable to expose the placeholder under (required). */
  env(var: string): this
  /** Secret value (required). */
  value(value: string): this
  /** Custom placeholder. Auto-generated as `$MSB_<env>` when unset. */
  placeholder(placeholder: string): this
  /** Add an allowed exact-match host. */
  allowHost(host: string): this
  /** Add an allowed wildcard host pattern (e.g. `*.openai.com`). */
  allowHostPattern(pattern: string): this
  /**
   * Allow any host. **Dangerous** — secret can be exfiltrated.
   * Pass `true` to opt in.
   */
  allowAnyHostDangerous(iUnderstand: boolean): this
  /** Require verified TLS identity before substituting (default: true). */
  requireTlsIdentity(enabled: boolean): this
  /** Configure header injection (default: true). */
  injectHeaders(enabled: boolean): this
  /** Configure Basic Auth injection (default: true). */
  injectBasicAuth(enabled: boolean): this
  /** Configure URL query parameter injection (default: false). */
  injectQuery(enabled: boolean): this
  /** Configure request body injection (default: false). */
  injectBody(enabled: boolean): this
  /**
   * Materialize into a `SecretEntry`. Panics if `env` or `value` weren't
   * set (matches the underlying Rust builder's contract; surface as a
   * typed error here).
   */
  build(): SecretEntry
}
export type JsSecretBuilder = SecretBuilder

/** Builder for installing the runtime binaries. */
export declare class Setup {
  constructor()
  baseDir(path: string): this
  version(version: string): this
  skipVerify(enabled: boolean): this
  force(enabled: boolean): this
  install(): Promise<void>
}
export type JsSetup = Setup

/** Fluent builder for TLS interception settings. */
export declare class TlsBuilder {
  constructor()
  /** Add a bypass pattern (no MITM). Supports `*.suffix` wildcards. */
  bypass(pattern: string): this
  /** Verify upstream server certificates (default: true). */
  verifyUpstream(verify: boolean): this
  /** Set the ports to intercept (default: 443). */
  interceptedPorts(ports: Array<number>): this
  /** Block QUIC on intercepted ports (default: true). */
  blockQuic(block: boolean): this
  /** Add an upstream CA certificate PEM path. May be called repeatedly. */
  upstreamCaCert(path: string): this
  /** Set a custom interception CA certificate PEM path. */
  interceptCaCert(path: string): this
  /** Set a custom interception CA private key PEM path. */
  interceptCaKey(path: string): this
  /** Materialize into a `TlsConfig`. */
  build(): TlsConfig
}
export type JsTlsBuilder = TlsBuilder

export declare class Volume {
  static create(config: VolumeConfig): Promise<Volume>
  static get(name: string): Promise<VolumeHandle>
  static list(): Promise<Array<VolumeInfo>>
  static remove(name: string): Promise<void>
  get name(): string
  get path(): string
  /** Host-side filesystem operations on this volume's directory. */
  fs(): VolumeFs
}
export type JsVolume = Volume

export declare class VolumeFs {
  read(path: string): Promise<Buffer>
  readString(path: string): Promise<string>
  readStream(path: string): Promise<VolumeFsReadStream>
  write(path: string, data: Buffer): Promise<void>
  writeStream(path: string): Promise<VolumeFsWriteSink>
  list(path: string): Promise<Array<FsEntry>>
  mkdir(path: string): Promise<void>
  removeDir(path: string): Promise<void>
  remove(path: string): Promise<void>
  copy(from: string, to: string): Promise<void>
  rename(from: string, to: string): Promise<void>
  stat(path: string): Promise<FsMetadata>
  exists(path: string): Promise<boolean>
}
export type JsVolumeFs = VolumeFs

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class VolumeFsReadStream {
  recv(): Promise<Buffer | null>
  [Symbol.asyncIterator](): AsyncGenerator<Buffer, void, undefined>
}
export type JsVolumeFsReadStream = VolumeFsReadStream

export declare class VolumeFsWriteSink {
  write(data: Buffer): Promise<void>
  close(): Promise<void>
}
export type JsVolumeFsWriteSink = VolumeFsWriteSink

export declare class VolumeHandle {
  get name(): string
  get quotaMib(): number | null
  get usedBytes(): number
  get labels(): Record<string, string>
  get createdAt(): number | null
  remove(): Promise<void>
  /** Host-side filesystem operations on this volume's directory. */
  fs(): VolumeFs
}
export type JsVolumeHandle = VolumeHandle

/** Get metrics for all running sandboxes. */
export declare function allSandboxMetrics(): Promise<Record<string, SandboxMetrics>>

/** Configuration for interactive attach sessions. */
export interface AttachConfig {
  /** Command to execute. */
  cmd: string
  /** Command arguments. */
  args?: Array<string>
  /** Working directory inside the sandbox. */
  cwd?: string
  /** User to run as. */
  user?: string
  /** Environment variables. */
  env?: Record<string, string>
  /** Detach key sequence (default: "ctrl-]"). Uses Docker-style syntax. */
  detachKeys?: string
}

/**
 * Built rootfs patch (flat representation of the `Patch` enum: `kind`
 * + per-variant fields).
 */
export interface BuiltPatch {
  /** `"text" | "file" | "copyFile" | "copyDir" | "symlink" | "mkdir" | "remove" | "append"`. */
  kind: string
  /** Absolute guest path (text/file/mkdir/remove/append). */
  path?: string
  /** Host source path (copyFile/copyDir). */
  src?: string
  /** Guest destination path (copyFile/copyDir). */
  dst?: string
  /** Symlink target. */
  target?: string
  /** Symlink link path. */
  link?: string
  /** Text content (text/append). */
  content?: string
  /** Raw byte content (file). */
  contentBytes?: Array<number>
  /** File / directory permissions. */
  mode?: number
  /** Allow replacing an existing path. */
  replace?: boolean
}

/** Supported disk image formats for [`Mount.disk`] and the `disk()` rootfs. */
export declare const enum DiskImageFormat {
  Qcow2 = 'qcow2',
  Raw = 'raw',
  Vmdk = 'vmdk'
}

/** Options for disk-image volume mounts. */
export interface DiskOptions {
  /** Disk image format. When omitted, inferred from the file extension. */
  format?: DiskImageFormat
  /**
   * Inner filesystem type the guest should mount (e.g. `"ext4"`). When
   * omitted, agentd probes `/proc/filesystems`.
   */
  fstype?: string
  /** Read-only mount. */
  readonly?: boolean
}

/** DNS interception configuration produced by `DnsBuilder.build()`. */
export interface DnsConfig {
  blockedDomains: Array<string>
  blockedSuffixes: Array<string>
  rebindProtection: boolean
  /**
   * Nameservers serialized as their parse-roundtrippable string form
   * (e.g. `"1.1.1.1:53"`, `"dns.google:53"`).
   */
  nameservers: Array<string>
  /** Per-query timeout in milliseconds. Default: 5000. */
  queryTimeoutMs: number
}

/** DNS interception configuration. */
export interface DnsConfig {
  /** Block specific domains (returns REFUSED). */
  blockDomains?: Array<string>
  /** Block domain suffixes (returns REFUSED). */
  blockDomainSuffixes?: Array<string>
  /** Enable DNS rebinding protection (default: true). */
  rebindProtection?: boolean
  /**
   * Nameservers to forward queries to. Accepts `IP`, `IP:PORT`,
   * `HOST`, or `HOST:PORT`. When set, overrides the host's
   * /etc/resolv.conf.
   */
  nameservers?: Array<string>
  /** Per-DNS-query timeout in milliseconds (default: 5000). */
  queryTimeoutMs?: number
}

/** Configuration for command execution. */
export interface ExecConfig {
  /** Command to execute. */
  cmd: string
  /** Command arguments. */
  args?: Array<string>
  /** Working directory inside the sandbox. */
  cwd?: string
  /** User to run as. */
  user?: string
  /** Environment variables. */
  env?: Record<string, string>
  /** Timeout in milliseconds. */
  timeoutMs?: number
  /** Stdin mode: "null" (default), "pipe", or a string to send as stdin bytes. */
  stdin?: string
  /** Enable pseudo-TTY. */
  tty?: boolean
}

/** Execution event emitted by `ExecHandle.recv()`. */
export interface ExecEvent {
  /** "started", "stdout", "stderr", or "exited". */
  eventType: string
  /** Process ID (only for "started" events). */
  pid?: number
  /** Output data (only for "stdout" and "stderr" events). */
  data?: Buffer
  /** Exit code (only for "exited" events). */
  code?: number
}

/** Execution event type. */
export declare const enum ExecEventType {
  Started = 'started',
  Stdout = 'stdout',
  Stderr = 'stderr',
  Exited = 'exited'
}

/** Process exit status. */
export interface ExitStatus {
  code: number
  success: boolean
}

/** Filesystem entry metadata returned by `fs.list()`. */
export interface FsEntry {
  path: string
  /** "file", "directory", "symlink", or "other". */
  kind: string
  size: number
  mode: number
  modified?: number
}

/** Filesystem entry kind. */
export declare const enum FsEntryKind {
  File = 'file',
  Directory = 'directory',
  Symlink = 'symlink',
  Other = 'other'
}

/** Filesystem metadata returned by `fs.stat()`. */
export interface FsMetadata {
  /** "file", "directory", "symlink", or "other". */
  kind: string
  size: number
  mode: number
  readonly: boolean
  modified?: number
  created?: number
}

/** OCI config fields extracted from the database. */
export interface ImageConfigDetail {
  digest: string
  env: Array<string>
  cmd?: Array<string>
  entrypoint?: Array<string>
  workingDir?: string
  user?: string
  labelsJson?: string
  stopSignal?: string
}

/** Full image detail (config + layers + handle metadata). */
export interface ImageDetailJs {
  reference: string
  manifestDigest?: string
  architecture?: string
  os?: string
  layerCount: number
  sizeBytes?: number
  createdAt?: number
  lastUsedAt?: number
  config?: ImageConfigDetail
  layers: Array<ImageLayerDetail>
}

/** Garbage-collect everything reclaimable. Returns the number reclaimed. */
export declare function imageGc(): Promise<number>

/** Garbage-collect orphaned layers. Returns the number reclaimed. */
export declare function imageGcLayers(): Promise<number>

/** Look up a cached image by reference. */
export declare function imageGet(reference: string): Promise<ImageHandle>

/** Lightweight image info as returned by `imageList`. */
export interface ImageInfo {
  reference: string
  manifestDigest?: string
  architecture?: string
  os?: string
  layerCount: number
  sizeBytes?: number
  createdAt?: number
  lastUsedAt?: number
}

/** Full inspect (config + layers). */
export declare function imageInspect(reference: string): Promise<ImageDetailJs>

/** Metadata for a single layer. */
export interface ImageLayerDetail {
  diffId: string
  blobDigest: string
  mediaType?: string
  compressedSizeBytes?: number
  erofsSizeBytes?: number
  position: number
}

/** List all cached images. */
export declare function imageList(): Promise<Array<ImageInfo>>

/**
 * Remove a cached image. Pass `force = true` to delete even when a
 * sandbox references it.
 */
export declare function imageRemove(reference: string, force?: boolean | undefined | null): Promise<void>

/** Download and install msb + libkrunfw to ~/.microsandbox/. */
export declare function install(): Promise<void>

/** Check if msb and libkrunfw are installed and available. */
export declare function isInstalled(): boolean

/** Log level for sandbox process output. */
export declare const enum LogLevel {
  Trace = 'trace',
  Debug = 'debug',
  Info = 'info',
  Warn = 'warn',
  Error = 'error'
}

/** Volume mount configuration. */
export interface MountConfig {
  /** Mount a host directory. Mutually exclusive with `named`, `tmpfs`, `disk`. */
  bind?: string
  /** Mount a named volume. Mutually exclusive with `bind`, `tmpfs`, `disk`. */
  named?: string
  /** Use tmpfs (memory-backed). Mutually exclusive with `bind`, `named`, `disk`. */
  tmpfs?: boolean
  /**
   * Mount a host disk image as a virtio-blk device. Mutually exclusive
   * with `bind`, `named`, `tmpfs`.
   */
  disk?: string
  /**
   * Disk image format. Inferred from the file extension when omitted
   * (only meaningful with `disk`).
   */
  format?: DiskImageFormat
  /**
   * Inner filesystem type for disk image mounts (e.g. `"ext4"`). When
   * omitted, agentd probes `/proc/filesystems`.
   */
  fstype?: string
  /** Read-only mount. */
  readonly?: boolean
  /** Size limit in MiB (for tmpfs). */
  sizeMib?: number
}

/** Options for bind and named volume mounts. */
export interface MountOptions {
  /** Read-only mount. */
  readonly?: boolean
}

/** Network configuration. */
export interface NetworkConfig {
  /**
   * Preset policy: "public-only" (default), "allow-all", or "none".
   * Ignored if `rules` is provided.
   */
  policy?: string
  /** Custom policy rules (first match wins). Overrides `policy` preset. */
  rules?: Array<PolicyRule>
  /**
   * Default action for egress traffic when no rule matches: "allow" or
   * "deny". When omitted, falls through to today's `public_only`
   * behavior (deny + implicit allow public).
   */
  defaultEgress?: string
  /**
   * Default action for ingress traffic when no rule matches: "allow" or
   * "deny". When omitted, defaults to "allow" (today's unfiltered
   * published-port behavior).
   */
  defaultIngress?: string
  /** DNS interception configuration. */
  dns?: DnsConfig
  /** TLS interception configuration. */
  tls?: TlsConfig
  /** Max concurrent connections (default: 256). */
  maxConnections?: number
  /**
   * Ship the host's trusted CAs into the guest at boot so outbound TLS
   * works behind corporate MITM proxies (Warp Zero Trust, Zscaler,
   * etc.). Opt-in. Default: false.
   */
  trustHostCas?: boolean
}

/** Rootfs patch applied before VM startup. */
export interface PatchConfig {
  /** Patch kind: "text", "file", "copyFile", "copyDir", "symlink", "mkdir", "remove", "append". */
  kind: string
  /** Guest path (all kinds except symlink where it's `link`). */
  path?: string
  /** Text content (for "text" and "append" kinds). */
  content?: string
  /** Source host path (for "copyFile" and "copyDir" kinds). */
  src?: string
  /** Destination guest path (for "copyFile" and "copyDir" kinds). */
  dst?: string
  /** Symlink target path (for "symlink" kind). */
  target?: string
  /** Symlink link path (for "symlink" kind). */
  link?: string
  /** File permissions (e.g. 0o644). */
  mode?: number
  /** Allow replacing existing files. */
  replace?: boolean
}

/** Optional knobs accepted by `text`, `file`, `copyFile`. */
export interface PatchFileOptions {
  mode?: number
  replace?: boolean
}

/** Optional knobs accepted by `mkdir`. */
export interface PatchModeOnly {
  mode?: number
}

/** Options for `Patch.text()` and `Patch.copyFile()`. */
export interface PatchOptions {
  /** File permissions (e.g. 0o644). */
  mode?: number
  /** Allow replacing existing files. */
  replace?: boolean
}

/** Optional knobs accepted by `copyDir`, `symlink`. */
export interface PatchReplaceOnly {
  replace?: boolean
}

/** Options for `Patch.copyDir()` and `Patch.symlink()`. */
export interface PatchReplaceOptions {
  /** Allow replacing existing files/directories. */
  replace?: boolean
}

/** A network policy rule. */
export interface PolicyRule {
  /** "allow" or "deny". */
  action: string
  /**
   * "egress", "ingress", or "any". Legacy "outbound"/"inbound" still
   * accepted as aliases for "egress"/"ingress".
   */
  direction?: string
  /**
   * Destination filter. One of:
   * - "*" — any destination
   * - "1.2.3.4/24" — CIDR notation
   * - "example.com" — exact domain
   * - ".example.com" — domain suffix
   * - "public", "loopback", "private", "link-local", "metadata", "multicast", "host" — destination group
   */
  destination?: string
  /** Single-protocol filter (legacy). Prefer `protocols`. */
  protocol?: string
  /** Set of allowed protocols. Empty/missing = any. */
  protocols?: Array<string>
  /** Single port or range (legacy). Prefer `ports`. */
  port?: string
  /**
   * Set of allowed ports/ranges (e.g. ["80", "443", "8000-9000"]).
   * Empty/missing = any.
   */
  ports?: Array<string>
}

/** Image pull policy. */
export declare const enum PullPolicy {
  Always = 'always',
  IfMissing = 'if-missing',
  Never = 'never'
}

/** Registry authentication credentials. */
export interface RegistryAuth {
  username: string
  password: string
}

/** Plain-object form of `RegistryAuth`. `kind: "anonymous" | "basic"`. */
export interface RegistryAuthInput {
  kind: string
  username?: string
  password?: string
}

/** Registry connection settings. */
export interface RegistryConfig {
  /** Authentication credentials. */
  auth?: RegistryAuth
  /** Access the registry over plain HTTP instead of HTTPS. */
  insecure?: boolean
  /** Path to a PEM file containing additional CA root certificates to trust. */
  caCertsPath?: string
}

/** Configuration for creating a sandbox. */
export interface SandboxConfig {
  /** Unique sandbox name. */
  name: string
  /** OCI image ref (e.g. "python:3.12"), host path, or disk image path. */
  image: string
  /** Guest memory in MiB (default: 512). */
  memoryMib?: number
  /** Virtual CPU count (default: 1). */
  cpus?: number
  /** Working directory inside the guest. */
  workdir?: string
  /** Default shell binary path. */
  shell?: string
  /** Override image entrypoint. */
  entrypoint?: Array<string>
  /** Override image cmd. */
  cmd?: Array<string>
  /** Guest hostname. */
  hostname?: string
  /**
   * Override the libkrunfw shared library path for this sandbox.
   * Defaults to the global resolver (config path, sibling of `msb`, or
   * `~/.microsandbox/lib/`).
   */
  libkrunfwPath?: string
  /** User to run as (UID or name). */
  user?: string
  /** Environment variables. */
  env?: Record<string, string>
  /** Named scripts that can be run via `sandbox.run(name)`. */
  scripts?: Record<string, string>
  /** Volume mounts keyed by guest path. */
  volumes?: Record<string, MountConfig>
  /** Rootfs patches applied before boot. */
  patches?: Array<PatchConfig>
  /** Image pull policy: "always", "if-missing", or "never". */
  pullPolicy?: string
  /** Log level: "trace", "debug", "info", "warn", "error". */
  logLevel?: string
  /** Kill any existing sandbox with the same name before creating. */
  replace?: boolean
  /** Suppress log output. */
  quietLogs?: boolean
  /** Arbitrary key-value labels. */
  labels?: Record<string, string>
  /** Signal to send on stop (default: SIGTERM). */
  stopSignal?: string
  /** Maximum run duration in seconds. */
  maxDurationSecs?: number
  /** Registry connection settings (auth, TLS, insecure). */
  registry?: RegistryConfig
  /** Port mappings: host_port → guest_port (TCP). */
  ports?: Record<string, number>
  /** Network configuration. */
  network?: NetworkConfig
  /**
   * Secret entries. Created with `Secret.env()`.
   *
   * ```js
   * import { Secret } from 'microsandbox'
   * secrets: [
   *     Secret.env("OPENAI_API_KEY", { value: "sk-...", allowHosts: ["api.openai.com"] }),
   * ]
   * ```
   */
  secrets?: Array<SecretEntry>
}

/** Lightweight handle info for a sandbox from the database. */
export interface SandboxInfo {
  name: string
  /** "running", "stopped", "crashed", or "draining". */
  status: string
  configJson: string
  createdAt?: number
  updatedAt?: number
}

/** Point-in-time resource metrics for a sandbox. */
export interface SandboxMetrics {
  cpuPercent: number
  memoryBytes: number
  memoryLimitBytes: number
  diskReadBytes: number
  diskWriteBytes: number
  netRxBytes: number
  netTxBytes: number
  /** Uptime in milliseconds. */
  uptimeMs: number
  /** Timestamp as milliseconds since Unix epoch. */
  timestampMs: number
}

/** Sandbox status. */
export declare const enum SandboxStatus {
  Running = 'running',
  Stopped = 'stopped',
  Crashed = 'crashed',
  Draining = 'draining'
}

/** A secret entry produced by `SecretBuilder.build()`. */
export interface SecretEntry {
  /** Environment variable name exposed to the sandbox (holds the placeholder). */
  envVar: string
  /** Secret value (never enters the sandbox). */
  value: string
  /** Placeholder string the sandbox sees instead of the real value. */
  placeholder: string
  /** Exact host names allowed to receive this secret. */
  allowedHosts: Array<string>
  /** Wildcard host patterns (e.g. `*.openai.com`) allowed to receive this secret. */
  allowedHostPatterns: Array<string>
  /** Allow any host. **Dangerous** — secret can be exfiltrated. */
  allowAnyHost: boolean
  /** Require verified TLS identity before substituting (default: true). */
  requireTlsIdentity: boolean
  /** Where the secret may be injected into requests. */
  injection: JsSecretInjection
}

/**
 * A secret entry for the `secrets` array on `SandboxConfig`.
 *
 * Created via `Secret.env()`:
 * ```js
 * import { Secret } from 'microsandbox'
 * Secret.env("OPENAI_API_KEY", { value: "sk-...", allowHosts: ["api.openai.com"] })
 * ```
 */
export interface SecretEntry {
  /** Environment variable name. */
  envVar: string
  /** The secret value (never enters the sandbox). */
  value: string
  /** Allowed hosts (exact match, e.g. `["api.openai.com"]`). */
  allowHosts?: Array<string>
  /** Allowed host patterns (wildcard, e.g. `["*.openai.com"]`). */
  allowHostPatterns?: Array<string>
  /** Custom placeholder (auto-generated as `$MSB_<ENV_VAR>` if omitted). */
  placeholder?: string
  /** Require verified TLS identity before substitution (default: true). */
  requireTls?: boolean
  /** Violation action: "block", "block-and-log" (default), "block-and-terminate". */
  onViolation?: string
  /**
   * Where in the HTTP request the secret can be injected.
   * Defaults to `{ headers: true, basicAuth: true, queryParams: false, body: false }`.
   */
  inject?: SecretInjection
}

/** Options for `Secret.env()`. */
export interface SecretEnvOptions {
  /** The secret value (never enters the sandbox). */
  value: string
  /** Allowed hosts (exact match, e.g. `["api.openai.com"]`). */
  allowHosts?: Array<string>
  /** Allowed host patterns (wildcard, e.g. `["*.openai.com"]`). */
  allowHostPatterns?: Array<string>
  /** Custom placeholder (auto-generated as `$MSB_<ENV_VAR>` if omitted). */
  placeholder?: string
  /** Require verified TLS identity before substitution (default: true). */
  requireTls?: boolean
  /** Violation action: "block", "block-and-log" (default), "block-and-terminate". */
  onViolation?: string
  /**
   * Where in the HTTP request the secret can be injected. Defaults to
   * headers + Basic Auth only; enable `queryParams` or `body` to widen scope.
   */
  inject?: SecretInjection
}

/** Injection sites for a secret value. */
export interface SecretInjection {
  headers: boolean
  basicAuth: boolean
  queryParams: boolean
  body: boolean
}

/**
 * Controls where the secret placeholder is substituted by the TLS proxy.
 *
 * By default, substitution happens in HTTP headers (including the
 * `Authorization` header for Basic Auth). Enable `queryParams` or `body`
 * to expand the scope to the request line query string or the request body.
 * When `body` is enabled, the proxy also rewrites `Content-Length` to match.
 *
 * ```js
 * Secret.env("API_KEY", {
 *   value: "sk-...",
 *   allowHosts: ["api.example.com"],
 *   inject: { headers: false, body: true },
 * })
 * ```
 */
export interface SecretInjection {
  /** Substitute in HTTP headers (default: true). */
  headers?: boolean
  /** Substitute in HTTP Basic Auth (default: true). */
  basicAuth?: boolean
  /** Substitute in URL query parameters (default: false). */
  queryParams?: boolean
  /**
   * Substitute in request body (default: false).
   * When enabled, `Content-Length` is rewritten to match the new body size.
   */
  body?: boolean
}

/** TLS interception configuration produced by `TlsBuilder.build()`. */
export interface TlsConfig {
  enabled: boolean
  bypass: Array<string>
  verifyUpstream: boolean
  interceptedPorts: Array<number>
  blockQuic: boolean
  upstreamCaCertPaths: Array<string>
  interceptCaCertPath?: string
  interceptCaKeyPath?: string
}

/** TLS interception configuration. */
export interface TlsConfig {
  /** Domains to bypass (no interception). Supports "*.suffix" wildcards. */
  bypass?: Array<string>
  /** Verify upstream server certificates (default: true). */
  verifyUpstream?: boolean
  /** Ports to intercept (default: [443]). */
  interceptedPorts?: Array<number>
  /** Block QUIC on intercepted ports (default: false). */
  blockQuic?: boolean
  /** Path to custom interception CA certificate PEM file. */
  interceptCaCert?: string
  /** Path to custom interception CA private key PEM file. */
  interceptCaKey?: string
  /** Paths to additional CA certificate PEM files to trust for upstream verification. */
  upstreamCaCert?: Array<string>
}

/** Options for tmpfs mounts. */
export interface TmpfsOptions {
  /** Size limit in MiB. */
  sizeMib?: number
  /** Read-only mount. */
  readonly?: boolean
}

/** Action to take when a secret is sent to a disallowed host. */
export declare const enum ViolationAction {
  /** Silently block the request. */
  Block = 'block',
  /** Block the request and log the violation. */
  BlockAndLog = 'block-and-log',
  /** Block the request and terminate the sandbox. */
  BlockAndTerminate = 'block-and-terminate'
}

/** Volume configuration for creation. */
export interface VolumeConfig {
  name: string
  /** Size quota in MiB. */
  quotaMib?: number
  /** Arbitrary key-value labels. */
  labels?: Record<string, string>
}

/** Volume handle info from the database. */
export interface VolumeInfo {
  name: string
  quotaMib?: number
  usedBytes: number
  labels: Record<string, string>
  createdAt?: number
}
