/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Fluent builder for interactive attach options. */
export declare class AttachOptionsBuilder {
  constructor()
  /** Append a single command argument. */
  arg(arg: string): this
  /** Append a list of command arguments. */
  args(args: Array<string>): this
  /** Override the working directory. */
  cwd(cwd: string): this
  /** Override the running user. */
  user(user: string): this
  /** Set a single environment variable. */
  env(key: string, value: string): this
  /** Set environment variables from an object. */
  envs(vars: Record<string, string>): this
  /**
   * Override the detach key sequence (Docker-style spec, e.g. `"ctrl-]"` or
   * `"ctrl-p,ctrl-q"`). Default: `Ctrl+]`.
   */
  detachKeys(keys: string): this
  /** Set a hard rlimit (soft = hard). */
  rlimit(resource: string, limit: number): this
  /** Set a separate soft and hard rlimit. */
  rlimitRange(resource: string, soft: number, hard: number): this
}
export type JsAttachOptionsBuilder = AttachOptionsBuilder

/**
 * Fluent builder for DNS interception settings.
 *
 * Mirrors `microsandbox_network::builder::DnsBuilder` 1:1; setters
 * mutate in place and return `this`. Errors from invalid block-domain
 * strings accumulate and surface from the terminal `.build()` call.
 */
export declare class DnsBuilder {
  constructor()
  /** Block a specific FQDN (returns REFUSED at the resolver). */
  blockDomain(domain: string): this
  /** Block any name ending in `suffix`. */
  blockDomainSuffix(suffix: string): this
  /** Enable or disable DNS rebinding protection. Default: true. */
  rebindProtection(enabled: boolean): this
  /**
   * Set the upstream nameservers. Replaces any previous set.
   * Each entry accepts the same forms as Rust: `"1.1.1.1"`,
   * `"1.1.1.1:53"`, `"dns.google"`, `"dns.google:53"`.
   */
  nameservers(servers: Array<string>): this
  /** Set the per-query timeout in milliseconds. Default: 5000. */
  queryTimeoutMs(ms: number): this
  /**
   * Materialize the accumulated state into a `DnsConfig`. Surfaces
   * the first invalid-domain error accumulated by `blockDomain` /
   * `blockDomainSuffix`, if any.
   */
  build(): DnsConfig
}
export type JsDnsBuilder = DnsBuilder

/**
 * Handle for a streaming command execution.
 *
 * Use `recv()` to get events one at a time, or iterate with a loop:
 * ```js
 * const handle = await sandbox.execStream("tail", ["-f", "/var/log/app.log"]);
 * let event;
 * while ((event = await handle.recv()) !== null) {
 *   if (event.eventType === "stdout") process.stdout.write(event.data);
 * }
 * ```
 */
export declare class ExecHandle {
  /** Get the correlation ID for this execution. */
  get id(): Promise<string>
  /** Receive the next event. Returns `null` when the stream ends. */
  recv(): Promise<ExecEvent | null>
  /** Take the stdin writer. Can only be called once; returns `null` on subsequent calls. */
  takeStdin(): Promise<ExecSink | null>
  /** Wait for the process to exit and return the exit status. */
  wait(): Promise<ExitStatus>
  /** Wait for completion and collect all output. */
  collect(): Promise<ExecOutput>
  /** Send a signal to the running process. */
  signal(signal: number): Promise<void>
  /** Kill the running process (SIGKILL). */
  kill(): Promise<void>
}
export type JsExecHandle = ExecHandle

/** Fluent builder for per-execution overrides. */
export declare class ExecOptionsBuilder {
  constructor()
  /** Append a single command argument. */
  arg(arg: string): this
  /** Append a list of command arguments. */
  args(args: Array<string>): this
  /** Override the working directory for this exec. */
  cwd(cwd: string): this
  /** Override the running user for this exec. */
  user(user: string): this
  /** Set a single environment variable. */
  env(key: string, value: string): this
  /** Set environment variables from an object. */
  envs(vars: Record<string, string>): this
  /** Kill the process if it hasn't exited within `ms` milliseconds. */
  timeout(ms: number): this
  /** Connect stdin to /dev/null (default). */
  stdinNull(): this
  /** Open a writable stdin pipe (use `ExecHandle.takeStdin()`). */
  stdinPipe(): this
  /** Pipe a fixed byte payload as stdin. */
  stdinBytes(data: Buffer): this
  /** Allocate a pseudo-terminal (default: false). */
  tty(enabled: boolean): this
  /** Set a hard rlimit (soft = hard). */
  rlimit(resource: string, limit: number): this
  /** Set a separate soft and hard rlimit. */
  rlimitRange(resource: string, soft: number, hard: number): this
}
export type JsExecOptionsBuilder = ExecOptionsBuilder

/**
 * Output of a completed command execution.
 *
 * Provides both string and raw byte access to stdout/stderr:
 * ```js
 * const output = await sandbox.shell("echo hello");
 * console.log(output.stdout());       // "hello
"
 * console.log(output.stdoutBytes());   // <Buffer 68 65 6c 6c 6f 0a>
 * console.log(output.code);            // 0
 * console.log(output.success);         // true
 * ```
 */
export declare class ExecOutput {
  /** Exit code of the process. */
  get code(): number
  /** Whether the process exited successfully (code == 0). */
  get success(): boolean
  /** Get stdout as a UTF-8 string. */
  stdout(): string
  /** Get stderr as a UTF-8 string. */
  stderr(): string
  /** Get stdout as raw bytes. */
  stdoutBytes(): Buffer
  /** Get stderr as raw bytes. */
  stderrBytes(): Buffer
  /** Get the exit status. */
  status(): ExitStatus
}

/** Stdin writer for a running process. */
export declare class ExecSink {
  /** Write data to the process stdin. */
  write(data: Buffer): Promise<void>
  /** Close stdin (sends EOF to the process). */
  close(): Promise<void>
}
export type JsExecSink = ExecSink

/**
 * A streaming reader for file data from the sandbox.
 *
 * Supports both manual `recv()` calls and `for await...of` iteration:
 * ```js
 * const stream = await sb.fs().readStream("/app/data.bin");
 * for await (const chunk of stream) {
 *   processChunk(chunk);
 * }
 * ```
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class FsReadStream {
  /** Receive the next chunk of data. Returns `null` when the stream ends. */
  recv(): Promise<Buffer | null>
  [Symbol.asyncIterator](): AsyncGenerator<Buffer, void, undefined>
}
export type JsFsReadStream = FsReadStream

/** Streaming writer for guest files. */
export declare class FsWriteSink {
  /** Write a chunk to the underlying file. */
  write(data: Buffer): Promise<void>
  /** Flush and close the sink. Idempotent. */
  close(): Promise<void>
}
export type JsFsWriteSink = FsWriteSink

/**
 * Fluent builder for a disk-image rootfs source.
 *
 * Used inside `Sandbox.builder(...).imageWith((i) => i.disk(...).fstype(...))`
 * to construct a `RootfsSource::DiskImage`. Standalone use is rare;
 * `.image("./ubuntu.qcow2")` resolves the same way for the common case.
 */
export declare class ImageBuilder {
  constructor()
  /**
   * Use a host disk image file as the root filesystem. The format is
   * derived from the file extension: `.qcow2`, `.raw`, or `.vmdk`.
   */
  disk(path: string): this
  /**
   * Set the inner filesystem type (e.g. `"ext4"`). Omit to let agentd
   * auto-detect by probing `/proc/filesystems`.
   */
  fstype(fstype: string): this
}
export type JsImageBuilder = ImageBuilder

/** A lightweight handle to a cached image. */
export declare class ImageHandle {
  get reference(): string
  get sizeBytes(): number | null
  get manifestDigest(): string | null
  get architecture(): string | null
  get os(): string | null
  get layerCount(): number
  get lastUsedAt(): number | null
  get createdAt(): number | null
}
export type JsImageHandle = ImageHandle

/**
 * A streaming subscription for sandbox metrics at a regular interval.
 *
 * Supports both manual `recv()` calls and `for await...of` iteration:
 * ```js
 * const stream = await sb.metricsStream(1000);
 * for await (const m of stream) {
 *   console.log(`CPU: ${m.cpuPercent.toFixed(1)}%`);
 * }
 * ```
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MetricsStream {
  /** Receive the next metrics snapshot. Returns `null` when the stream ends. */
  recv(): Promise<SandboxMetrics | null>
  [Symbol.asyncIterator](): AsyncGenerator<SandboxMetrics, void, undefined>
}
export type JsMetricsStream = MetricsStream

/**
 * Fluent builder for a sandbox volume mount.
 *
 * Pick exactly one mount kind via `.bind()`, `.named()`, `.tmpfs()`, or
 * `.disk(...)`, then chain modifiers (`.readonly()`, `.size(mib)` for
 * tmpfs, `.format(fmt)` / `.fstype(s)` for disk). Validation is deferred
 * to the terminal `.build()` call.
 */
export declare class MountBuilder {
  constructor(guest: string)
  /** Bind a host directory at the guest path. */
  bind(host: string): this
  /** Mount a named volume created via `Volume.builder(name).create()`. */
  named(name: string): this
  /** Mount an in-memory tmpfs at the guest path. */
  tmpfs(): this
  /** Mount a host disk image file as a virtio-blk device. */
  disk(host: string): this
  /**
   * Override the disk image format (`"qcow2" | "raw" | "vmdk"`). Only
   * valid when paired with `.disk()`.
   */
  format(format: string): this
  /** Inner filesystem type for a `.disk()` mount (e.g. `"ext4"`). */
  fstype(fstype: string): this
  /** Mark the mount read-only. */
  readonly(): this
  /** Tmpfs size cap in MiB (only valid with `.tmpfs()`). */
  size(mib: number): this
}
export type JsMountBuilder = MountBuilder

/** Fluent builder for sandbox network configuration. */
export declare class NetworkBuilder {
  constructor()
  /** Enable or disable networking. */
  enabled(enabled: boolean): this
  /** Publish a TCP port. */
  port(hostPort: number, guestPort: number): this
  /** Publish a UDP port. */
  portUdp(hostPort: number, guestPort: number): this
  /**
   * Set a policy. Construct via the JS-side `NetworkPolicy.publicOnly()`
   * / `.allowAll()` / `.none()` / `.nonLocal()` factories or build a
   * custom one and pass it through `JSON.stringify`-friendly JSON. Here
   * we accept the canonical serialized form (a JSON string) to avoid
   * re-modeling the rule schema across the FFI; Phase 7 reconciles.
   */
  policyJson(json: string): this
  /**
   * Configure DNS interception via a callback. The callback receives
   * a fresh `DnsBuilder`; chain setters on it and return.
   */
  dns(configure: (arg: DnsBuilder) => DnsBuilder): this
  /** Configure TLS interception via a callback. */
  tls(configure: (arg: JsTlsBuilder) => JsTlsBuilder): this
  /** Add a secret via a callback. */
  secret(configure: (arg: JsSecretBuilder) => JsSecretBuilder): this
  /** 4-arg shorthand: add a secret with explicit placeholder. */
  secretEnv(envVar: string, value: string, placeholder: string, allowedHost: string): this
  /**
   * Set the violation action for secrets: `"block" | "block-and-log"
   * | "block-and-terminate"`.
   */
  onSecretViolation(action: string): this
  /** Set the maximum number of concurrent connections. */
  maxConnections(max: number): this
  /** Trust the host's root CAs inside the guest. Default: false. */
  trustHostCAs(enabled: boolean): this
}
export type JsNetworkBuilder = NetworkBuilder

/** Fluent builder for an ordered list of pre-boot rootfs patches. */
export declare class PatchBuilder {
  constructor()
  /** Write a text file (UTF-8) at `path`. */
  text(path: string, content: string, opts?: PatchFileOptions | undefined | null): this
  /** Write raw bytes at `path`. */
  file(path: string, content: Buffer, opts?: PatchFileOptions | undefined | null): this
  /** Copy a host file into the rootfs at `dst`. */
  copyFile(src: string, dst: string, opts?: PatchFileOptions | undefined | null): this
  /** Copy a host directory into the rootfs at `dst`. */
  copyDir(src: string, dst: string, opts?: PatchReplaceOnly | undefined | null): this
  /** Create a symlink at `link` pointing to `target`. */
  symlink(target: string, link: string, opts?: PatchReplaceOnly | undefined | null): this
  /** Create a directory (idempotent). */
  mkdir(path: string, opts?: PatchModeOnly | undefined | null): this
  /** Remove a file or directory (idempotent). */
  remove(path: string): this
  /** Append text to an existing file. */
  append(path: string, content: string): this
  /** Materialize into the ordered list of patches. */
  build(): Array<BuiltPatch>
}
export type JsPatchBuilder = PatchBuilder

/** Fluent builder for OCI registry connection settings. */
export declare class RegistryConfigBuilder {
  constructor()
  /** Set authentication credentials. */
  auth(auth: RegistryAuthInput): this
  /** Use plain HTTP (no TLS). */
  insecure(): this
  /** Add a PEM-encoded CA root certificate to trust. May be called repeatedly. */
  caCerts(pemData: Buffer): this
}
export type JsRegistryConfigBuilder = RegistryConfigBuilder

/**
 * A running sandbox instance.
 *
 * Created via `Sandbox.create()` or `Sandbox.start()`. Holds a live connection
 * to the guest VM and can execute commands, access the filesystem, and query metrics.
 */
export declare class Sandbox {
  /** Start an existing stopped sandbox (attached mode). */
  static start(name: string): Promise<Sandbox>
  /** Start an existing stopped sandbox (detached mode). */
  static startDetached(name: string): Promise<Sandbox>
  /** Get a lightweight handle to an existing sandbox. */
  static get(name: string): Promise<JsSandboxHandle>
  /** List all sandboxes. */
  static list(): Promise<Array<SandboxInfo>>
  /** Remove a stopped sandbox from the database. */
  static remove(name: string): Promise<void>
  /** Sandbox name. */
  get name(): Promise<string>
  /** Whether this handle owns the sandbox lifecycle (attached mode). */
  get ownsLifecycle(): Promise<boolean>
  /** Execute a command and wait for completion. */
  exec(cmd: string, args?: Array<string> | undefined | null): Promise<ExecOutput>
  /**
   * Execute a command using a populated `ExecOptionsBuilder`. The TS
   * layer wraps this in a closure-callback API (`execWith(cmd, b => …)`).
   */
  execWithBuilder(cmd: string, builder: ExecOptionsBuilder): Promise<ExecOutput>
  /** Execute a command with streaming I/O. */
  execStream(cmd: string, args?: Array<string> | undefined | null): Promise<ExecHandle>
  /**
   * Execute a command with streaming I/O using a populated
   * `ExecOptionsBuilder`. The TS layer wraps this in a closure-callback
   * API (`execStreamWith(cmd, b => …)`). Set `b.stdinPipe()` on the
   * builder for bidirectional streams.
   */
  execStreamWithBuilder(cmd: string, builder: ExecOptionsBuilder): Promise<ExecHandle>
  /** Execute a shell command using the sandbox's configured shell. */
  shell(script: string): Promise<ExecOutput>
  /** Execute a shell command with streaming I/O. */
  shellStream(script: string): Promise<ExecHandle>
  /** Get a filesystem handle for operations on the running sandbox. */
  fs(): SandboxFs
  /** Get point-in-time resource metrics. */
  metrics(): Promise<SandboxMetrics>
  /** Stream metrics snapshots at the requested interval (in milliseconds). */
  metricsStream(intervalMs: number): Promise<MetricsStream>
  /**
   * Attach to an interactive PTY session inside the sandbox.
   *
   * Bridges the host terminal to the guest process. Returns the exit code.
   */
  attach(cmd: string, args?: Array<string> | undefined | null): Promise<number>
  /**
   * Attach using a populated `AttachOptionsBuilder`. The TS layer
   * wraps this in a closure-callback API (`attachWith(cmd, b => …)`).
   */
  attachWithBuilder(cmd: string, builder: AttachOptionsBuilder): Promise<number>
  /** Attach to the sandbox's default shell. */
  attachShell(): Promise<number>
  /** Stop the sandbox gracefully (SIGTERM). */
  stop(): Promise<void>
  /** Stop and wait for exit, returning the exit status. */
  stopAndWait(): Promise<ExitStatus>
  /** Kill the sandbox immediately (SIGKILL). */
  kill(): Promise<void>
  /** Graceful drain (SIGUSR1 — for load balancing). */
  drain(): Promise<void>
  /** Wait for the sandbox process to exit. */
  wait(): Promise<ExitStatus>
  /** Detach from the sandbox — it will continue running after this handle is dropped. */
  detach(): Promise<void>
  /** Remove the persisted database record after stopping. */
  removePersisted(): Promise<void>
}

/**
 * Fluent builder for a sandbox. Mirrors `microsandbox::sandbox::SandboxBuilder`
 * 1:1; setters mutate in place and return `this`. Closure-style
 * sub-builders (volume / patch / network / secret / registry / imageWith)
 * receive a fresh napi-wrapped builder, let JS chain on it, and route
 * the result back through the core SDK's closure callback.
 */
export declare class SandboxBuilder {
  constructor(name: string)
  /**
   * Set the rootfs image source. Accepts an OCI reference or a host
   * path (paths starting with `/`, `./`, `../` resolve as local; disk
   * image extensions `.qcow2`/`.raw`/`.vmdk` resolve to virtio-blk).
   */
  image(image: string): this
  /** Configure a disk-image rootfs explicitly via a callback. */
  imageWith(configure: (arg: ImageBuilder) => ImageBuilder): this
  /** Number of virtual CPUs. */
  cpus(count: number): this
  /** Guest memory in MiB. */
  memory(mib: number): this
  /** Override log verbosity: `"trace" | "debug" | "info" | "warn" | "error"`. */
  logLevel(level: string): this
  /** Suppress sandbox logs. */
  quietLogs(): this
  /** Default working directory for commands. */
  workdir(path: string): this
  /** Shell binary used by `Sandbox.shell(...)`. */
  shell(shell: string): this
  /** Configure registry connection settings via a callback. */
  registry(configure: (arg: RegistryConfigBuilder) => RegistryConfigBuilder): this
  /** Replace any existing sandbox with the same name. */
  replace(): this
  /** Override the image entrypoint. */
  entrypoint(cmd: Array<string>): this
  /** Override the guest hostname. */
  hostname(name: string): this
  /** Override the libkrunfw shared library path for this sandbox. */
  libkrunfwPath(path: string): this
  /** Default running user. */
  user(user: string): this
  /** Image pull policy: `"always" | "if-missing" | "never"`. */
  pullPolicy(policy: string): this
  /** Disable networking entirely. */
  disableNetwork(): this
  /** Configure networking via a callback. */
  network(configure: (arg: NetworkBuilder) => NetworkBuilder): this
  /** Publish a TCP port from host -> guest. */
  port(hostPort: number, guestPort: number): this
  /** Publish a UDP port from host -> guest. */
  portUdp(hostPort: number, guestPort: number): this
  /** Add a secret via a callback. */
  secret(configure: (arg: JsSecretBuilder) => JsSecretBuilder): this
  /**
   * Shorthand: add a secret. Auto-generates the placeholder as
   * `$MSB_<env_var>` and allows substitution only on `allowed_host`.
   */
  secretEnv(envVar: string, value: string, allowedHost: string): this
  /** Set a single environment variable. */
  env(key: string, value: string): this
  /** Set environment variables from an object. */
  envs(vars: Record<string, string>): this
  /** Set a hard rlimit (soft = hard). */
  rlimit(resource: string, limit: number): this
  /** Set a separate soft and hard rlimit. */
  rlimitRange(resource: string, soft: number, hard: number): this
  /** Mount a script under `/.msb/scripts/<name>` inside the guest. */
  script(name: string, content: string): this
  /** Mount many scripts at once. */
  scripts(scripts: Record<string, string>): this
  /** Auto-stop after `secs` seconds. */
  maxDuration(secs: number): this
  /** Auto-stop after `secs` seconds of inactivity. */
  idleTimeout(secs: number): this
  /**
   * Configure a volume mount via a callback. The callback receives a
   * `MountBuilder` already pre-bound to `guestPath`.
   */
  volume(guestPath: string, configure: (arg: MountBuilder) => MountBuilder): this
  /** Apply rootfs patches via a callback. */
  patch(configure: (arg: PatchBuilder) => PatchBuilder): this
  /**
   * Materialize the built configuration without creating a sandbox.
   * Returns the JSON-serialized `SandboxConfig` for inspection.
   */
  build(): string
  /**
   * Create and start the sandbox in attached mode.
   *
   * # Safety
   * `&mut self` async is required because we drain `inner`
   * synchronously before awaiting; napi-rs requires the `unsafe` tag
   * regardless. JS callers see `create(): Promise<Sandbox>`.
   */
  create(): Promise<JsSandbox>
  /**
   * Create and start the sandbox in detached mode (survives the
   * parent process).
   *
   * # Safety
   * Same justification as `create`.
   */
  createDetached(): Promise<JsSandbox>
}
export type JsSandboxBuilder = SandboxBuilder

/** Filesystem operations on a running sandbox (via agent protocol). */
export declare class SandboxFs {
  /** Read a file as a Buffer. */
  read(path: string): Promise<Buffer>
  /** Read a file as a UTF-8 string. */
  readString(path: string): Promise<string>
  /** Write data to a file (accepts Buffer or string). */
  write(path: string, data: Buffer): Promise<void>
  /** List directory contents. */
  list(path: string): Promise<Array<FsEntry>>
  /** Create a directory. */
  mkdir(path: string): Promise<void>
  /** Remove a directory. */
  removeDir(path: string): Promise<void>
  /** Remove a file. */
  remove(path: string): Promise<void>
  /** Copy a file within the sandbox. */
  copy(from: string, to: string): Promise<void>
  /** Rename a file within the sandbox. */
  rename(from: string, to: string): Promise<void>
  /** Get file or directory metadata. */
  stat(path: string): Promise<FsMetadata>
  /** Check if a path exists. */
  exists(path: string): Promise<boolean>
  /** Copy a file from the host into the sandbox. */
  copyFromHost(hostPath: string, guestPath: string): Promise<void>
  /** Copy a file from the sandbox to the host. */
  copyToHost(guestPath: string, hostPath: string): Promise<void>
  /** Read a file with streaming (~3 MiB chunks). */
  readStream(path: string): Promise<FsReadStream>
  /** Write a file with streaming. Returns a sink the caller writes to. */
  writeStream(path: string): Promise<FsWriteSink>
}
export type JsSandboxFs = SandboxFs

/**
 * A lightweight handle to a sandbox from the database.
 *
 * Does NOT hold a live connection — use `connect()` or `start()` to get a live `Sandbox`.
 */
export declare class SandboxHandle {
  /** Sandbox name. */
  get name(): string
  /** Status at time of query: "running", "stopped", "crashed", or "draining". */
  get status(): string
  /** Raw config JSON string from the database. */
  get configJson(): string
  /** Creation timestamp as ms since Unix epoch. */
  get createdAt(): number | null
  /** Last update timestamp as ms since Unix epoch. */
  get updatedAt(): number | null
  /** Get point-in-time metrics from the database. */
  metrics(): Promise<SandboxMetrics>
  /** Start the sandbox (attached mode) — returns a live Sandbox handle. */
  start(): Promise<Sandbox>
  /** Start the sandbox (detached mode). */
  startDetached(): Promise<Sandbox>
  /** Connect to an already-running sandbox (no lifecycle ownership). */
  connect(): Promise<Sandbox>
  /** Stop the sandbox (SIGTERM). */
  stop(): Promise<void>
  /** Kill the sandbox (SIGKILL). */
  kill(): Promise<void>
  /** Remove the sandbox from the database. */
  remove(): Promise<void>
}
export type JsSandboxHandle = SandboxHandle

/** Fluent builder for a single secret entry. */
export declare class SecretBuilder {
  constructor()
  /** Environment variable to expose the placeholder under (required). */
  env(var: string): this
  /** Secret value (required). */
  value(value: string): this
  /** Custom placeholder. Auto-generated as `$MSB_<env>` when unset. */
  placeholder(placeholder: string): this
  /** Add an allowed exact-match host. */
  allowHost(host: string): this
  /** Add an allowed wildcard host pattern (e.g. `*.openai.com`). */
  allowHostPattern(pattern: string): this
  /**
   * Allow any host. **Dangerous** — secret can be exfiltrated.
   * Pass `true` to opt in.
   */
  allowAnyHostDangerous(iUnderstand: boolean): this
  /** Require verified TLS identity before substituting (default: true). */
  requireTlsIdentity(enabled: boolean): this
  /** Configure header injection (default: true). */
  injectHeaders(enabled: boolean): this
  /** Configure Basic Auth injection (default: true). */
  injectBasicAuth(enabled: boolean): this
  /** Configure URL query parameter injection (default: false). */
  injectQuery(enabled: boolean): this
  /** Configure request body injection (default: false). */
  injectBody(enabled: boolean): this
  /**
   * Materialize into a `SecretEntry`. Panics if `env` or `value` weren't
   * set (matches the underlying Rust builder's contract; surface as a
   * typed error here).
   */
  build(): SecretEntry
}
export type JsSecretBuilder = SecretBuilder

/** Builder for installing the runtime binaries. */
export declare class Setup {
  constructor()
  baseDir(path: string): this
  version(version: string): this
  skipVerify(enabled: boolean): this
  force(enabled: boolean): this
  install(): Promise<void>
}
export type JsSetup = Setup

/** Fluent builder for TLS interception settings. */
export declare class TlsBuilder {
  constructor()
  /** Add a bypass pattern (no MITM). Supports `*.suffix` wildcards. */
  bypass(pattern: string): this
  /** Verify upstream server certificates (default: true). */
  verifyUpstream(verify: boolean): this
  /** Set the ports to intercept (default: 443). */
  interceptedPorts(ports: Array<number>): this
  /** Block QUIC on intercepted ports (default: true). */
  blockQuic(block: boolean): this
  /** Add an upstream CA certificate PEM path. May be called repeatedly. */
  upstreamCaCert(path: string): this
  /** Set a custom interception CA certificate PEM path. */
  interceptCaCert(path: string): this
  /** Set a custom interception CA private key PEM path. */
  interceptCaKey(path: string): this
  /** Materialize into a `TlsConfig`. */
  build(): TlsConfig
}
export type JsTlsBuilder = TlsBuilder

export declare class Volume {
  static get(name: string): Promise<VolumeHandle>
  static list(): Promise<Array<VolumeInfo>>
  static remove(name: string): Promise<void>
  get name(): string
  get path(): string
  /** Host-side filesystem operations on this volume's directory. */
  fs(): VolumeFs
}
export type JsVolume = Volume

/** Fluent builder for a named persistent volume. */
export declare class VolumeBuilder {
  constructor(name: string)
  /** Limit the volume's storage capacity (MiB). Omit for unlimited. */
  quota(mib: number): this
  /** Attach a key-value label. May be called multiple times. */
  label(key: string, value: string): this
  /**
   * Create the volume.
   *
   * Marked `unsafe` only because `napi-rs` requires `&mut self` async
   * methods to be tagged that way (a half-mutated struct could be
   * observed mid-await). Practically it's safe: we take the inner
   * builder synchronously before the await point, leaving an empty
   * `Option` behind that subsequent calls reject. JS users do not see
   * the `unsafe` marker.
   *
   * # Safety
   * The await-point hazard does not apply here because we drain the
   * inner builder before awaiting.
   */
  create(): Promise<Volume>
}
export type JsVolumeBuilder = VolumeBuilder

export declare class VolumeFs {
  read(path: string): Promise<Buffer>
  readString(path: string): Promise<string>
  readStream(path: string): Promise<VolumeFsReadStream>
  write(path: string, data: Buffer): Promise<void>
  writeStream(path: string): Promise<VolumeFsWriteSink>
  list(path: string): Promise<Array<FsEntry>>
  mkdir(path: string): Promise<void>
  removeDir(path: string): Promise<void>
  remove(path: string): Promise<void>
  copy(from: string, to: string): Promise<void>
  rename(from: string, to: string): Promise<void>
  stat(path: string): Promise<FsMetadata>
  exists(path: string): Promise<boolean>
}
export type JsVolumeFs = VolumeFs

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class VolumeFsReadStream {
  recv(): Promise<Buffer | null>
  [Symbol.asyncIterator](): AsyncGenerator<Buffer, void, undefined>
}
export type JsVolumeFsReadStream = VolumeFsReadStream

export declare class VolumeFsWriteSink {
  write(data: Buffer): Promise<void>
  close(): Promise<void>
}
export type JsVolumeFsWriteSink = VolumeFsWriteSink

export declare class VolumeHandle {
  get name(): string
  get quotaMib(): number | null
  get usedBytes(): number
  get labels(): Record<string, string>
  get createdAt(): number | null
  remove(): Promise<void>
  /** Host-side filesystem operations on this volume's directory. */
  fs(): VolumeFs
}
export type JsVolumeHandle = VolumeHandle

/** Get metrics for all running sandboxes. */
export declare function allSandboxMetrics(): Promise<Record<string, SandboxMetrics>>

/**
 * Built rootfs patch (flat representation of the `Patch` enum: `kind`
 * + per-variant fields).
 */
export interface BuiltPatch {
  /** `"text" | "file" | "copyFile" | "copyDir" | "symlink" | "mkdir" | "remove" | "append"`. */
  kind: string
  /** Absolute guest path (text/file/mkdir/remove/append). */
  path?: string
  /** Host source path (copyFile/copyDir). */
  src?: string
  /** Guest destination path (copyFile/copyDir). */
  dst?: string
  /** Symlink target. */
  target?: string
  /** Symlink link path. */
  link?: string
  /** Text content (text/append). */
  content?: string
  /** Raw byte content (file). */
  contentBytes?: Array<number>
  /** File / directory permissions. */
  mode?: number
  /** Allow replacing an existing path. */
  replace?: boolean
}

/** DNS interception configuration produced by `DnsBuilder.build()`. */
export interface DnsConfig {
  blockedDomains: Array<string>
  blockedSuffixes: Array<string>
  rebindProtection: boolean
  /**
   * Nameservers serialized as their parse-roundtrippable string form
   * (e.g. `"1.1.1.1:53"`, `"dns.google:53"`).
   */
  nameservers: Array<string>
  /** Per-query timeout in milliseconds. Default: 5000. */
  queryTimeoutMs: number
}

/** Execution event emitted by `ExecHandle.recv()`. */
export interface ExecEvent {
  /** "started", "stdout", "stderr", or "exited". */
  eventType: string
  /** Process ID (only for "started" events). */
  pid?: number
  /** Output data (only for "stdout" and "stderr" events). */
  data?: Buffer
  /** Exit code (only for "exited" events). */
  code?: number
}

/** Process exit status. */
export interface ExitStatus {
  code: number
  success: boolean
}

/** Filesystem entry metadata returned by `fs.list()`. */
export interface FsEntry {
  path: string
  /** "file", "directory", "symlink", or "other". */
  kind: string
  size: number
  mode: number
  modified?: number
}

/** Filesystem metadata returned by `fs.stat()`. */
export interface FsMetadata {
  /** "file", "directory", "symlink", or "other". */
  kind: string
  size: number
  mode: number
  readonly: boolean
  modified?: number
  created?: number
}

/** OCI config fields extracted from the database. */
export interface ImageConfigDetail {
  digest: string
  env: Array<string>
  cmd?: Array<string>
  entrypoint?: Array<string>
  workingDir?: string
  user?: string
  labelsJson?: string
  stopSignal?: string
}

/** Full image detail (config + layers + handle metadata). */
export interface ImageDetailJs {
  reference: string
  manifestDigest?: string
  architecture?: string
  os?: string
  layerCount: number
  sizeBytes?: number
  createdAt?: number
  lastUsedAt?: number
  config?: ImageConfigDetail
  layers: Array<ImageLayerDetail>
}

/** Garbage-collect everything reclaimable. Returns the number reclaimed. */
export declare function imageGc(): Promise<number>

/** Garbage-collect orphaned layers. Returns the number reclaimed. */
export declare function imageGcLayers(): Promise<number>

/** Look up a cached image by reference. */
export declare function imageGet(reference: string): Promise<ImageHandle>

/** Lightweight image info as returned by `imageList`. */
export interface ImageInfo {
  reference: string
  manifestDigest?: string
  architecture?: string
  os?: string
  layerCount: number
  sizeBytes?: number
  createdAt?: number
  lastUsedAt?: number
}

/** Full inspect (config + layers). */
export declare function imageInspect(reference: string): Promise<ImageDetailJs>

/** Metadata for a single layer. */
export interface ImageLayerDetail {
  diffId: string
  blobDigest: string
  mediaType?: string
  compressedSizeBytes?: number
  erofsSizeBytes?: number
  position: number
}

/** List all cached images. */
export declare function imageList(): Promise<Array<ImageInfo>>

/**
 * Remove a cached image. Pass `force = true` to delete even when a
 * sandbox references it.
 */
export declare function imageRemove(reference: string, force?: boolean | undefined | null): Promise<void>

/** Download and install msb + libkrunfw to ~/.microsandbox/. */
export declare function install(): Promise<void>

/** Check if msb and libkrunfw are installed and available. */
export declare function isInstalled(): boolean

/** Optional knobs accepted by `text`, `file`, `copyFile`. */
export interface PatchFileOptions {
  mode?: number
  replace?: boolean
}

/** Optional knobs accepted by `mkdir`. */
export interface PatchModeOnly {
  mode?: number
}

/** Optional knobs accepted by `copyDir`, `symlink`. */
export interface PatchReplaceOnly {
  replace?: boolean
}

/** Plain-object form of `RegistryAuth`. `kind: "anonymous" | "basic"`. */
export interface RegistryAuthInput {
  kind: string
  username?: string
  password?: string
}

/** Lightweight handle info for a sandbox from the database. */
export interface SandboxInfo {
  name: string
  /** "running", "stopped", "crashed", or "draining". */
  status: string
  configJson: string
  createdAt?: number
  updatedAt?: number
}

/** Point-in-time resource metrics for a sandbox. */
export interface SandboxMetrics {
  cpuPercent: number
  memoryBytes: number
  memoryLimitBytes: number
  diskReadBytes: number
  diskWriteBytes: number
  netRxBytes: number
  netTxBytes: number
  /** Uptime in milliseconds. */
  uptimeMs: number
  /** Timestamp as milliseconds since Unix epoch. */
  timestampMs: number
}

/** A secret entry produced by `SecretBuilder.build()`. */
export interface SecretEntry {
  /** Environment variable name exposed to the sandbox (holds the placeholder). */
  envVar: string
  /** Secret value (never enters the sandbox). */
  value: string
  /** Placeholder string the sandbox sees instead of the real value. */
  placeholder: string
  /** Exact host names allowed to receive this secret. */
  allowedHosts: Array<string>
  /** Wildcard host patterns (e.g. `*.openai.com`) allowed to receive this secret. */
  allowedHostPatterns: Array<string>
  /** Allow any host. **Dangerous** — secret can be exfiltrated. */
  allowAnyHost: boolean
  /** Require verified TLS identity before substituting (default: true). */
  requireTlsIdentity: boolean
  /** Where the secret may be injected into requests. */
  injection: JsSecretInjection
}

/** Injection sites for a secret value. */
export interface SecretInjection {
  headers: boolean
  basicAuth: boolean
  queryParams: boolean
  body: boolean
}

/** TLS interception configuration produced by `TlsBuilder.build()`. */
export interface TlsConfig {
  enabled: boolean
  bypass: Array<string>
  verifyUpstream: boolean
  interceptedPorts: Array<number>
  blockQuic: boolean
  upstreamCaCertPaths: Array<string>
  interceptCaCertPath?: string
  interceptCaKeyPath?: string
}

/** Volume handle info from the database. */
export interface VolumeInfo {
  name: string
  quotaMib?: number
  usedBytes: number
  labels: Record<string, string>
  createdAt?: number
}
