// @generated by microsandbox-types. Do not edit by hand.

export type EnvVar = {
  /**
   * Environment variable name.
   */
  key: string;
  /**
   * Environment variable value.
   */
  value: string;
};

export type HandoffInit = {
  /**
   * Init binary: absolute path inside the guest rootfs, or the literal `auto`.
   *
   * Always a Linux-style `/`-separated path — never build it with host OS path APIs, whose semantics diverge on Windows (`\` separators, `/sbin/init` treated as relative).
   */
  cmd: string;
  /**
   * Supplemental argv. `argv[0]` is implicitly `cmd`.
   */
  args: Array<string>;
  /**
   * Extra env vars merged on top of the inherited env.
   */
  env: Array<[string, string]>;
};

export type SecurityProfile = "default" | "restricted";

export type SandboxPolicy = {
  /**
   * Whether the sandbox is ephemeral.
   *
   * Ephemeral sandboxes are one-off: the host runtime that owns the
   * process removes the persisted DB row and on-disk state when the VM
   * reaches a terminal status, and other host runtimes opportunistically
   * clean up ephemeral leftovers from runtimes that died before they
   * could self-clean. Defaults to `false` (persistent); named and created
   * sandboxes stay inspectable and restartable after they stop.
   */
  ephemeral: boolean;
  /**
   * Hard cap on total sandbox lifetime in seconds. `None` = run forever.
   */
  max_duration_secs: number | null;
  /**
   * Idle timeout in seconds. `None` = no idle detection.
   */
  idle_timeout_secs: number | null;
};

export type SandboxLogLevel = "error" | "warn" | "info" | "debug" | "trace";

export type MountOptions = {
  /**
   * Whether the mount is read-only.
   *
   * Guest writes fail with the kernel's read-only filesystem behavior. Virtiofs-backed mounts also reject writes on the host-side filesystem server as defense in depth.
   */
  readonly: boolean;
  /**
   * Whether direct execution from the mount is disabled.
   *
   * This prevents `execve` of binaries or scripts located on the mount. Interpreters can still read files from the mount, for example `sh /mnt/script.sh`, because the interpreter itself executes from a different filesystem.
   */
  noexec: boolean;
  /**
   * Whether setuid and setgid privilege elevation from files on the mount is ignored.
   */
  nosuid: boolean;
  /**
   * Whether device files on the mount are ignored.
   */
  nodev: boolean;
  /**
   * Guest uid presented for host files under this mount that carry no
   * per-file stat override.
   *
   * Host-created files (written outside the guest) have no override, so
   * without this they surface with the runtime's fallback owner. When set,
   * such files are presented as this uid instead. Must be set together with
   * [`override_gid`](Self::override_gid). `None` keeps the fallback.
   */
  override_uid?: number | null;
  /**
   * Guest gid presented for host files under this mount that carry no
   * per-file stat override. See [`override_uid`](Self::override_uid); the two
   * must be set together.
   */
  override_gid?: number | null;
};

export type OwnedVolumeStorage = {
  "kind": "directory";
  /**
   * Guest-write budget in MiB; `None` uses the directory-mount default.
   */
  quota_mib: number | null;
} | {
  "kind": "disk";
  /**
   * Required, positive capacity in MiB.
   */
  capacity_mib: number;
};

export type StatVirtualization = "strict" | "relaxed" | "off";

export type HostPermissions = "private" | "mirror";

export type SecretSubstitution = {
  /**
   * Substitute in HTTP headers (default: true).
   */
  headers: boolean;
  /**
   * Restrict header substitution to these header field names.
   *
   * Requires [`headers`](Self::headers) to be true; a non-empty list with
   * header substitution disabled is rejected as contradictory. An empty list
   * (the default) allows every header field. When non-empty, the
   * placeholder is substituted only in the named fields (matched ASCII
   * case-insensitively); a placeholder found in any other header field is
   * treated as a disabled location: on a verified allowed destination it is
   * forwarded unchanged, while other destinations follow the violation
   * policy.
   *
   * Prefer an allowlist containing only the intended credential header
   * (typically `Authorization`). Substituting in every header lets an
   * untrusted guest place the placeholder in a header the upstream host
   * reflects back in its response (or otherwise exposes), which would let
   * the guest read the real secret out of that response.
   *
   * Names must be valid HTTP field names (RFC 9110 `token`).
   */
  header_fields?: Array<string>;
  /**
   * Substitute in URL query parameters (default: false).
   */
  query: boolean;
  /**
   * Substitute in request body (default: false).
   *
   * Fixed-length HTTP/1 bodies up to 16 MiB update `Content-Length`;
   * larger fixed-length bodies are blocked. Chunked HTTP/1 bodies are
   * decoded and re-encoded with fresh chunk sizes. Encoded bodies pass
   * through unchanged. HTTP/2 DATA-frame body substitution is not
   * supported; matching body placeholders are blocked.
   */
  body: boolean;
};

export type NetworkPolicy = {
  /**
   * Default action for egress traffic matching no rule. Default: `Deny`.
   */
  default_egress: Action;
  /**
   * Default action for ingress traffic matching no rule. Default: `Deny`.
   */
  default_ingress: Action;
  /**
   * Ordered rules, evaluated first-match-wins per direction.
   */
  rules: Array<Rule>;
};

export type Rule = {
  /**
   * Direction this rule applies to.
   */
  direction: Direction;
  /**
   * Destination filter (direction-dependent interpretation).
   */
  destination: Destination;
  /**
   * Protocol set; empty matches any protocol.
   */
  protocols: Array<Protocol>;
  /**
   * Guest-side port-range set; empty matches any port.
   */
  ports: Array<PortRange>;
  /**
   * Action to take on a match.
   */
  action: Action;
};

export type Action = "allow" | "deny";

export type Direction = "egress" | "ingress" | "any";

export type Protocol = "tcp" | "udp" | "icmpv4" | "icmpv6";

export type Destination = "any" | { "cidr": string } | { "domain": string } | {
  "domain_suffix": string;
} | { "group": DestinationGroup };

export type DestinationGroup =
  | "public"
  | "loopback"
  | "private"
  | "link_local"
  | "metadata"
  | "multicast"
  | "host";

export type PortRange = {
  /**
   * Start port (inclusive).
   */
  start: number;
  /**
   * End port (inclusive).
   */
  end: number;
};

export type ModificationPolicy = "no_restart" | "next_start" | "restart";

export type SandboxModificationPlan = {
  /**
   * Sandbox being modified.
   */
  sandbox: string;
  /**
   * Sandbox status used for classification.
   */
  status: string;
  /**
   * Whether the changes were applied.
   */
  applied: boolean;
  /**
   * Modification policy used to produce the plan.
   */
  policy: ModificationPolicy;
  /**
   * Planned changes.
   */
  changes: Array<PlannedChange>;
  /**
   * Conflicts that must be resolved before the patch can apply.
   */
  conflicts: Array<ModificationConflict>;
  /**
   * Non-fatal warnings about the patch or current runtime capabilities.
   */
  warnings: Array<ModificationWarning>;
  /**
   * Live resource resize outcomes, populated by apply when a live change ran.
   */
  resize_status?: Array<ResourceResizeStatus>;
};

export type PlannedChange =
  | { "kind": "config" } & ConfigPlannedChange
  | { "kind": "secret" } & SecretPlannedChange;

export type ConfigPlannedChange = {
  /**
   * Config field being changed.
   */
  field: string;
  /**
   * Natural change type for table rendering.
   */
  change: ChangeKind;
  /**
   * Previous safe visible state.
   */
  before: string | null;
  /**
   * New safe visible state.
   */
  after: string | null;
  /**
   * When or whether the change can take effect.
   */
  disposition: ModificationDisposition;
  /**
   * Human-readable reason for this classification, when useful.
   */
  reason: string | null;
};

export type SecretPlannedChange = {
  /**
   * Table field name. This is always `secret`.
   */
  field: string;
  /**
   * Stable secret identity, usually the environment variable name.
   */
  name: string;
  /**
   * Natural change type for table rendering.
   */
  change: SecretChangeKind;
  /**
   * Previous guest-visible reference or placeholder.
   */
  before_ref: string | null;
  /**
   * New guest-visible reference or placeholder.
   */
  after_ref: string | null;
  /**
   * When or whether the change can take effect.
   */
  disposition: ModificationDisposition;
  /**
   * Allowed hosts after the requested change.
   */
  allow_hosts?: Array<string>;
  /**
   * Human-readable reason for this classification, when useful.
   */
  reason: string | null;
};

export type ChangeKind = "added" | "updated" | "removed";

export type SecretChangeKind =
  | "added"
  | "rotated"
  | "removed"
  | "renamed"
  | "hosts updated"
  | "placeholder updated";

export type ModificationDisposition =
  | "live"
  | "next start"
  | "requires restart"
  | "unsupported"
  | "unconfirmed"
  | string & {};

export type ModificationConflict = {
  /**
   * Field with the conflict.
   */
  field: string;
  /**
   * Human-readable conflict description.
   */
  message: string;
};

export type ModificationWarning = {
  /**
   * Field associated with the warning.
   */
  field: string;
  /**
   * Human-readable warning description.
   */
  message: string;
};

export type ResourceResizeStatus = {
  /**
   * Resource being resized.
   */
  resource: ResourceKind;
  /**
   * Requested value.
   */
  requested: string;
  /**
   * Actual value observed in the guest/runtime.
   */
  actual: string;
  /**
   * Host/VMM-enforced value.
   */
  enforced: string;
  /**
   * Convergence state.
   */
  state: ResourceConvergenceState;
};

export type ResourceKind = "cpus" | "memory";

export type ResourceConvergenceState =
  | "accepted"
  | "converging"
  | "applied"
  | "guest-refused"
  | "failed";
