// @generated by microsandbox-types. Do not edit by hand.

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type DiskImageFormat = "Qcow2" | "Raw" | "Vmdk";

export type OciRootfsSource = {
/**
 * OCI image reference (e.g. `python`).
 */
reference: string,
/**
 * Writable overlay upper size in MiB.
 */
upper_size_mib?: number | null, };

export type RootfsSource = { "Bind": string } | { "Oci": OciRootfsSource } | { "DiskImage": {
/**
 * Path to the disk image file on the host.
 */
path: string,
/**
 * Disk image format.
 */
format: DiskImageFormat,
/**
 * Inner filesystem type (optional; auto-detected if absent).
 */
fstype: string | null, } };

export type PullPolicy = "IfMissing" | "Always" | "Never";

export type StatVirtualization = "strict" | "relaxed" | "off";

export type HostPermissions = "private" | "mirror";

export type SecurityProfile = "default" | "restricted";

export type MountOptions = {
/**
 * Whether the mount is read-only.
 *
 * Guest writes fail with the kernel's read-only filesystem behavior. Virtiofs-backed mounts also reject writes on the host-side filesystem server as defense in depth.
 */
readonly: boolean,
/**
 * Whether direct execution from the mount is disabled.
 *
 * This prevents `execve` of binaries or scripts located on the mount. Interpreters can still read files from the mount, for example `sh /mnt/script.sh`, because the interpreter itself executes from a different filesystem.
 */
noexec: boolean,
/**
 * Whether setuid and setgid privilege elevation from files on the mount is ignored.
 */
nosuid: boolean,
/**
 * Whether device files on the mount are ignored.
 */
nodev: boolean, };

export type VolumeKind = "Directory" | "Disk";

export type VolumeSpec = {
/**
 * Volume name.
 */
name: string,
/**
 * Storage kind.
 */
kind: VolumeKind,
/**
 * Size quota in MiB. `None` means unlimited.
 */
quota_mib: number | null,
/**
 * Disk capacity in MiB. Required for disk volumes.
 */
capacity_mib: number | null,
/**
 * Labels for organization.
 */
labels: Array<[string, string]>, };

export type NamedVolumeMode = "Existing" | "Create" | "EnsureExists";

export type NamedVolumeCreate = {
/**
 * Creation behavior for this named volume mount.
 */
mode: NamedVolumeMode,
/**
 * Volume name to create or ensure exists.
 */
name: string,
/**
 * Storage kind to create or ensure exists.
 */
kind: VolumeKind,
/**
 * Directory quota in MiB, if configured.
 */
quota_mib: number | null,
/**
 * Disk capacity in MiB, if configured.
 */
capacity_mib: number | null,
/**
 * Labels to attach to newly-created volumes.
 */
labels: Array<[string, string]>, };

export type VolumeMount = { "type": "Bind",
/**
 * Host path to bind mount.
 */
host: string,
/**
 * Guest mount path.
 */
guest: string,
/**
 * Guest mount behavior.
 */
options: MountOptions,
/**
 * Guest-visible stat virtualization policy.
 */
stat_virtualization: StatVirtualization,
/**
 * Host permission propagation policy.
 */
host_permissions: HostPermissions,
/**
 * Guest-write byte budget in MiB.
 *
 * Bounds how much the guest may add beyond the directory's existing
 * contents. `None` applies the protective default at spawn time; set a
 * value to override it.
 */
quota_mib: number | null, } | { "type": "Named",
/**
 * Volume name.
 */
name: string,
/**
 * Guest mount path.
 */
guest: string,
/**
 * Creation metadata for sandbox-time named volume provisioning.
 *
 * This is transient and intentionally skipped when sandbox configs are persisted; restarting a sandbox mounts the already-created volume.
 */
create: NamedVolumeCreate | null,
/**
 * Guest mount behavior.
 */
options: MountOptions,
/**
 * Guest-visible stat virtualization policy.
 */
stat_virtualization: StatVirtualization,
/**
 * Host permission propagation policy.
 */
host_permissions: HostPermissions, } | { "type": "Tmpfs",
/**
 * Guest mount path.
 */
guest: string,
/**
 * Size limit in MiB.
 */
size_mib: number | null,
/**
 * Guest mount behavior.
 */
options: MountOptions, } | { "type": "DiskImage",
/**
 * Host path to the disk image file.
 */
host: string,
/**
 * Guest mount path.
 */
guest: string,
/**
 * Disk image format.
 */
format: DiskImageFormat,
/**
 * Inner filesystem type. When `None`, agentd probes `/proc/filesystems`.
 */
fstype: string | null,
/**
 * Guest mount behavior.
 */
options: MountOptions, };

export type Patch = { "Text": {
/**
 * Absolute guest path, such as `/etc/app.conf`.
 */
path: string,
/**
 * Text content to write.
 */
content: string,
/**
 * File permissions, such as `0o644`. `None` uses the default.
 */
mode: number | null,
/**
 * Allow replacing a file that already exists in the rootfs.
 */
replace: boolean, } } | { "File": {
/**
 * Absolute guest path.
 */
path: string,
/**
 * Raw byte content to write.
 */
content: Array<number>,
/**
 * File permissions, such as `0o644`. `None` uses the default.
 */
mode: number | null,
/**
 * Allow replacing a file that already exists in the rootfs.
 */
replace: boolean, } } | { "CopyFile": {
/**
 * Host path to copy from.
 */
src: string,
/**
 * Absolute guest destination path.
 */
dst: string,
/**
 * File permissions. `None` preserves source permissions.
 */
mode: number | null,
/**
 * Allow replacing a file that already exists in the rootfs.
 */
replace: boolean, } } | { "CopyDir": {
/**
 * Host directory to copy from.
 */
src: string,
/**
 * Absolute guest destination path.
 */
dst: string,
/**
 * Allow replacing files that already exist in the rootfs.
 */
replace: boolean, } } | { "Symlink": {
/**
 * Symlink target path.
 */
target: string,
/**
 * Absolute guest path where the symlink is created.
 */
link: string,
/**
 * Allow replacing a path that already exists in the rootfs.
 */
replace: boolean, } } | { "Mkdir": {
/**
 * Absolute guest path.
 */
path: string,
/**
 * Directory permissions, such as `0o755`. `None` uses the default.
 */
mode: number | null, } } | { "Remove": {
/**
 * Absolute guest path to remove.
 */
path: string, } } | { "Append": {
/**
 * Absolute guest path of the file to append to.
 */
path: string,
/**
 * Content to append.
 */
content: string, } };

export type NetworkSpec = {
/**
 * Whether networking is enabled for this sandbox.
 */
enabled: boolean,
/**
 * Guest interface overrides for the local network engine.
 */
interface: InterfaceOverrides | null,
/**
 * Host-to-guest port mappings.
 */
ports: Array<PublishedPortSpec>,
/**
 * Egress and ingress policy subdocument.
 */
policy: NetworkPolicy | null,
/**
 * DNS interception and filtering subdocument.
 */
dns: DnsConfig | null,
/**
 * TLS interception subdocument.
 */
tls: TlsConfig | null,
/**
 * Secret injection subdocument.
 */
secrets: SecretsConfig | null,
/**
 * Max concurrent guest connections.
 */
max_connections: number | null,
/**
 * Whether to copy trusted host CAs into the guest at boot.
 */
trust_host_cas: boolean, };

export type PublishedPortSpec = {
/**
 * Host-side port to bind.
 */
host_port: number,
/**
 * Guest-side port to forward to.
 */
guest_port: number,
/**
 * Transport protocol.
 */
protocol: PortProtocol,
/**
 * Host address to bind. Defaults to loopback.
 */
host_bind: string, };

export type PortProtocol = "tcp" | "udp";

export type HandoffInit = {
/**
 * Init binary: absolute path inside the guest rootfs, or the literal `auto`.
 */
cmd: string,
/**
 * Supplemental argv. `argv[0]` is implicitly `cmd`.
 */
args: Array<string>,
/**
 * Extra env vars merged on top of the inherited env.
 */
env: Array<[string, string]>, };

export type SandboxPolicy = {
/**
 * Whether the sandbox is ephemeral.
 *
 * Ephemeral sandboxes are one-off: the host runtime that owns the
 * process removes the persisted DB row and on-disk state when the VM
 * reaches a terminal status, and other host runtimes opportunistically
 * clean up ephemeral leftovers from runtimes that died before they
 * could self-clean. Defaults to `false` (persistent); named and created
 * sandboxes stay inspectable and restartable after they stop.
 */
ephemeral: boolean,
/**
 * Hard cap on total sandbox lifetime in seconds. `None` = run forever.
 */
max_duration_secs: number | null,
/**
 * Idle timeout in seconds. `None` = no idle detection.
 */
idle_timeout_secs: number | null, };

export type SnapshotDestination = { "Name": string } | { "Path": string };

export type SnapshotSpec = {
/**
 * Name of the source sandbox. Must be stopped.
 */
source_sandbox: string,
/**
 * Where to write the artifact.
 */
destination: SnapshotDestination,
/**
 * User-supplied labels.
 */
labels: Array<[string, string]>,
/**
 * Overwrite an existing artifact at the destination.
 */
force: boolean,
/**
 * Compute and record upper-layer content integrity at creation time.
 */
record_integrity: boolean, };

export type SandboxSpec = {
/**
 * Unique sandbox name.
 */
name: string,
/**
 * Root filesystem source.
 */
image: RootfsSource,
/**
 * CPU and memory resources.
 */
resources: SandboxResources,
/**
 * Guest runtime options.
 */
runtime: SandboxRuntimeOptions,
/**
 * Environment variables visible to commands in the sandbox.
 */
env: Array<EnvVar>,
/**
 * User-defined labels attached to the sandbox.
 */
labels: { [key in string]: string },
/**
 * Sandbox-wide resource limits inherited by guest processes.
 */
rlimits: Array<Rlimit>,
/**
 * Volume mounts.
 */
mounts: Array<VolumeMount>,
/**
 * Rootfs patches applied before VM start.
 */
patches: Array<Patch>,
/**
 * Network specification.
 */
network: NetworkSpec,
/**
 * Hand off PID 1 to a guest init binary after agentd setup.
 */
init: HandoffInit | null,
/**
 * Pull policy for OCI images.
 */
pull_policy: PullPolicy,
/**
 * In-guest security profile.
 */
security_profile: SecurityProfile,
/**
 * Sandbox lifecycle policy.
 */
lifecycle: SandboxPolicy, };

export type SandboxResources = {
/**
 * Number of virtual CPUs currently presented to the guest at boot.
 */
cpus: number,
/**
 * Guest memory currently presented to the guest at boot, in MiB.
 */
memory_mib: number,
/**
 * Maximum virtual CPUs the sandbox may expose after boot-time hotplug support lands.
 */
max_cpus: number,
/**
 * Maximum guest memory the sandbox may expose after boot-time hotplug support lands, in MiB.
 */
max_memory_mib: number, };

export type SandboxRuntimeOptions = {
/**
 * Working directory inside the guest.
 */
workdir: string | null,
/**
 * Default shell for scripts and interactive sessions.
 */
shell: string | null,
/**
 * Named scripts available inside the guest.
 */
scripts: { [key in string]: string },
/**
 * Image entrypoint override.
 */
entrypoint: Array<string> | null,
/**
 * Image command override.
 */
cmd: Array<string> | null,
/**
 * Guest hostname override.
 */
hostname: string | null,
/**
 * Guest user identity override.
 */
user: string | null,
/**
 * Runtime log verbosity.
 */
log_level: SandboxLogLevel | null,
/**
 * Metrics sampling interval in milliseconds. `None` disables sampling.
 */
metrics_sample_interval_ms: number | null,
/**
 * Force-disable metrics sampling regardless of `metrics_sample_interval_ms`.
 */
disable_metrics_sample: boolean, };

export type EnvVar = {
/**
 * Environment variable name.
 */
key: string,
/**
 * Environment variable value.
 */
value: string, };

export type SandboxLogLevel = "error" | "warn" | "info" | "debug" | "trace";

export type RlimitResource = "Cpu" | "Fsize" | "Data" | "Stack" | "Core" | "Rss" | "Nproc" | "Nofile" | "Memlock" | "As" | "Locks" | "Sigpending" | "Msgqueue" | "Nice" | "Rtprio" | "Rttime";

export type Rlimit = {
/**
 * Resource type.
 */
resource: RlimitResource,
/**
 * Soft limit (can be raised up to hard limit by the process).
 */
soft: number,
/**
 * Hard limit (ceiling, requires privileges to raise).
 */
hard: number, };

export type LogSource = "stdout" | "stderr" | "output" | "system";

export type SandboxModificationPatch = {
/**
 * Desired effective vCPU count.
 */
cpus: number | null,
/**
 * Desired boot-time maximum possible vCPU count.
 */
max_cpus: number | null,
/**
 * Desired effective guest memory in MiB.
 */
memory_mib: number | null,
/**
 * Desired boot-time maximum hotpluggable memory in MiB.
 */
max_memory_mib: number | null,
/**
 * Desired OCI writable overlay upper size in MiB. Grow-only: the upper is a real ext4 image, so shrinking risks data loss and is rejected in v1.
 */
oci_upper_size_mib: number | null,
/**
 * Environment variables to set for future execs.
 */
env?: Array<EnvVar>,
/**
 * Environment variable keys to remove.
 */
env_remove?: Array<string>,
/**
 * Labels to set.
 */
labels?: Array<[string, string]>,
/**
 * Label keys to remove.
 */
labels_remove?: Array<string>,
/**
 * Desired working directory for future execs.
 */
workdir: string | null,
/**
 * Desired secret specs, keyed by secret name. The planner diffs each
 * spec against the existing config to infer what changes.
 */
secrets?: Array<SecretModificationPatch>,
/**
 * Secret names to remove. Removal is explicit: absence of a name from
 * `secrets` never means removal.
 */
secrets_remove?: Array<string>, };

export type ModificationPolicy = "no_restart" | "next_start" | "restart";

export type SecretModificationPatch = {
/**
 * Stable secret identity, usually the environment variable name.
 */
name: string,
/**
 * Host-side source reference to resolve the value from. Mutually
 * exclusive with `value`.
 */
source: SecretSource | null,
/**
 * Raw secret value supplied by the caller, for embedders that hold only
 * a value (e.g. from their own vault). Mutually exclusive with `source`.
 * A value-based apply persists the value into the durable config until a
 * later source-based rotate migrates the entry to a reference.
 */
value?: string,
/**
 * Guest-visible placeholder/reference, if explicitly requested.
 */
placeholder: string | null,
/**
 * Desired allowed host patterns. Empty means "leave unchanged" for an
 * existing secret; a new secret needs at least one.
 */
allowed_hosts?: Array<string>, };

export type SecretSource = { "kind": "env",
/**
 * Host environment variable name.
 */
var: string, } | { "kind": "store",
/**
 * Store-specific secret reference.
 */
reference: string, };

export type SandboxModificationPlan = {
/**
 * Sandbox being modified.
 */
sandbox: string,
/**
 * Sandbox status used for classification.
 */
status: string,
/**
 * Whether the changes were applied.
 */
applied: boolean,
/**
 * Modification policy used to produce the plan.
 */
policy: ModificationPolicy,
/**
 * Planned changes.
 */
changes: Array<PlannedChange>,
/**
 * Conflicts that must be resolved before the patch can apply.
 */
conflicts: Array<ModificationConflict>,
/**
 * Non-fatal warnings about the patch or current runtime capabilities.
 */
warnings: Array<ModificationWarning>,
/**
 * Live resource resize outcomes, populated by apply when a live change ran.
 */
resize_status?: Array<ResourceResizeStatus>, };

export type PlannedChange = { "kind": "config" } & ConfigPlannedChange | { "kind": "secret" } & SecretPlannedChange;

export type ConfigPlannedChange = {
/**
 * Config field being changed.
 */
field: string,
/**
 * Natural change type for table rendering.
 */
change: ChangeKind,
/**
 * Previous safe visible state.
 */
before: string | null,
/**
 * New safe visible state.
 */
after: string | null,
/**
 * When or whether the change can take effect.
 */
disposition: ModificationDisposition,
/**
 * Human-readable reason for this classification, when useful.
 */
reason: string | null, };

export type SecretPlannedChange = {
/**
 * Table field name. This is always `secret`.
 */
field: string,
/**
 * Stable secret identity, usually the environment variable name.
 */
name: string,
/**
 * Natural change type for table rendering.
 */
change: SecretChangeKind,
/**
 * Previous guest-visible reference or placeholder.
 */
before_ref: string | null,
/**
 * New guest-visible reference or placeholder.
 */
after_ref: string | null,
/**
 * When or whether the change can take effect.
 */
disposition: ModificationDisposition,
/**
 * Allowed hosts after the requested change.
 */
allow_hosts?: Array<string>,
/**
 * Human-readable reason for this classification, when useful.
 */
reason: string | null, };

export type ChangeKind = "added" | "updated" | "removed";

export type SecretChangeKind = "added" | "rotated" | "removed" | "renamed" | "hosts updated" | "placeholder updated";

export type ModificationDisposition = "live" | "next start" | "requires restart" | "unsupported";

export type ModificationConflict = {
/**
 * Field with the conflict.
 */
field: string,
/**
 * Human-readable conflict description.
 */
message: string, };

export type ModificationWarning = {
/**
 * Field associated with the warning.
 */
field: string,
/**
 * Human-readable warning description.
 */
message: string, };

export type ResourceKind = "cpus" | "memory";

export type ResourceConvergenceState = "accepted" | "converging" | "applied" | "guest-refused" | "failed";

export type ResourceResizeStatus = {
/**
 * Resource being resized.
 */
resource: ResourceKind,
/**
 * Requested value.
 */
requested: string,
/**
 * Actual value observed in the guest/runtime.
 */
actual: string,
/**
 * Host/VMM-enforced value.
 */
enforced: string,
/**
 * Convergence state.
 */
state: ResourceConvergenceState, };

export type SecretsConfig = {
/**
 * List of secrets to inject.
 */
secrets: Array<SecretEntry>,
/**
 * Default action when a placeholder leaks to a disallowed host.
 */
on_violation: ViolationAction, };

export type SecretEntry = {
/**
 * Environment variable name exposed to the sandbox (holds the placeholder).
 *
 * Must be non-empty and must not contain `=` or NUL. microsandbox does
 * not require shell-identifier syntax because Linux environment entries
 * only require a `NAME=value` shape.
 */
env_var: string,
/**
 * The actual secret value (never enters the sandbox).
 *
 * Empty when the entry carries a [`source`](Self::source) reference
 * instead: reference-model entries resolve the value host-side at spawn
 * time so the durable sandbox config never stores raw secret material.
 *
 * Wrapped in [`Zeroizing`] so the owned plaintext copy is wiped when the
 * entry drops.
 */
value: string,
/**
 * Host-side source reference resolved into [`value`](Self::value) at
 * spawn time. `None` means `value` already carries the material (the
 * inline model used by value-based secrets).
 */
source?: SecretSource | null,
/**
 * Placeholder string the sandbox sees instead of the real value.
 *
 * Must be non-empty, no longer than [`MAX_SECRET_PLACEHOLDER_BYTES`], and
 * must not contain NUL, CR, or LF.
 */
placeholder: string,
/**
 * Hosts allowed to receive this secret.
 */
allowed_hosts: Array<HostPattern>,
/**
 * Where the secret can be injected.
 */
injection: SecretInjection,
/**
 * Action on a violation for this secret (overrides the config default).
 */
on_violation?: ViolationAction | null,
/**
 * Require verified TLS identity before substituting (default: true).
 *
 * When true, the secret is only substituted if the connection uses TLS
 * interception (not bypass) and the SNI matches an allowed host.
 */
require_tls_identity: boolean, };

export type SecretInjection = {
/**
 * Substitute in HTTP headers (default: true).
 */
headers: boolean,
/**
 * Substitute in HTTP Basic Auth (default: true).
 */
basic_auth: boolean,
/**
 * Substitute in URL query parameters (default: false).
 */
query_params: boolean,
/**
 * Substitute in request body (default: false).
 *
 * Fixed-length HTTP/1 bodies up to 16 MiB update `Content-Length`;
 * larger fixed-length bodies are blocked. Chunked HTTP/1 bodies are
 * decoded and re-encoded with fresh chunk sizes. Encoded bodies pass
 * through unchanged. HTTP/2 DATA-frame body substitution is not
 * supported; matching body placeholders are blocked.
 */
body: boolean, };

export type HostPattern = { "exact": string } | { "wildcard": string } | "any";

export type ViolationAction = "block" | "block-and-log" | "block-and-terminate" | { "passthrough": Array<HostPattern> };

export type TlsConfig = {
/**
 * Whether TLS interception is enabled.
 */
enabled: boolean,
/**
 * TCP ports subject to TLS interception (default: `[443]`).
 */
intercepted_ports: Array<number>,
/**
 * Domains to bypass (no MITM). Supports exact match and `*.suffix` wildcards.
 */
bypass: Array<string>,
/**
 * Whether to verify the upstream server's TLS certificate.
 */
verify_upstream: boolean,
/**
 * Drop UDP to intercepted ports when TLS interception is active, forcing
 * QUIC traffic to fall back to TCP/TLS.
 */
block_quic_on_intercept: boolean,
/**
 * CA certificate PEM files to trust for upstream server verification.
 */
upstream_ca_cert: Array<string>,
/**
 * Host-scoped CA certificate PEM files to trust for upstream server verification.
 */
scoped_upstream_ca_cert: Array<ScopedUpstreamCaCert>,
/**
 * Host-scoped upstream verification overrides.
 */
scoped_verify_upstream: Array<ScopedVerifyUpstream>,
/**
 * Interception CA configuration. The TLS proxy uses this CA to sign
 * per-domain certs it presents to the guest during interception.
 */
intercept_ca: InterceptCaConfig,
/**
 * Per-domain certificate cache configuration.
 */
cache: CertCacheConfig, };

export type InterceptCaConfig = {
/**
 * Path to an existing CA certificate PEM file. If `None`, a CA is
 * auto-generated and persisted.
 */
cert_path: string | null,
/**
 * Path to an existing CA private key PEM file. If `None`, a key is
 * auto-generated and persisted.
 */
key_path: string | null, };

export type CertCacheConfig = {
/**
 * Maximum number of cached certificates. Default: 1000.
 */
capacity: number,
/**
 * Certificate validity duration in hours. Default: 24.
 */
validity_hours: number, };

export type ScopedUpstreamCaCert = {
/**
 * Host pattern this CA applies to. Supports exact hosts and `*.suffix` wildcards.
 */
pattern: string,
/**
 * Path to the CA certificate PEM file.
 */
path: string, };

export type ScopedVerifyUpstream = {
/**
 * Host pattern this override applies to. Supports exact hosts and `*.suffix` wildcards.
 */
pattern: string,
/**
 * Whether to verify matching upstream server certificates.
 */
verify: boolean, };

export type Action = "allow" | "deny";

export type Direction = "egress" | "ingress" | "any";

export type Protocol = "tcp" | "udp" | "icmpv4" | "icmpv6";

export type DestinationGroup = "public" | "loopback" | "private" | "link_local" | "metadata" | "multicast" | "host";

export type Destination = "any" | { "cidr": string } | { "domain": string } | { "domain_suffix": string } | { "group": DestinationGroup };

export type PortRange = {
/**
 * Start port (inclusive).
 */
start: number,
/**
 * End port (inclusive).
 */
end: number, };

export type Rule = {
/**
 * Direction this rule applies to.
 */
direction: Direction,
/**
 * Destination filter (direction-dependent interpretation).
 */
destination: Destination,
/**
 * Protocol set; empty matches any protocol.
 */
protocols: Array<Protocol>,
/**
 * Guest-side port-range set; empty matches any port.
 */
ports: Array<PortRange>,
/**
 * Action to take on a match.
 */
action: Action, };

export type NetworkPolicy = {
/**
 * Default action for egress traffic matching no rule. Default: `Deny`.
 */
default_egress: Action,
/**
 * Default action for ingress traffic matching no rule. Default: `Deny`.
 */
default_ingress: Action,
/**
 * Ordered rules, evaluated first-match-wins per direction.
 */
rules: Array<Rule>, };

export type DnsConfig = {
/**
 * Whether DNS-rebinding protection is enabled. Default: true.
 */
rebind_protection: boolean,
/**
 * Upstream nameservers as `IP`, `IP:PORT`, `HOST`, or `HOST:PORT`
 * strings. Empty falls back to the host's `/etc/resolv.conf`.
 */
nameservers: Array<string>,
/**
 * Per-query timeout in milliseconds. Default: 5000.
 */
query_timeout_ms: number, };

export type InterfaceOverrides = {
/**
 * Guest MAC address as six octets. Default: derived from slot.
 */
mac: [number, number, number, number, number, number] | null,
/**
 * Interface MTU. Default: 1500.
 */
mtu: number | null,
/**
 * Guest IPv4 address (e.g. `172.16.0.2`). Default: derived from slot.
 */
ipv4_address: string | null,
/**
 * Guest IPv4 pool CIDR (e.g. `"172.16.0.0/12"`). Default: derived from slot.
 */
ipv4_pool: string | null,
/**
 * Guest IPv6 address. Default: derived from slot.
 */
ipv6_address: string | null,
/**
 * Guest IPv6 pool CIDR. Default: derived from slot.
 */
ipv6_pool: string | null, };

export type CloudSandboxSpec = {
/**
 * Unique sandbox name.
 */
name: string,
/**
 * Root filesystem source.
 */
image: CloudRootfsSource,
/**
 * CPU, memory, and user-facing disk resources.
 */
resources: CloudSandboxResources,
/**
 * Guest runtime options (curated; platform-controlled fields omitted).
 */
runtime: CloudSandboxRuntimeOptions,
/**
 * Environment variables visible to commands in the sandbox.
 */
env: Array<EnvVar>,
/**
 * User-defined labels attached to the sandbox.
 */
labels: { [key in string]: string },
/**
 * Sandbox-wide resource limits inherited by guest processes.
 */
rlimits: Array<Rlimit>,
/**
 * Volume mounts.
 */
mounts: Array<CloudVolumeMount>,
/**
 * Rootfs patches applied before VM start.
 */
patches: Array<Patch>,
/**
 * Network specification (curated; platform-controlled fields omitted).
 */
network: CloudNetworkSpec,
/**
 * Hand off PID 1 to a guest init binary after agentd setup.
 */
init: HandoffInit | null,
/**
 * Pull policy for OCI images.
 */
pull_policy: PullPolicy,
/**
 * In-guest security profile.
 */
security_profile: SecurityProfile,
/**
 * Sandbox lifecycle policy.
 */
lifecycle: SandboxPolicy, };

export type CloudRootfsSource = { "type": "bind",
/**
 * Host path to bind mount.
 */
path: string, } | { "type": "oci",
/**
 * OCI image reference (e.g. `python`).
 */
reference: string, } | { "type": "disk_image",
/**
 * Path to the disk image file on the host.
 */
path: string,
/**
 * Disk image format.
 */
format: DiskImageFormat,
/**
 * Inner filesystem type (optional; auto-detected if absent).
 */
fstype: string | null, };

export type CloudVolumeMount = { "type": "bind",
/**
 * Host directory to bind into the guest.
 */
host: string,
/**
 * Guest path to mount at.
 */
guest: string,
/**
 * Mount options (read-only, no-exec, …).
 */
options: MountOptions,
/**
 * How guest `stat()` results are virtualized.
 */
stat_virtualization: StatVirtualization,
/**
 * Host permission policy applied to the mount.
 */
host_permissions: HostPermissions,
/**
 * Optional guest-write quota in MiB.
 */
quota_mib: number | null, } | { "type": "named",
/**
 * Named volume to mount.
 */
name: string,
/**
 * Guest path to mount at.
 */
guest: string,
/**
 * Mount options (read-only, no-exec, …).
 */
options: MountOptions,
/**
 * How guest `stat()` results are virtualized.
 */
stat_virtualization: StatVirtualization,
/**
 * Host permission policy applied to the mount.
 */
host_permissions: HostPermissions, } | { "type": "tmpfs",
/**
 * Guest path to mount at.
 */
guest: string,
/**
 * Optional size cap in MiB.
 */
size_mib: number | null,
/**
 * Mount options (read-only, no-exec, …).
 */
options: MountOptions, } | { "type": "disk_image",
/**
 * Host path to the disk image file.
 */
host: string,
/**
 * Guest path to mount at.
 */
guest: string,
/**
 * Disk image format.
 */
format: DiskImageFormat,
/**
 * Inner filesystem type (auto-detected if absent).
 */
fstype: string | null,
/**
 * Mount options (read-only, no-exec, …).
 */
options: MountOptions, };

export type CloudSandboxResources = {
/**
 * Number of virtual CPUs.
 */
vcpus: number,
/**
 * Guest memory in MiB.
 */
memory_mib: number,
/**
 * Writable disk size in MiB. Applies only to OCI root filesystems.
 */
disk_size_mib?: number | null, };

export type CloudSandboxRuntimeOptions = {
/**
 * Working directory for guest commands.
 */
workdir: string | null,
/**
 * Default shell.
 */
shell: string | null,
/**
 * Named in-guest scripts.
 */
scripts: { [key in string]: string },
/**
 * Entrypoint override.
 */
entrypoint: Array<string> | null,
/**
 * Command override.
 */
cmd: Array<string> | null,
/**
 * Guest user.
 */
user: string | null,
/**
 * Runtime log level.
 */
log_level: SandboxLogLevel | null, };

export type CloudNetworkSpec = {
/**
 * Whether networking is enabled for this sandbox.
 */
enabled: boolean,
/**
 * Egress/ingress policy. The cloud floors it (hard-denies the internal
 * network) before boot; public egress stays the caller's to govern.
 */
policy: NetworkPolicy | null,
/**
 * Secret-injection config.
 */
secrets: CloudSecretsConfig | null,
/**
 * Max concurrent guest connections (the cloud clamps it to a ceiling).
 */
max_connections: number | null, };

export type CloudSecretsConfig = {
/**
 * Secrets to inject.
 */
entries: Array<CloudSecretEntry>,
/**
 * Default action when a placeholder leaks to a disallowed host.
 */
on_violation: CloudViolationAction, };

export type CloudSecretEntry = {
/**
 * Environment variable name exposed to the sandbox.
 */
env_var: string,
/**
 * The secret value (empty when `source` carries a reference instead).
 */
value: string,
/**
 * Host-side source resolved into `value` at spawn time.
 */
source?: CloudSecretSource | null,
/**
 * Placeholder the sandbox sees instead of the real value.
 */
placeholder: string,
/**
 * Hosts allowed to receive this secret.
 */
allowed_hosts: Array<CloudHostPattern>,
/**
 * Where the secret may be injected.
 */
injection: SecretInjection,
/**
 * Per-secret violation action overriding the config default.
 */
on_violation?: CloudViolationAction | null,
/**
 * Require verified TLS identity before substituting (default: true).
 */
require_tls_identity: boolean, };

export type CloudSecretSource = { "type": "env",
/**
 * Host environment variable name.
 */
var: string, } | { "type": "store",
/**
 * Store-specific secret reference.
 */
reference: string, };

export type CloudHostPattern = { "type": "exact",
/**
 * Hostname to match exactly.
 */
value: string, } | { "type": "wildcard",
/**
 * Wildcard pattern.
 */
value: string, } | { "type": "any" };

export type CloudViolationAction = { "type": "block" } | { "type": "block_and_log" } | { "type": "block_and_terminate" } | { "type": "passthrough",
/**
 * Hosts for which the placeholder passes through unchanged.
 */
hosts: Array<CloudHostPattern>, };

export type CloudCreateSandboxResponse = {
/**
 * Server-side UUID.
 */
id: string,
/**
 * Owning org's UUID.
 */
org_id: string,
/**
 * User-facing, per-org sandbox name.
 */
name: string,
/**
 * Canonical, resolved SSH username token.
 */
slug: string,
/**
 * Current lifecycle status.
 */
status: CloudSandboxStatus,
/**
 * The sandbox spec the cloud control plane stored for this sandbox.
 */
spec: CloudSandboxSpec,
/**
 * Whether the sandbox should be removed when its allocation terminates.
 */
ephemeral: boolean,
/**
 * Creation timestamp.
 */
created_at: string,
/**
 * Last start timestamp, when known.
 */
started_at: string | null,
/**
 * Last stop timestamp, when known.
 */
stopped_at: string | null,
/**
 * Last failure reason, when any.
 */
last_error: string | null, };

export type CloudSandboxStatus = "created" | "starting" | "running" | "stopping" | "stopped" | "failed";

export type CloudPaginated<T> = {
/**
 * Page of response items.
 */
data: Array<T>,
/**
 * Cursor for the next page, when one exists.
 */
next_cursor: string | null, };

export type CloudMessageResponse = {
/**
 * Human-readable response message.
 */
message: string, };

export type CloudErrorBody = {
/**
 * Flat machine-readable error code, when returned in this shape.
 */
code: string | null,
/**
 * Flat human-readable error message, when returned in this shape.
 */
message: string | null,
/**
 * Nested error object returned by the API error responder.
 */
error: CloudErrorDetails | null, };

export type CloudErrorDetails = {
/**
 * Machine-readable error code.
 */
code: string | null,
/**
 * Human-readable error message.
 */
message: string | null, };
