/*
 Generated by typeshare 1.13.4
*/

/** Per-domain certificate cache configuration. */
export interface CertCacheConfig {
	/** Maximum number of cached certificates. Default: 1000. */
	capacity: number;
	/** Certificate validity duration in hours. Default: 24. */
	validity_hours: number;
}

/** Sandbox lifecycle status returned by the cloud control plane. */
export enum CloudSandboxStatus {
	/** Created in the database but not yet started. */
	Created = "created",
	/** Start request has been submitted. */
	Starting = "starting",
	/** Sandbox is running. */
	Running = "running",
	/** Stop request has been submitted. */
	Stopping = "stopping",
	/** Sandbox is stopped. */
	Stopped = "stopped",
	/** Sandbox failed. */
	Failed = "failed",
}

/**
 * Cloud root filesystem source.
 *
 * Mirrors the domain [`RootfsSource`] JSON shape, but keeps writable-disk
 * sizing out of the image payload. Cloud callers express that intent through
 * [`CloudSandboxResources::disk_size_mib`]; conversion to the domain spec
 * attaches it to OCI rootfs.
 */
export type CloudRootfsSource =
	/** Use a host directory directly as the root filesystem. */
	| { type: "bind", content: string }
	/** Use an OCI image reference with an EROFS lower and ext4 overlay upper. */
	| { type: "oci", content: {
	/** OCI image reference (e.g. `python`). */
	reference: string;
}}
	/** Use a disk image file as the root filesystem via virtio-blk. */
	| { type: "disk_image", content: {
	/** Path to the disk image file on the host. */
	path: string;
	/** Disk image format. */
	format: DiskImageFormat;
	/** Inner filesystem type (optional; auto-detected if absent). */
	fstype?: string;
}};

/** Cloud resource request. */
export interface CloudSandboxResources {
	/** Number of virtual CPUs. */
	vcpus: number;
	/** Guest memory in MiB. */
	memory_mib: number;
	/** Writable disk size in MiB. Applies only to OCI root filesystems. */
	disk_size_mib?: number;
}

/** Runtime log verbosity for sandbox specs. */
export enum SandboxLogLevel {
	/** Emit only error logs. */
	Error = "error",
	/** Emit warning and error logs. */
	Warn = "warn",
	/** Emit info, warning, and error logs. */
	Info = "info",
	/** Emit debug and higher-severity logs. */
	Debug = "debug",
	/** Emit trace and higher-severity logs. */
	Trace = "trace",
}

/** Guest runtime options for a sandbox. */
export interface SandboxRuntimeOptions {
	/** Working directory inside the guest. */
	workdir?: string;
	/** Default shell for scripts and interactive sessions. */
	shell?: string;
	/** Named scripts available inside the guest. */
	scripts: Record<string, string>;
	/** Image entrypoint override. */
	entrypoint?: string[];
	/** Image command override. */
	cmd?: string[];
	/** Guest hostname override. */
	hostname?: string;
	/** Guest user identity override. */
	user?: string;
	/** Runtime log verbosity. */
	log_level?: SandboxLogLevel;
	/** Metrics sampling interval in milliseconds. `None` disables sampling. */
	metrics_sample_interval_ms?: number;
	/** Force-disable metrics sampling regardless of `metrics_sample_interval_ms`. */
	disable_metrics_sample: boolean;
}

/** Environment variable entry. */
export interface EnvVar {
	/** Environment variable name. */
	key: string;
	/** Environment variable value. */
	value: string;
}

/** POSIX resource limit identifiers. */
export enum RlimitResource {
	/** Max CPU time in seconds (`RLIMIT_CPU`). */
	Cpu = "cpu",
	/** Max file size in bytes (`RLIMIT_FSIZE`). */
	Fsize = "fsize",
	/** Max data segment size (`RLIMIT_DATA`). */
	Data = "data",
	/** Max stack size (`RLIMIT_STACK`). */
	Stack = "stack",
	/** Max core file size (`RLIMIT_CORE`). */
	Core = "core",
	/** Max resident set size (`RLIMIT_RSS`). */
	Rss = "rss",
	/** Max number of processes (`RLIMIT_NPROC`). */
	Nproc = "nproc",
	/** Max open file descriptors (`RLIMIT_NOFILE`). */
	Nofile = "nofile",
	/** Max locked memory (`RLIMIT_MEMLOCK`). */
	Memlock = "memlock",
	/** Max address space size (`RLIMIT_AS`). */
	As = "as",
	/** Max file locks (`RLIMIT_LOCKS`). */
	Locks = "locks",
	/** Max pending signals (`RLIMIT_SIGPENDING`). */
	Sigpending = "sigpending",
	/** Max bytes in POSIX message queues (`RLIMIT_MSGQUEUE`). */
	Msgqueue = "msgqueue",
	/** Max nice priority (`RLIMIT_NICE`). */
	Nice = "nice",
	/** Max real-time priority (`RLIMIT_RTPRIO`). */
	Rtprio = "rtprio",
	/** Max real-time timeout (`RLIMIT_RTTIME`). */
	Rttime = "rttime",
}

/** A POSIX resource limit. */
export interface Rlimit {
	/** Resource type. */
	resource: RlimitResource;
	/** Soft limit (can be raised up to hard limit by the process). */
	soft: number;
	/** Hard limit (ceiling, requires privileges to raise). */
	hard: number;
}

/** A volume mount specification for a sandbox. */
export type VolumeMount =
	/** Bind mount a host directory into the guest. */
	| { type: "bind", content: {
	/** Host path to bind mount. */
	host: string;
	/** Guest mount path. */
	guest: string;
	/** Guest mount behavior. */
	options?: MountOptions;
	/** Guest-visible stat virtualization policy. */
	stat_virtualization: StatVirtualization;
	/** Host permission propagation policy. */
	host_permissions: HostPermissions;
	/**
	 * Guest-write byte budget in MiB.
	 *
	 * Bounds how much the guest may add beyond the directory's existing
	 * contents. `None` applies the protective default at spawn time; set a
	 * value to override it.
	 */
	quota_mib?: number;
}}
	/** Mount a named volume into the guest. */
	| { type: "named", content: {
	/** Volume name. */
	name: string;
	/** Guest mount path. */
	guest: string;
	/** Guest mount behavior. */
	options?: MountOptions;
	/** Guest-visible stat virtualization policy. */
	stat_virtualization: StatVirtualization;
	/** Host permission propagation policy. */
	host_permissions: HostPermissions;
}}
	/** Temporary filesystem backed by guest memory. */
	| { type: "tmpfs", content: {
	/** Guest mount path. */
	guest: string;
	/** Size limit in MiB. */
	size_mib?: number;
	/** Guest mount behavior. */
	options?: MountOptions;
}}
	/** Mount a disk image file as a virtio-blk device at a guest path. */
	| { type: "disk_image", content: {
	/** Host path to the disk image file. */
	host: string;
	/** Guest mount path. */
	guest: string;
	/** Disk image format. */
	format: DiskImageFormat;
	/** Inner filesystem type. When `None`, agentd probes `/proc/filesystems`. */
	fstype?: string;
	/** Guest mount behavior. */
	options?: MountOptions;
}};

/** Rootfs patch applied before VM startup. */
export type Patch =
	/** Write text content to a file. */
	| { type: "text", content: {
	/** Absolute guest path, such as `/etc/app.conf`. */
	path: string;
	/** Text content to write. */
	content: string;
	/** File permissions, such as `0o644`. `None` uses the default. */
	mode?: number;
	/** Allow replacing a file that already exists in the rootfs. */
	replace: boolean;
}}
	/** Write raw bytes to a file. */
	| { type: "file", content: {
	/** Absolute guest path. */
	path: string;
	/** Raw byte content to write. */
	content: number[];
	/** File permissions, such as `0o644`. `None` uses the default. */
	mode?: number;
	/** Allow replacing a file that already exists in the rootfs. */
	replace: boolean;
}}
	/** Copy a file from the host into the rootfs. */
	| { type: "copy_file", content: {
	/** Host path to copy from. */
	src: string;
	/** Absolute guest destination path. */
	dst: string;
	/** File permissions. `None` preserves source permissions. */
	mode?: number;
	/** Allow replacing a file that already exists in the rootfs. */
	replace: boolean;
}}
	/** Copy a directory from the host into the rootfs. */
	| { type: "copy_dir", content: {
	/** Host directory to copy from. */
	src: string;
	/** Absolute guest destination path. */
	dst: string;
	/** Allow replacing files that already exist in the rootfs. */
	replace: boolean;
}}
	/** Create a symlink. */
	| { type: "symlink", content: {
	/** Symlink target path. */
	target: string;
	/** Absolute guest path where the symlink is created. */
	link: string;
	/** Allow replacing a path that already exists in the rootfs. */
	replace: boolean;
}}
	/** Create a directory. */
	| { type: "mkdir", content: {
	/** Absolute guest path. */
	path: string;
	/** Directory permissions, such as `0o755`. `None` uses the default. */
	mode?: number;
}}
	/** Remove a file or directory. */
	| { type: "remove", content: {
	/** Absolute guest path to remove. */
	path: string;
}}
	/** Append content to an existing file. */
	| { type: "append", content: {
	/** Absolute guest path of the file to append to. */
	path: string;
	/** Content to append. */
	content: string;
}};

/**
 * Optional guest interface overrides. Unset fields are derived from the
 * sandbox slot by the local network engine. Carried in
 * [`NetworkSpec::interface`].
 */
export interface InterfaceOverrides {
	/** Guest MAC address as six octets. Default: derived from slot. */
	mac?: number[];
	/** Interface MTU. Default: 1500. */
	mtu?: number;
	/** Guest IPv4 address (e.g. `172.16.0.2`). Default: derived from slot. */
	ipv4_address?: string;
	/** Guest IPv4 pool CIDR (e.g. `"172.16.0.0/12"`). Default: derived from slot. */
	ipv4_pool?: string;
	/** Guest IPv6 address. Default: derived from slot. */
	ipv6_address?: string;
	/** Guest IPv6 pool CIDR. Default: derived from slot. */
	ipv6_pool?: string;
}

/** Transport protocol for a published port. */
export enum PortProtocol {
	/** TCP. */
	Tcp = "tcp",
	/** UDP. */
	Udp = "udp",
}

/** A published port mapping between host and guest. */
export interface PublishedPortSpec {
	/** Host-side port to bind. */
	host_port: number;
	/** Guest-side port to forward to. */
	guest_port: number;
	/** Transport protocol. */
	protocol?: PortProtocol;
	/** Host address to bind. Defaults to loopback. */
	host_bind: string;
}

/** Action to take on traffic matched by a [`Rule`] (or a policy default). */
export enum Action {
	/** Allow the traffic. */
	Allow = "allow",
	/** Silently drop the traffic. */
	Deny = "deny",
}

/** Direction a [`Rule`] applies to. */
export enum Direction {
	/** Outbound: guest → destination. */
	Egress = "egress",
	/** Inbound: peer → guest. */
	Ingress = "ingress",
	/** Either direction. */
	Any = "any",
}

/**
 * Traffic destination filter for a [`Rule`].
 *
 * The `Cidr`, `Domain`, and `DomainSuffix` leaves carry their canonical
 * string form (e.g. `"10.0.0.0/8"`, `"example.com"`); the local network
 * engine re-parses and validates them into its richer internal types at
 * load time.
 */
export type Destination =
	/** Match any destination. */
	| { type: "any", content?: undefined }
	/** IP address or CIDR block (e.g. `"1.2.3.4"`, `"10.0.0.0/8"`). */
	| { type: "cidr", content: string }
	/** Exact domain name (e.g. `"example.com"`). */
	| { type: "domain", content: string }
	/** Domain suffix — the apex and any subdomain of it. */
	| { type: "domain_suffix", content: string }
	/** A pre-defined destination group. */
	| { type: "group", content: DestinationGroup };

/** Protocol filter for a [`Rule`]. */
export enum Protocol {
	/** TCP. */
	Tcp = "tcp",
	/** UDP. */
	Udp = "udp",
	/** ICMPv4. */
	Icmpv4 = "icmpv4",
	/** ICMPv6. */
	Icmpv6 = "icmpv6",
}

/** Inclusive guest-side port range for a [`Rule`] match. */
export interface PortRange {
	/** Start port (inclusive). */
	start: number;
	/** End port (inclusive). */
	end: number;
}

/**
 * A single egress/ingress policy rule. Evaluated first-match-wins per
 * direction.
 */
export interface Rule {
	/** Direction this rule applies to. */
	direction: Direction;
	/** Destination filter (direction-dependent interpretation). */
	destination: Destination;
	/** Protocol set; empty matches any protocol. */
	protocols?: Protocol[];
	/** Guest-side port-range set; empty matches any port. */
	ports?: PortRange[];
	/** Action to take on a match. */
	action: Action;
}

/**
 * Egress/ingress network policy: an ordered [`Rule`] list plus a
 * per-direction default [`Action`]. Carried in [`NetworkSpec::policy`].
 */
export interface NetworkPolicy {
	/** Default action for egress traffic matching no rule. Default: `Deny`. */
	default_egress: Action;
	/** Default action for ingress traffic matching no rule. Default: `Deny`. */
	default_ingress: Action;
	/** Ordered rules, evaluated first-match-wins per direction. */
	rules?: Rule[];
}

/** DNS interception and filtering settings. Carried in [`NetworkSpec::dns`]. */
export interface DnsConfig {
	/** Whether DNS-rebinding protection is enabled. Default: true. */
	rebind_protection: boolean;
	/**
	 * Upstream nameservers as `IP`, `IP:PORT`, `HOST`, or `HOST:PORT`
	 * strings. Empty falls back to the host's `/etc/resolv.conf`.
	 */
	nameservers: string[];
	/** Per-query timeout in milliseconds. Default: 5000. */
	query_timeout_ms: number;
}

/** Certificate authority configuration for TLS interception. */
export interface InterceptCaConfig {
	/**
	 * Path to an existing CA certificate PEM file. If `None`, a CA is
	 * auto-generated and persisted.
	 */
	cert_path?: string;
	/**
	 * Path to an existing CA private key PEM file. If `None`, a key is
	 * auto-generated and persisted.
	 */
	key_path?: string;
}

/**
 * TLS interception configuration. Carried in [`NetworkSpec::tls`](NetworkSpec).
 *
 * The local network engine terminates TCP at its in-process stack, so TLS MITM
 * is handled by proxy tasks — these fields configure which ports/domains are
 * intercepted and how the interception CA is sourced.
 */
export interface TlsConfig {
	/** Whether TLS interception is enabled. */
	enabled?: boolean;
	/** TCP ports subject to TLS interception (default: `[443]`). */
	intercepted_ports: number[];
	/** Domains to bypass (no MITM). Supports exact match and `*.suffix` wildcards. */
	bypass?: string[];
	/** Whether to verify the upstream server's TLS certificate. */
	verify_upstream: boolean;
	/**
	 * Drop UDP to intercepted ports when TLS interception is active, forcing
	 * QUIC traffic to fall back to TCP/TLS.
	 */
	block_quic_on_intercept: boolean;
	/** CA certificate PEM files to trust for upstream server verification. */
	upstream_ca_cert?: string[];
	/**
	 * Interception CA configuration. The TLS proxy uses this CA to sign
	 * per-domain certs it presents to the guest during interception.
	 */
	intercept_ca?: InterceptCaConfig;
	/** Per-domain certificate cache configuration. */
	cache?: CertCacheConfig;
}

/** Host pattern for a secret allowlist. */
export type HostPattern =
	/** Exact hostname match. */
	| { type: "exact", content: string }
	/** Wildcard match (e.g., `*.openai.com`). */
	| { type: "wildcard", content: string }
	/** Any host (dangerous — secret can be exfiltrated). */
	| { type: "any", content?: undefined };

/** Where in the HTTP request a secret can be injected. */
export interface SecretInjection {
	/** Substitute in HTTP headers (default: true). */
	headers: boolean;
	/** Substitute in HTTP Basic Auth (default: true). */
	basic_auth: boolean;
	/** Substitute in URL query parameters (default: false). */
	query_params?: boolean;
	/**
	 * Substitute in request body (default: false).
	 *
	 * Fixed-length HTTP/1 bodies up to 16 MiB update `Content-Length`;
	 * larger fixed-length bodies are blocked. Chunked HTTP/1 bodies are
	 * decoded and re-encoded with fresh chunk sizes. Encoded bodies pass
	 * through unchanged. HTTP/2 DATA-frame body substitution is not
	 * supported; matching body placeholders are blocked.
	 */
	body?: boolean;
}

/** Action when a secret placeholder is detected going to a disallowed host. */
export type ViolationAction =
	/** Block the request silently. */
	| { type: "block", content?: undefined }
	/** Block and log (default). */
	| { type: "block_and_log", content?: undefined }
	/** Block and terminate the sandbox. */
	| { type: "block_and_terminate", content?: undefined }
	/** Forward the request with the placeholder unchanged for matching hosts. */
	| { type: "passthrough", content: HostPattern[] };

/**
 * A single secret entry.
 *
 * `value` is the sensitive material — it never enters the sandbox and is
 * redacted by the [`Debug`](fmt::Debug) impl.
 */
export interface SecretEntry {
	/**
	 * Environment variable name exposed to the sandbox (holds the placeholder).
	 *
	 * Must be non-empty and must not contain `=` or NUL. microsandbox does
	 * not require shell-identifier syntax because Linux environment entries
	 * only require a `NAME=value` shape.
	 */
	env_var: string;
	/** The actual secret value (never enters the sandbox). */
	value: string;
	/**
	 * Placeholder string the sandbox sees instead of the real value.
	 *
	 * Must be non-empty, no longer than [`MAX_SECRET_PLACEHOLDER_BYTES`], and
	 * must not contain NUL, CR, or LF.
	 */
	placeholder: string;
	/** Hosts allowed to receive this secret. */
	allowed_hosts?: HostPattern[];
	/** Where the secret can be injected. */
	injection?: SecretInjection;
	/** Action on a violation for this secret (overrides the config default). */
	on_violation?: ViolationAction;
	/**
	 * Require verified TLS identity before substituting (default: true).
	 *
	 * When true, the secret is only substituted if the connection uses TLS
	 * interception (not bypass) and the SNI matches an allowed host.
	 */
	require_tls_identity: boolean;
}

/**
 * Placeholder-based secret injection for a sandbox's TLS-intercepted egress.
 *
 * The sandbox only ever sees each secret's `placeholder`; the local network
 * engine substitutes the real `value` into outbound requests bound for an
 * allowed host (and blocks/forwards per [`ViolationAction`] otherwise). Carried
 * in [`NetworkSpec::secrets`](NetworkSpec).
 */
export interface SecretsConfig {
	/** List of secrets to inject. */
	entries?: SecretEntry[];
	/** Default action when a placeholder leaks to a disallowed host. */
	on_violation?: ViolationAction;
}

/**
 * Complete network specification for a sandbox.
 *
 * All subdocuments are typed. The local-engine `policy`, `dns`, and
 * `interface` configs are mirrored here as wire types whose leaf values
 * (CIDRs, domain names, nameservers) are carried in their canonical string
 * form; the network engine re-parses these into its richer internal types at
 * load time, which keeps that engine's validation crates out of this shared
 * contract.
 */
export interface NetworkSpec {
	/** Whether networking is enabled for this sandbox. */
	enabled: boolean;
	/** Guest interface overrides for the local network engine. */
	interface?: InterfaceOverrides;
	/** Host-to-guest port mappings. */
	ports: PublishedPortSpec[];
	/** Egress and ingress policy. */
	policy?: NetworkPolicy;
	/** DNS interception and filtering. */
	dns?: DnsConfig;
	/** TLS-interception subdocument (see [`TlsConfig`]). */
	tls?: TlsConfig;
	/** Placeholder-based secret-injection subdocument (see [`SecretsConfig`]). */
	secrets?: SecretsConfig;
	/** Max concurrent guest connections. */
	max_connections?: number;
	/** Whether to copy trusted host CAs into the guest at boot. */
	trust_host_cas: boolean;
}

/** Fully-assembled handoff-init specification. */
export interface HandoffInit {
	/** Init binary: absolute path inside the guest rootfs, or the literal `auto`. */
	cmd: string;
	/** Supplemental argv. `argv[0]` is implicitly `cmd`. */
	args?: string[];
	/** Extra env vars merged on top of the inherited env. */
	env?: string[][];
}

/** Controls when an OCI registry is contacted for manifest freshness. */
export enum PullPolicy {
	/** Use cached layers if complete, pull otherwise. */
	IfMissing = "if_missing",
	/** Always fetch the manifest from the registry, reusing cached layers whose digests still match. */
	Always = "always",
	/** Never contact the registry. Error if the image is not fully cached locally. */
	Never = "never",
}

/** Sandbox-level in-guest security profile. */
export enum SecurityProfile {
	/**
	 * Preserve normal guest-root semantics.
	 *
	 * Exec sessions do not set `no_new_privs` and keep `CAP_SYS_ADMIN`, so workflows such as `sudo`, package managers, and Docker-in-Docker work as they would in a regular VM.
	 */
	Default = "default",
	/**
	 * Harden guest exec sessions.
	 *
	 * Agentd sets `no_new_privs`, drops `CAP_SYS_ADMIN`, and forces `nosuid,nodev` on user mounts. Workloads that need privilege elevation or guest mount administration, such as `sudo` and Docker-in-Docker, are intentionally incompatible with this profile.
	 */
	Restricted = "restricted",
}

/** Sandbox lifecycle policy. */
export interface SandboxPolicy {
	/**
	 * Whether the sandbox is ephemeral.
	 *
	 * Ephemeral sandboxes are one-off: the host runtime that owns the
	 * process removes the persisted DB row and on-disk state when the VM
	 * reaches a terminal status, and other host runtimes opportunistically
	 * clean up ephemeral leftovers from runtimes that died before they
	 * could self-clean. Defaults to `false` (persistent); named and created
	 * sandboxes stay inspectable and restartable after they stop.
	 */
	ephemeral?: boolean;
	/** Hard cap on total sandbox lifetime in seconds. `None` = run forever. */
	max_duration_secs?: number;
	/** Idle timeout in seconds. `None` = no idle detection. */
	idle_timeout_secs?: number;
}

/** Cloud sandbox specification carried on create routes. */
export interface CloudSandboxSpec {
	/** Unique sandbox name. */
	name: string;
	/** Root filesystem source. */
	image: CloudRootfsSource;
	/** CPU, memory, and user-facing disk resources. */
	resources: CloudSandboxResources;
	/** Guest runtime options. */
	runtime: SandboxRuntimeOptions;
	/** Environment variables visible to commands in the sandbox. */
	env: EnvVar[];
	/** User-defined labels attached to the sandbox. */
	labels: Record<string, string>;
	/** Sandbox-wide resource limits inherited by guest processes. */
	rlimits: Rlimit[];
	/** Volume mounts. */
	mounts: VolumeMount[];
	/** Rootfs patches applied before VM start. */
	patches: Patch[];
	/** Network specification. */
	network: NetworkSpec;
	/** Hand off PID 1 to a guest init binary after agentd setup. */
	init?: HandoffInit;
	/** Pull policy for OCI images. */
	pull_policy: PullPolicy;
	/** In-guest security profile. */
	security_profile: SecurityProfile;
	/** Sandbox lifecycle policy. */
	lifecycle: SandboxPolicy;
}

/** Wire shape of the cloud sandbox response returned by sandbox endpoints. */
export interface CloudCreateSandboxResponse {
	/** Server-side UUID. */
	id: string;
	/** Owning org's UUID. */
	org_id: string;
	/** User-facing, per-org sandbox name. */
	name: string;
	/** Canonical, resolved SSH username token. */
	slug: string;
	/** Current lifecycle status. */
	status: CloudSandboxStatus;
	/** The sandbox spec the cloud control plane stored for this sandbox. */
	spec: CloudSandboxSpec;
	/** Whether the sandbox should be removed when its allocation terminates. */
	ephemeral: boolean;
	/** Creation timestamp. */
	created_at: string;
	/** Last start timestamp, when known. */
	started_at?: string;
	/** Last stop timestamp, when known. */
	stopped_at?: string;
	/** Last failure reason, when any. */
	last_error?: string;
}

/** Nested cloud API error details. */
export interface CloudErrorDetails {
	/** Machine-readable error code. */
	code?: string;
	/** Human-readable error message. */
	message?: string;
}

/** Wire shape of the typed error body returned by cloud APIs on 4xx/5xx responses. */
export interface CloudErrorBody {
	/** Flat machine-readable error code, when returned in this shape. */
	code?: string;
	/** Flat human-readable error message, when returned in this shape. */
	message?: string;
	/** Nested error object returned by the API error responder. */
	error?: CloudErrorDetails;
}

/** Wire shape of the message response returned by mutation endpoints. */
export interface CloudMessageResponse {
	/** Human-readable response message. */
	message: string;
}

/** Wire shape of paginated list responses. */
export interface CloudPaginated<T> {
	/** Page of response items. */
	data: T[];
	/** Cursor for the next page, when one exists. */
	next_cursor?: string;
}

/** Guest mount behavior shared by every volume mount kind. */
export interface MountOptions {
	/**
	 * Whether the mount is read-only.
	 *
	 * Guest writes fail with the kernel's read-only filesystem behavior. Virtiofs-backed mounts also reject writes on the host-side filesystem server as defense in depth.
	 */
	readonly: boolean;
	/**
	 * Whether direct execution from the mount is disabled.
	 *
	 * This prevents `execve` of binaries or scripts located on the mount. Interpreters can still read files from the mount, for example `sh /mnt/script.sh`, because the interpreter itself executes from a different filesystem.
	 */
	noexec: boolean;
	/** Whether setuid and setgid privilege elevation from files on the mount is ignored. */
	nosuid: boolean;
	/** Whether device files on the mount are ignored. */
	nodev: boolean;
}

/** Sandbox-time behavior for a named volume mount. */
export enum NamedVolumeMode {
	/** Require the named volume to already exist. */
	Existing = "existing",
	/** Create the named volume and fail if it already exists. */
	Create = "create",
	/** Ensure the named volume exists, or reuse a compatible existing volume. */
	EnsureExists = "ensure_exists",
}

/** Storage kind for a named volume. */
export enum VolumeKind {
	/** Directory-backed named volume mounted through virtiofs. */
	Directory = "directory",
	/** Raw ext4 disk-image named volume mounted through virtio-blk. */
	Disk = "disk",
}

/** Creation metadata for sandbox-time named volume provisioning. */
export interface NamedVolumeCreate {
	/** Creation behavior for this named volume mount. */
	mode: NamedVolumeMode;
	/** Volume name to create or ensure exists. */
	name: string;
	/** Storage kind to create or ensure exists. */
	kind: VolumeKind;
	/** Directory quota in MiB, if configured. */
	quota_mib?: number;
	/** Disk capacity in MiB, if configured. */
	capacity_mib?: number;
	/** Labels to attach to newly-created volumes. */
	labels: string[][];
}

/** OCI root filesystem source. */
export interface OciRootfsSource {
	/** OCI image reference (e.g. `python`). */
	reference: string;
	/** Writable overlay upper size in MiB. */
	upper_size_mib?: number;
}

/** CPU and memory resources for a sandbox. */
export interface SandboxResources {
	/** Number of virtual CPUs. */
	vcpus: number;
	/** Guest memory in MiB. */
	memory_mib: number;
}

/** Root filesystem source for a sandbox. */
export type RootfsSource =
	/** Use a host directory directly as the root filesystem. */
	| { type: "bind", content: string }
	/** Use an OCI image reference with an EROFS lower and ext4 overlay upper. */
	| { type: "oci", content: OciRootfsSource }
	/** Use a disk image file as the root filesystem via virtio-blk. */
	| { type: "disk_image", content: {
	/** Path to the disk image file on the host. */
	path: string;
	/** Disk image format. */
	format: DiskImageFormat;
	/** Inner filesystem type (optional; auto-detected if absent). */
	fstype?: string;
}};

/**
 * Backend-neutral sandbox task description.
 *
 * This is the durable contract for fields that are already shared across backends. Local-only execution state such as resolved manifest digests, snapshot upper-layer paths, registry credentials, replace flags, and backend dispatch stays outside this type.
 */
export interface SandboxSpec {
	/** Unique sandbox name. */
	name: string;
	/** Root filesystem source. */
	image: RootfsSource;
	/** CPU and memory resources. */
	resources: SandboxResources;
	/** Guest runtime options. */
	runtime: SandboxRuntimeOptions;
	/** Environment variables visible to commands in the sandbox. */
	env: EnvVar[];
	/** User-defined labels attached to the sandbox. */
	labels: Record<string, string>;
	/** Sandbox-wide resource limits inherited by guest processes. */
	rlimits: Rlimit[];
	/** Volume mounts. */
	mounts: VolumeMount[];
	/** Rootfs patches applied before VM start. */
	patches: Patch[];
	/** Network specification. */
	network: NetworkSpec;
	/** Hand off PID 1 to a guest init binary after agentd setup. */
	init?: HandoffInit;
	/** Pull policy for OCI images. */
	pull_policy: PullPolicy;
	/** In-guest security profile. */
	security_profile: SecurityProfile;
	/** Sandbox lifecycle policy. */
	lifecycle: SandboxPolicy;
}

/** Configuration for creating a named volume. */
export interface VolumeSpec {
	/** Volume name. */
	name: string;
	/** Storage kind. */
	kind: VolumeKind;
	/** Size quota in MiB. `None` means unlimited. */
	quota_mib?: number;
	/** Disk capacity in MiB. Required for disk volumes. */
	capacity_mib?: number;
	/** Labels for organization. */
	labels: string[][];
}

/** Pre-defined destination category for a [`Destination::Group`] match. */
export enum DestinationGroup {
	/** Public internet — any address not in another category. */
	Public = "public",
	/** Loopback addresses (`127.0.0.0/8`, `::1`). */
	Loopback = "loopback",
	/** Private ranges (RFC 1918 / RFC 4193 ULA / CGN). */
	Private = "private",
	/** Link-local addresses, excluding the metadata IP. */
	LinkLocal = "link_local",
	/** Cloud metadata endpoint (`169.254.169.254`). */
	Metadata = "metadata",
	/** Multicast addresses (`224.0.0.0/4`, `ff00::/8`). */
	Multicast = "multicast",
	/** The sandbox host, reachable via the gateway IP. */
	Host = "host",
}

/** Disk image format for virtio-blk root filesystems and volume mounts. */
export enum DiskImageFormat {
	/** QEMU Copy-on-Write v2. */
	Qcow2 = "qcow2",
	/** Raw disk image. */
	Raw = "raw",
	/** VMware Disk (FLAT/ZERO only, no delta links). */
	Vmdk = "vmdk",
}

/**
 * Host permission propagation policy for a virtiofs-backed volume mount.
 *
 * Serializes/deserializes as the lowercase variant name (`"private"`, `"mirror"`) to align with the CLI and NAPI spellings.
 */
export enum HostPermissions {
	/** Guest chmod stays in the metadata overlay only. */
	Private = "private",
	/** Mirror ordinary rwx bits for regular files and directories to the host inode. */
	Mirror = "mirror",
}

/**
 * Stat virtualization policy for a virtiofs-backed volume mount.
 *
 * Serializes/deserializes as the lowercase variant name (`"strict"`, `"relaxed"`, `"off"`) so persisted JSON aligns with the CLI grammar (`stat-virt=strict|relaxed|off`) and the NAPI string contract.
 */
export enum StatVirtualization {
	/** Fail-closed: probe the host backing path; require xattr support. */
	Strict = "strict",
	/** Opportunistic: apply the overlay when present; tolerate missing xattr support. */
	Relaxed = "relaxed",
	/** Literal host metadata: do not read or apply the override xattr. */
	Off = "off",
}
