#!/usr/bin/env bash
# Guard against node-ts SDK docs drift (issue #590).
#
# The node-ts public API surface has two layers:
#   - sdk/node-ts/native/index.d.ts — generated by NAPI-RS from the #[napi]
#     annotations in sdk/node-ts/native/*.rs
#   - dist/index.d.ts (not committed) — compiled from sdk/node-ts/src/**/*.ts,
#     the package-root types re-exporting the native layer
#
# A PR is treated as changing the public API when any of these fire:
#   1. native/index.d.ts changed (authoritative generated surface), or
#   2. the export-declaration lines of src/**/*.ts (excluding src/internal/)
#      differ between base and head, or
#   3. the #[napi] / pub declaration lines of native/*.rs differ between base
#      and head — this also catches PRs that edit the Rust bindings but forget
#      to commit the regenerated index.d.ts.
#
# Signals 2 and 3 are line-grep heuristics, deliberately: regenerating the
# declarations for comparison would require a full Rust/NAPI toolchain build,
# which is too heavy for this guard and would break simple local runs.
# Body-only edits don't touch declaration lines, so they don't fire.
#
# When an API signal fires, the PR must also touch docs/sdk/typescript/.
#
# Usage: check-node-sdk-docs-drift.sh <base-ref> [head-ref]
#   Diffs merge-base(base-ref, head-ref)..head-ref. head-ref defaults to HEAD.
#
# Escape hatches for API changes that genuinely need no docs update:
#   - apply the `docs-skip` label to the PR (CI passes DOCS_SKIP=true), or
#   - add a `docs-skip: <reason>` trailer to any commit in the PR.

set -euo pipefail

BASE="${1:?usage: check-node-sdk-docs-drift.sh <base-ref> [head-ref]}"
HEAD="${2:-HEAD}"

API_DTS="sdk/node-ts/native/index.d.ts"
DOCS_PATTERN='^docs/sdk/typescript(/|\.mdx$)'

MERGE_BASE="$(git merge-base "$BASE" "$HEAD")"
CHANGED="$(git diff --name-only "$MERGE_BASE" "$HEAD")"

# Extract the export-declaration lines of the package-root TS surface at a
# given revision. src/internal/ is private implementation, not re-exported.
ts_surface() {
  local rev="$1" f
  git ls-tree -r --name-only "$rev" -- sdk/node-ts/src \
    | grep -E '\.ts$' | grep -v '^sdk/node-ts/src/internal/' \
    | while IFS= read -r f; do
        git show "$rev:$f" | grep -E '^export ' | sed "s|^|$f: |" || true
      done
}

# Extract the #[napi] attribute and pub declaration lines of the Rust binding
# sources at a given revision. pub(crate) items are internal and excluded.
rs_surface() {
  local rev="$1" f
  git ls-tree -r --name-only "$rev" -- sdk/node-ts/native \
    | grep -E '\.rs$' \
    | while IFS= read -r f; do
        git show "$rev:$f" | grep -E '^[[:space:]]*(#\[napi|pub )' \
          | sed "s|^|$f: |" || true
      done
}

signals=()
dts_changed=false
if grep -qxF "$API_DTS" <<<"$CHANGED"; then
  dts_changed=true
  signals+=("generated declarations changed: $API_DTS")
fi

TS_DIFF="$(diff <(ts_surface "$MERGE_BASE") <(ts_surface "$HEAD") || true)"
if [[ -n "$TS_DIFF" ]]; then
  signals+=("package-root export surface changed: sdk/node-ts/src/")
fi

RS_DIFF="$(diff <(rs_surface "$MERGE_BASE") <(rs_surface "$HEAD") || true)"
if [[ -n "$RS_DIFF" ]]; then
  signals+=("native binding declarations changed: sdk/node-ts/native/*.rs")
fi

if [[ ${#signals[@]} -eq 0 ]]; then
  echo "OK: node-ts public API surface unchanged; no docs update required."
  exit 0
fi

if grep -qE "$DOCS_PATTERN" <<<"$CHANGED"; then
  echo "OK: node-ts API surface and TypeScript SDK docs both updated."
  exit 0
fi

if [[ "${DOCS_SKIP:-}" == "true" ]]; then
  echo "OK: docs check skipped via docs-skip label."
  exit 0
fi

if git log --format=%B "$MERGE_BASE..$HEAD" | grep -qiE '^docs-skip:'; then
  echo "OK: docs check skipped via docs-skip commit trailer."
  exit 0
fi

echo "::error::node-ts public API changed without a matching update under docs/sdk/typescript/"
echo
echo "This PR changes the node-ts SDK public surface but does not touch the"
echo "TypeScript SDK reference docs. Update the relevant page(s) under"
echo "docs/sdk/typescript/, or — if this API change genuinely needs no docs"
echo "update — apply the 'docs-skip' PR label or add a 'docs-skip: <reason>'"
echo "trailer to a commit."
echo
echo "API-change signals:"
for s in "${signals[@]}"; do echo "  - $s"; done

# Show the relevant diffs so the author can locate the affected exports;
# each section is capped to keep the log readable on large regenerations.
show_capped() {
  local title="$1" body="$2"
  echo
  echo "$title"
  echo "-----------------------------------------------------------------------"
  sed -n '1,200p' <<<"$body"
  if [[ "$(wc -l <<<"$body")" -gt 200 ]]; then
    echo "... (truncated)"
  fi
}

if $dts_changed; then
  show_capped "Changed declarations in $API_DTS:" \
    "$(git diff "$MERGE_BASE" "$HEAD" -- "$API_DTS" | tail -n +5)"
fi
[[ -n "$TS_DIFF" ]] && show_capped "Changed src export lines:" "$TS_DIFF"
[[ -n "$RS_DIFF" ]] && show_capped "Changed native declaration lines:" "$RS_DIFF"
exit 1
