#!/usr/bin/env bash
# Guard against node-ts SDK docs drift (issue #590).
#
# The node-ts public API surface has two layers:
#   - sdk/node-ts/native/index.d.ts — generated by NAPI-RS from the #[napi]
#     annotations in sdk/node-ts/native/*.rs
#   - dist/index.d.ts (not committed) — compiled from sdk/node-ts/src/**/*.ts,
#     the package-root types re-exporting the native layer
#
# A PR is treated as changing the public API when any of these fire:
#   1. native/index.d.ts changed (authoritative generated surface), or
#   2. the TypeScript declarations emitted by tsc from src/**/*.ts differ
#      between base and head. Emitting real declarations, rather than
#      grepping source lines, catches names added or removed inside
#      multi-line `export { ... }` blocks and member changes on exported
#      interfaces/classes, while ignoring body-only edits (declarations
#      carry no bodies). dist/internal/ is INCLUDED: the package root
#      publicly aliases internal declarations (e.g. RootDiskBuilder from
#      internal/napi.ts), so excluding them would hide real API changes;
#      the cost is that a rare internal-only declaration change also fires,
#      which the docs-skip trailer absorbs. Each revision compiles with its
#      own locked typescript/@types/node (from package-lock.json, falling
#      back to package.json ranges), so toolchain-upgrade PRs whose base
#      source predates the new compiler still evaluate; when both
#      revisions lock the same versions the toolchain is installed once.
#      Needs node+npm; only runs when src/ or tsconfig.json actually
#      changed (a pure dependency bump without src changes is not an API
#      signal and must not fire on cross-compiler formatting drift).
#   2b. the package.json entry points (main/module/types/exports) differ —
#      the manifest's export map is public API even when no source file
#      changes; unrelated manifest churn (version, deps) is ignored.
#   3. the NAPI-exported declarations of native/*.rs differ between base
#      and head — including lib.rs module wiring (mod lines and their
#      #[cfg] attributes), since un-declaring or cfg-gating a module drops
#      its exports with every signature intact. This also catches PRs that
#      forget to commit the regenerated index.d.ts. The extractor is
#      bracket-aware and napi-scoped: it captures #[napi(...)] attribute
#      blocks (multi-line included), the annotated item's signature until
#      its parameter list closes, pub signatures inside #[napi] impl
#      blocks, and field/variant declarations inside #[napi] struct/enum
#      blocks. Function bodies and un-annotated helpers (to_napi_error,
#      datetime_to_ms, ...) are never captured, so internal-only edits
#      don't fire. (Regenerating index.d.ts for comparison instead would
#      need a full Rust/NAPI toolchain build — too heavy for this guard
#      and impractical locally.)
#
# When an API signal fires, the PR must also touch docs/sdk/typescript/.
#
# Usage: check-node-sdk-docs-drift.sh <base-ref> [head-ref]
#   Diffs merge-base(base-ref, head-ref)..head-ref. head-ref defaults to HEAD.
#
# Escape hatch for API changes that genuinely need no docs update: add a
# `docs-skip: <reason>` trailer to any commit in the PR — an empty commit
# is fine, and pushing it re-runs CI on the exact tree being skipped:
#   git commit --allow-empty -m "chore: skip docs check" -m "docs-skip: <reason>"
# (DOCS_SKIP=true also short-circuits the check for local/manual runs.)

set -euo pipefail

BASE="${1:?usage: check-node-sdk-docs-drift.sh <base-ref> [head-ref]}"
HEAD="${2:-HEAD}"

API_DTS="sdk/node-ts/native/index.d.ts"
DOCS_PATTERN='^docs/sdk/typescript(/|\.mdx$)'

MERGE_BASE="$(git merge-base "$BASE" "$HEAD")"
CHANGED="$(git diff --name-only "$MERGE_BASE" "$HEAD")"

# Escape hatches run BEFORE any signal computation, deliberately: the
# trailer (or DOCS_SKIP) skips the ENTIRE check — including a guard-self
# failure such as tsc refusing to compile a revision — not just the docs
# requirement. That makes it double as the escape hatch for guard
# malfunctions, and skipped runs never pay the compile cost.
if [[ "${DOCS_SKIP:-}" == "true" ]]; then
  echo "OK: docs check skipped via DOCS_SKIP override."
  exit 0
fi
if git log --format=%B "$MERGE_BASE..$HEAD" | grep -qiE '^docs-skip:'; then
  echo "OK: docs check skipped via docs-skip commit trailer."
  exit 0
fi
# Likewise, if the docs were touched the requirement is satisfied whatever
# the signals would say — skip the expensive computation too.
if grep -qE "$DOCS_PATTERN" <<<"$CHANGED"; then
  echo "OK: TypeScript SDK docs updated in this change; no drift check needed."
  exit 0
fi

TOOLS=""
cleanup() { if [[ -n "$TOOLS" ]]; then rm -rf "$TOOLS"; fi; }
trap cleanup EXIT

require_node() {
  if ! command -v node >/dev/null || ! command -v npm >/dev/null; then
    echo "::error::node and npm are required for this check (sdk/node-ts sources changed)" >&2
    exit 1
  fi
}

# The manifest's entry points are public API too: the exports map and the
# root main/module/types fields. Compare only those, so unrelated manifest
# churn (version bumps, deps, scripts) stays quiet.
pkg_surface() {
  local rev="$1"
  git show "$rev:sdk/node-ts/package.json" | node -e '
    let s = "";
    process.stdin.on("data", (d) => (s += d)).on("end", () => {
      const p = JSON.parse(s);
      console.log(JSON.stringify(
        { main: p.main, module: p.module, types: p.types, exports: p.exports },
        null, 2));
    });'
}

# Print "typescript-version @types/node-version" for a revision, preferring
# the exact locked versions and falling back to package.json ranges.
resolve_toolchain() {
  local rev="$1" out
  if out="$(git show "$rev:sdk/node-ts/package-lock.json" 2>/dev/null | node -e '
      let s = "";
      process.stdin.on("data", (d) => (s += d)).on("end", () => {
        try {
          const p = JSON.parse(s).packages;
          console.log(p["node_modules/typescript"].version + " " +
                      p["node_modules/@types/node"].version);
        } catch { process.exit(1); }
      });')"; then
    echo "$out"
  else
    git show "$rev:sdk/node-ts/package.json" | node -e '
      let s = "";
      process.stdin.on("data", (d) => (s += d)).on("end", () => {
        const d = JSON.parse(s).devDependencies;
        console.log(d.typescript + " " + d["@types/node"]);
      });'
  fi
}

# Install typescript/@types/node into <dir> unless already present there.
install_toolchain() {
  local dir="$1" ts_ver="$2" types_ver="$3"
  [[ -x "$dir/node_modules/.bin/tsc" ]] && return 0
  mkdir -p "$dir"
  npm install --prefix "$dir" --no-save --ignore-scripts --no-audit --no-fund \
    "typescript@$ts_ver" "@types/node@$types_ver" >/dev/null
}

# Emit the TypeScript declaration surface of sdk/node-ts at a revision into
# <workdir>/out, compiling with the tsc under <toolchain>/node_modules
# (resolved by the compiler walking up from the extracted tree).
emit_ts_surface() {
  local rev="$1" toolchain="$2" dir="$3"
  mkdir -p "$dir/tree"
  git archive "$rev" sdk/node-ts | tar -x -C "$dir/tree"
  ln -sfn "$toolchain/node_modules" "$dir/node_modules"
  if ! "$toolchain/node_modules/.bin/tsc" -p "$dir/tree/sdk/node-ts/tsconfig.json" \
      --emitDeclarationOnly --declarationMap false --sourceMap false \
      --outDir "$dir/out"; then
    echo "::error::tsc failed compiling sdk/node-ts/src at $rev with its own locked toolchain" >&2
    exit 1
  fi
}

# Extract the NAPI-exported declaration surface of the Rust binding sources
# at a revision: #[napi] attributes, the annotated item's signature, pub
# signatures inside #[napi] impl blocks, and member declarations inside
# #[napi] struct/enum blocks. Bodies and un-annotated items are skipped.
rs_surface() {
  local rev="$1" f
  git ls-tree -r --name-only "$rev" -- sdk/node-ts/native \
    | grep -E '\.rs$' \
    | while IFS= read -r f; do
        git show "$rev:$f" | awk -v fname="$f" '
          function pcount(s, t) { t = s; sub(/\/\/.*/, "", t)
            return gsub(/\(/, "(", t) - gsub(/\)/, ")", t) }
          function bcount(s, t) { t = s; sub(/\/\/.*/, "", t)
            return gsub(/\{/, "{", t) - gsub(/\}/, "}", t) }
          {
            line = $0
            if (attr) {                       # inside multi-line #[napi(...)]
              print fname ": " line
              if (line ~ /\][[:space:]]*$/) { attr = 0; pending = 1 }
              next
            }
            if (sig) {                        # inside multi-line signature
              print fname ": " line
              pd += pcount(line)
              if (pd <= 0) sig = 0
              depth += bcount(line)
              if (bd && depth < bd) bd = 0
              next
            }
            # Module wiring in lib.rs is surface too: removing or
            # cfg-gating a `mod` line drops its #[napi] exports from the
            # built binding while every signature stays intact. Capture
            # (pub) mod declarations plus the #[cfg] lines attached to
            # them (scoped to lib.rs so in-file test modules elsewhere
            # stay quiet).
            if (fname ~ /\/lib\.rs$/) {
              if (line ~ /^[[:space:]]*#\[cfg/) {
                cfgbuf = cfgbuf fname ": " line "\n"
                next
              }
              if (line ~ /^[[:space:]]*(pub[[:space:]]+)?mod[[:space:]]+[A-Za-z0-9_]/) {
                printf "%s", cfgbuf
                cfgbuf = ""
                print fname ": " line
                next
              }
              cfgbuf = ""
            }
            if (line ~ /^[[:space:]]*#\[napi/) {
              print fname ": " line
              if (line ~ /\][[:space:]]*$/) pending = 1
              else attr = 1
              next
            }
            if (pending) {                    # first item line after #[napi]
              if (line ~ /^[[:space:]]*($|#\[|\/\/)/) next
              pending = 0
              print fname ": " line
              if (line ~ /(^|[[:space:]])impl([[:space:]<]|$)/) {
                depth += bcount(line)
                if (line ~ /\{/) { bd = depth; btype = "impl" }
                next
              }
              if (line ~ /pub[[:space:]]+(struct|enum)/) {
                depth += bcount(line)
                if (line ~ /\{/) { bd = depth; btype = "data" }
                next
              }
              pd = pcount(line)               # fn-like: capture signature
              if (pd > 0) sig = 1
              depth += bcount(line)
              if (bd && depth < bd) bd = 0
              next
            }
            if (bd && depth >= bd) {          # inside a #[napi] block
              if (btype == "impl") {
                if (line ~ /^[[:space:]]*pub /) {
                  print fname ": " line
                  pd = pcount(line)
                  if (pd > 0) sig = 1
                }
              } else if (line !~ /^[[:space:]]*(\/\/|\}|$)/) {
                print fname ": " line         # struct fields / enum variants
              }
            }
            depth += bcount(line)
            if (bd && depth < bd) bd = 0
          }'
      done
}

signals=()
dts_changed=false
if grep -qxF "$API_DTS" <<<"$CHANGED"; then
  dts_changed=true
  signals+=("generated declarations changed: $API_DTS")
fi

PKG_DIFF=""
if grep -qxF 'sdk/node-ts/package.json' <<<"$CHANGED"; then
  require_node
  PKG_DIFF="$(diff <(pkg_surface "$MERGE_BASE") <(pkg_surface "$HEAD") || true)"
  if [[ -n "$PKG_DIFF" ]]; then
    signals+=("package entry points changed: sdk/node-ts/package.json (main/module/types/exports)")
  fi
fi

TS_DIFF=""
if grep -qE '^sdk/node-ts/(src/|tsconfig\.json$)' <<<"$CHANGED"; then
  require_node
  TOOLS="$(mktemp -d)"
  base_tc="$(resolve_toolchain "$MERGE_BASE")"
  head_tc="$(resolve_toolchain "$HEAD")"
  echo "TS toolchains — base: $base_tc, head: $head_tc"
  install_toolchain "$TOOLS/tc-base" $base_tc
  if [[ "$head_tc" == "$base_tc" ]]; then
    ln -sn "$TOOLS/tc-base" "$TOOLS/tc-head"
  else
    install_toolchain "$TOOLS/tc-head" $head_tc
  fi
  emit_ts_surface "$MERGE_BASE" "$TOOLS/tc-base" "$TOOLS/base"
  emit_ts_surface "$HEAD" "$TOOLS/tc-head" "$TOOLS/head"
  TS_DIFF="$(cd "$TOOLS" && diff -ru base/out head/out || true)"
  if [[ -n "$TS_DIFF" ]]; then
    signals+=("package-root TS declaration surface changed: sdk/node-ts/src/")
  fi
fi

RS_DIFF=""
if grep -qE '^sdk/node-ts/native/[^/]+\.rs$' <<<"$CHANGED"; then
  RS_DIFF="$(diff <(rs_surface "$MERGE_BASE") <(rs_surface "$HEAD") || true)"
  if [[ -n "$RS_DIFF" ]]; then
    signals+=("native binding declarations changed: sdk/node-ts/native/*.rs")
  fi
fi

if [[ ${#signals[@]} -eq 0 ]]; then
  echo "OK: node-ts public API surface unchanged; no docs update required."
  exit 0
fi

echo "::error::node-ts public API changed without a matching update under docs/sdk/typescript/"
echo
echo "This PR changes the node-ts SDK public surface but does not touch the"
echo "TypeScript SDK reference docs. Update the relevant page(s) under"
echo "docs/sdk/typescript/. If this API change genuinely needs no docs update,"
echo "push a commit whose message carries a 'docs-skip: <reason>' trailer"
echo "(an empty commit is fine):"
echo "  git commit --allow-empty -m \"chore: skip docs check\" -m \"docs-skip: <reason>\""
echo
echo "API-change signals:"
for s in "${signals[@]}"; do echo "  - $s"; done

# Show the relevant diffs so the author can locate the affected exports;
# each section is capped to keep the log readable on large regenerations.
show_capped() {
  local title="$1" body="$2"
  echo
  echo "$title"
  echo "-----------------------------------------------------------------------"
  sed -n '1,200p' <<<"$body"
  if [[ "$(wc -l <<<"$body")" -gt 200 ]]; then
    echo "... (truncated)"
  fi
}

if $dts_changed; then
  show_capped "Changed declarations in $API_DTS:" \
    "$(git diff "$MERGE_BASE" "$HEAD" -- "$API_DTS" | tail -n +5)"
fi
[[ -n "$PKG_DIFF" ]] && show_capped "Changed package entry points:" "$PKG_DIFF"
[[ -n "$TS_DIFF" ]] && show_capped "Changed emitted TS declarations (base/out vs head/out):" "$TS_DIFF"
[[ -n "$RS_DIFF" ]] && show_capped "Changed native declaration lines:" "$RS_DIFF"
exit 1
