// Code generated by typeshare 1.13.4. DO NOT EDIT.
package msbtypes

import "encoding/json"

// Per-domain certificate cache configuration.
type CertCacheConfig struct {
	// Maximum number of cached certificates. Default: 1000.
	Capacity uint64 `json:"capacity"`
	// Certificate validity duration in hours. Default: 24.
	ValidityHours uint64 `json:"validity_hours"`
}

// Sandbox lifecycle status returned by the cloud control plane.
type CloudSandboxStatus string

const (
	// Created in the database but not yet started.
	CloudSandboxStatusCreated CloudSandboxStatus = "created"
	// Start request has been submitted.
	CloudSandboxStatusStarting CloudSandboxStatus = "starting"
	// Sandbox is running.
	CloudSandboxStatusRunning CloudSandboxStatus = "running"
	// Stop request has been submitted.
	CloudSandboxStatusStopping CloudSandboxStatus = "stopping"
	// Sandbox is stopped.
	CloudSandboxStatusStopped CloudSandboxStatus = "stopped"
	// Sandbox failed.
	CloudSandboxStatusFailed CloudSandboxStatus = "failed"
)

// Generated type representing the anonymous struct variant `Oci` of the `CloudRootfsSource` Rust enum
type CloudRootfsSourceOciInner struct {
	// OCI image reference (e.g. `python`).
	Reference string `json:"reference"`
}

// Generated type representing the anonymous struct variant `DiskImage` of the `CloudRootfsSource` Rust enum
type CloudRootfsSourceDiskImageInner struct {
	// Path to the disk image file on the host.
	Path string `json:"path"`
	// Disk image format.
	Format DiskImageFormat `json:"format"`
	// Inner filesystem type (optional; auto-detected if absent).
	Fstype *string `json:"fstype,omitempty"`
}

// Cloud root filesystem source.
//
// Mirrors the domain [`RootfsSource`] JSON shape, but keeps writable-disk
// sizing out of the image payload. Cloud callers express that intent through
// [`CloudSandboxResources::disk_size_mib`]; conversion to the domain spec
// attaches it to OCI rootfs.
type CloudRootfsSourceTypes string

const (
	// Use a host directory directly as the root filesystem.
	CloudRootfsSourceTypeVariantBind CloudRootfsSourceTypes = "bind"
	// Use an OCI image reference with an EROFS lower and ext4 overlay upper.
	CloudRootfsSourceTypeVariantOci CloudRootfsSourceTypes = "oci"
	// Use a disk image file as the root filesystem via virtio-blk.
	CloudRootfsSourceTypeVariantDiskImage CloudRootfsSourceTypes = "disk_image"
)

type CloudRootfsSource struct {
	Type CloudRootfsSourceTypes `json:"type"`
	data interface{}
}

func (c *CloudRootfsSource) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     CloudRootfsSourceTypes `json:"type"`
		Content json.RawMessage        `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	c.Type = enum.Tag
	switch c.Type {
	case CloudRootfsSourceTypeVariantBind:
		var res string
		c.data = &res
	case CloudRootfsSourceTypeVariantOci:
		var res CloudRootfsSourceOciInner
		c.data = &res
	case CloudRootfsSourceTypeVariantDiskImage:
		var res CloudRootfsSourceDiskImageInner
		c.data = &res

	}
	if err := json.Unmarshal(enum.Content, &c.data); err != nil {
		return err
	}

	return nil
}

func (c CloudRootfsSource) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     CloudRootfsSourceTypes `json:"type"`
		Content interface{}            `json:"data,omitempty"`
	}
	enum.Tag = c.Type
	enum.Content = c.data
	return json.Marshal(enum)
}

func (c CloudRootfsSource) Bind() string {
	res, _ := c.data.(*string)
	return *res
}
func (c CloudRootfsSource) Oci() *CloudRootfsSourceOciInner {
	res, _ := c.data.(*CloudRootfsSourceOciInner)
	return res
}
func (c CloudRootfsSource) DiskImage() *CloudRootfsSourceDiskImageInner {
	res, _ := c.data.(*CloudRootfsSourceDiskImageInner)
	return res
}

func NewCloudRootfsSourceTypeVariantBind(content string) CloudRootfsSource {
	return CloudRootfsSource{
		Type: CloudRootfsSourceTypeVariantBind,
		data: &content,
	}
}
func NewCloudRootfsSourceTypeVariantOci(content *CloudRootfsSourceOciInner) CloudRootfsSource {
	return CloudRootfsSource{
		Type: CloudRootfsSourceTypeVariantOci,
		data: content,
	}
}
func NewCloudRootfsSourceTypeVariantDiskImage(content *CloudRootfsSourceDiskImageInner) CloudRootfsSource {
	return CloudRootfsSource{
		Type: CloudRootfsSourceTypeVariantDiskImage,
		data: content,
	}
}

// Cloud resource request.
type CloudSandboxResources struct {
	// Number of virtual CPUs.
	Vcpus int `json:"vcpus"`
	// Guest memory in MiB.
	MemoryMib uint32 `json:"memory_mib"`
	// Writable disk size in MiB. Applies only to OCI root filesystems.
	DiskSizeMib *uint32 `json:"disk_size_mib,omitempty"`
}

// Runtime log verbosity for sandbox specs.
type SandboxLogLevel string

const (
	// Emit only error logs.
	SandboxLogLevelError SandboxLogLevel = "error"
	// Emit warning and error logs.
	SandboxLogLevelWarn SandboxLogLevel = "warn"
	// Emit info, warning, and error logs.
	SandboxLogLevelInfo SandboxLogLevel = "info"
	// Emit debug and higher-severity logs.
	SandboxLogLevelDebug SandboxLogLevel = "debug"
	// Emit trace and higher-severity logs.
	SandboxLogLevelTrace SandboxLogLevel = "trace"
)

// Guest runtime options for a sandbox.
type SandboxRuntimeOptions struct {
	// Working directory inside the guest.
	Workdir *string `json:"workdir,omitempty"`
	// Default shell for scripts and interactive sessions.
	Shell *string `json:"shell,omitempty"`
	// Named scripts available inside the guest.
	Scripts map[string]string `json:"scripts"`
	// Image entrypoint override.
	Entrypoint *[]string `json:"entrypoint,omitempty"`
	// Image command override.
	Cmd *[]string `json:"cmd,omitempty"`
	// Guest hostname override.
	Hostname *string `json:"hostname,omitempty"`
	// Guest user identity override.
	User *string `json:"user,omitempty"`
	// Runtime log verbosity.
	LogLevel *SandboxLogLevel `json:"log_level,omitempty"`
	// Metrics sampling interval in milliseconds. `None` disables sampling.
	MetricsSampleIntervalMs *uint64 `json:"metrics_sample_interval_ms,omitempty"`
	// Force-disable metrics sampling regardless of `metrics_sample_interval_ms`.
	DisableMetricsSample bool `json:"disable_metrics_sample"`
}

// Environment variable entry.
type EnvVar struct {
	// Environment variable name.
	Key string `json:"key"`
	// Environment variable value.
	Value string `json:"value"`
}

// POSIX resource limit identifiers.
type RlimitResource string

const (
	// Max CPU time in seconds (`RLIMIT_CPU`).
	RlimitResourceCpu RlimitResource = "cpu"
	// Max file size in bytes (`RLIMIT_FSIZE`).
	RlimitResourceFsize RlimitResource = "fsize"
	// Max data segment size (`RLIMIT_DATA`).
	RlimitResourceData RlimitResource = "data"
	// Max stack size (`RLIMIT_STACK`).
	RlimitResourceStack RlimitResource = "stack"
	// Max core file size (`RLIMIT_CORE`).
	RlimitResourceCore RlimitResource = "core"
	// Max resident set size (`RLIMIT_RSS`).
	RlimitResourceRss RlimitResource = "rss"
	// Max number of processes (`RLIMIT_NPROC`).
	RlimitResourceNproc RlimitResource = "nproc"
	// Max open file descriptors (`RLIMIT_NOFILE`).
	RlimitResourceNofile RlimitResource = "nofile"
	// Max locked memory (`RLIMIT_MEMLOCK`).
	RlimitResourceMemlock RlimitResource = "memlock"
	// Max address space size (`RLIMIT_AS`).
	RlimitResourceAs RlimitResource = "as"
	// Max file locks (`RLIMIT_LOCKS`).
	RlimitResourceLocks RlimitResource = "locks"
	// Max pending signals (`RLIMIT_SIGPENDING`).
	RlimitResourceSigpending RlimitResource = "sigpending"
	// Max bytes in POSIX message queues (`RLIMIT_MSGQUEUE`).
	RlimitResourceMsgqueue RlimitResource = "msgqueue"
	// Max nice priority (`RLIMIT_NICE`).
	RlimitResourceNice RlimitResource = "nice"
	// Max real-time priority (`RLIMIT_RTPRIO`).
	RlimitResourceRtprio RlimitResource = "rtprio"
	// Max real-time timeout (`RLIMIT_RTTIME`).
	RlimitResourceRttime RlimitResource = "rttime"
)

// A POSIX resource limit.
type Rlimit struct {
	// Resource type.
	Resource RlimitResource `json:"resource"`
	// Soft limit (can be raised up to hard limit by the process).
	Soft uint64 `json:"soft"`
	// Hard limit (ceiling, requires privileges to raise).
	Hard uint64 `json:"hard"`
}

// Generated type representing the anonymous struct variant `Bind` of the `VolumeMount` Rust enum
type VolumeMountBindInner struct {
	// Host path to bind mount.
	Host string `json:"host"`
	// Guest mount path.
	Guest string `json:"guest"`
	// Guest mount behavior.
	Options *MountOptions `json:"options,omitempty"`
	// Guest-visible stat virtualization policy.
	StatVirtualization StatVirtualization `json:"stat_virtualization"`
	// Host permission propagation policy.
	HostPermissions HostPermissions `json:"host_permissions"`
	// Guest-write byte budget in MiB.
	//
	// Bounds how much the guest may add beyond the directory's existing
	// contents. `None` applies the protective default at spawn time; set a
	// value to override it.
	QuotaMib *uint32 `json:"quota_mib,omitempty"`
}

// Generated type representing the anonymous struct variant `Named` of the `VolumeMount` Rust enum
type VolumeMountNamedInner struct {
	// Volume name.
	Name string `json:"name"`
	// Guest mount path.
	Guest string `json:"guest"`
	// Guest mount behavior.
	Options *MountOptions `json:"options,omitempty"`
	// Guest-visible stat virtualization policy.
	StatVirtualization StatVirtualization `json:"stat_virtualization"`
	// Host permission propagation policy.
	HostPermissions HostPermissions `json:"host_permissions"`
}

// Generated type representing the anonymous struct variant `Tmpfs` of the `VolumeMount` Rust enum
type VolumeMountTmpfsInner struct {
	// Guest mount path.
	Guest string `json:"guest"`
	// Size limit in MiB.
	SizeMib *uint32 `json:"size_mib,omitempty"`
	// Guest mount behavior.
	Options *MountOptions `json:"options,omitempty"`
}

// Generated type representing the anonymous struct variant `DiskImage` of the `VolumeMount` Rust enum
type VolumeMountDiskImageInner struct {
	// Host path to the disk image file.
	Host string `json:"host"`
	// Guest mount path.
	Guest string `json:"guest"`
	// Disk image format.
	Format DiskImageFormat `json:"format"`
	// Inner filesystem type. When `None`, agentd probes `/proc/filesystems`.
	Fstype *string `json:"fstype,omitempty"`
	// Guest mount behavior.
	Options *MountOptions `json:"options,omitempty"`
}

// A volume mount specification for a sandbox.
type VolumeMountTypes string

const (
	// Bind mount a host directory into the guest.
	VolumeMountTypeVariantBind VolumeMountTypes = "bind"
	// Mount a named volume into the guest.
	VolumeMountTypeVariantNamed VolumeMountTypes = "named"
	// Temporary filesystem backed by guest memory.
	VolumeMountTypeVariantTmpfs VolumeMountTypes = "tmpfs"
	// Mount a disk image file as a virtio-blk device at a guest path.
	VolumeMountTypeVariantDiskImage VolumeMountTypes = "disk_image"
)

type VolumeMount struct {
	Type VolumeMountTypes `json:"type"`
	data interface{}
}

func (v *VolumeMount) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     VolumeMountTypes `json:"type"`
		Content json.RawMessage  `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	v.Type = enum.Tag
	switch v.Type {
	case VolumeMountTypeVariantBind:
		var res VolumeMountBindInner
		v.data = &res
	case VolumeMountTypeVariantNamed:
		var res VolumeMountNamedInner
		v.data = &res
	case VolumeMountTypeVariantTmpfs:
		var res VolumeMountTmpfsInner
		v.data = &res
	case VolumeMountTypeVariantDiskImage:
		var res VolumeMountDiskImageInner
		v.data = &res

	}
	if err := json.Unmarshal(enum.Content, &v.data); err != nil {
		return err
	}

	return nil
}

func (v VolumeMount) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     VolumeMountTypes `json:"type"`
		Content interface{}      `json:"data,omitempty"`
	}
	enum.Tag = v.Type
	enum.Content = v.data
	return json.Marshal(enum)
}

func (v VolumeMount) Bind() *VolumeMountBindInner {
	res, _ := v.data.(*VolumeMountBindInner)
	return res
}
func (v VolumeMount) Named() *VolumeMountNamedInner {
	res, _ := v.data.(*VolumeMountNamedInner)
	return res
}
func (v VolumeMount) Tmpfs() *VolumeMountTmpfsInner {
	res, _ := v.data.(*VolumeMountTmpfsInner)
	return res
}
func (v VolumeMount) DiskImage() *VolumeMountDiskImageInner {
	res, _ := v.data.(*VolumeMountDiskImageInner)
	return res
}

func NewVolumeMountTypeVariantBind(content *VolumeMountBindInner) VolumeMount {
	return VolumeMount{
		Type: VolumeMountTypeVariantBind,
		data: content,
	}
}
func NewVolumeMountTypeVariantNamed(content *VolumeMountNamedInner) VolumeMount {
	return VolumeMount{
		Type: VolumeMountTypeVariantNamed,
		data: content,
	}
}
func NewVolumeMountTypeVariantTmpfs(content *VolumeMountTmpfsInner) VolumeMount {
	return VolumeMount{
		Type: VolumeMountTypeVariantTmpfs,
		data: content,
	}
}
func NewVolumeMountTypeVariantDiskImage(content *VolumeMountDiskImageInner) VolumeMount {
	return VolumeMount{
		Type: VolumeMountTypeVariantDiskImage,
		data: content,
	}
}

// Generated type representing the anonymous struct variant `Text` of the `Patch` Rust enum
type PatchTextInner struct {
	// Absolute guest path, such as `/etc/app.conf`.
	Path string `json:"path"`
	// Text content to write.
	Content string `json:"content"`
	// File permissions, such as `0o644`. `None` uses the default.
	Mode *uint32 `json:"mode,omitempty"`
	// Allow replacing a file that already exists in the rootfs.
	Replace bool `json:"replace"`
}

// Generated type representing the anonymous struct variant `File` of the `Patch` Rust enum
type PatchFileInner struct {
	// Absolute guest path.
	Path string `json:"path"`
	// Raw byte content to write.
	Content []int `json:"content"`
	// File permissions, such as `0o644`. `None` uses the default.
	Mode *uint32 `json:"mode,omitempty"`
	// Allow replacing a file that already exists in the rootfs.
	Replace bool `json:"replace"`
}

// Generated type representing the anonymous struct variant `CopyFile` of the `Patch` Rust enum
type PatchCopyFileInner struct {
	// Host path to copy from.
	Src string `json:"src"`
	// Absolute guest destination path.
	Dst string `json:"dst"`
	// File permissions. `None` preserves source permissions.
	Mode *uint32 `json:"mode,omitempty"`
	// Allow replacing a file that already exists in the rootfs.
	Replace bool `json:"replace"`
}

// Generated type representing the anonymous struct variant `CopyDir` of the `Patch` Rust enum
type PatchCopyDirInner struct {
	// Host directory to copy from.
	Src string `json:"src"`
	// Absolute guest destination path.
	Dst string `json:"dst"`
	// Allow replacing files that already exist in the rootfs.
	Replace bool `json:"replace"`
}

// Generated type representing the anonymous struct variant `Symlink` of the `Patch` Rust enum
type PatchSymlinkInner struct {
	// Symlink target path.
	Target string `json:"target"`
	// Absolute guest path where the symlink is created.
	Link string `json:"link"`
	// Allow replacing a path that already exists in the rootfs.
	Replace bool `json:"replace"`
}

// Generated type representing the anonymous struct variant `Mkdir` of the `Patch` Rust enum
type PatchMkdirInner struct {
	// Absolute guest path.
	Path string `json:"path"`
	// Directory permissions, such as `0o755`. `None` uses the default.
	Mode *uint32 `json:"mode,omitempty"`
}

// Generated type representing the anonymous struct variant `Remove` of the `Patch` Rust enum
type PatchRemoveInner struct {
	// Absolute guest path to remove.
	Path string `json:"path"`
}

// Generated type representing the anonymous struct variant `Append` of the `Patch` Rust enum
type PatchAppendInner struct {
	// Absolute guest path of the file to append to.
	Path string `json:"path"`
	// Content to append.
	Content string `json:"content"`
}

// Rootfs patch applied before VM startup.
type PatchTypes string

const (
	// Write text content to a file.
	PatchTypeVariantText PatchTypes = "text"
	// Write raw bytes to a file.
	PatchTypeVariantFile PatchTypes = "file"
	// Copy a file from the host into the rootfs.
	PatchTypeVariantCopyFile PatchTypes = "copy_file"
	// Copy a directory from the host into the rootfs.
	PatchTypeVariantCopyDir PatchTypes = "copy_dir"
	// Create a symlink.
	PatchTypeVariantSymlink PatchTypes = "symlink"
	// Create a directory.
	PatchTypeVariantMkdir PatchTypes = "mkdir"
	// Remove a file or directory.
	PatchTypeVariantRemove PatchTypes = "remove"
	// Append content to an existing file.
	PatchTypeVariantAppend PatchTypes = "append"
)

type Patch struct {
	Type PatchTypes `json:"type"`
	data interface{}
}

func (p *Patch) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     PatchTypes      `json:"type"`
		Content json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	p.Type = enum.Tag
	switch p.Type {
	case PatchTypeVariantText:
		var res PatchTextInner
		p.data = &res
	case PatchTypeVariantFile:
		var res PatchFileInner
		p.data = &res
	case PatchTypeVariantCopyFile:
		var res PatchCopyFileInner
		p.data = &res
	case PatchTypeVariantCopyDir:
		var res PatchCopyDirInner
		p.data = &res
	case PatchTypeVariantSymlink:
		var res PatchSymlinkInner
		p.data = &res
	case PatchTypeVariantMkdir:
		var res PatchMkdirInner
		p.data = &res
	case PatchTypeVariantRemove:
		var res PatchRemoveInner
		p.data = &res
	case PatchTypeVariantAppend:
		var res PatchAppendInner
		p.data = &res

	}
	if err := json.Unmarshal(enum.Content, &p.data); err != nil {
		return err
	}

	return nil
}

func (p Patch) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     PatchTypes  `json:"type"`
		Content interface{} `json:"data,omitempty"`
	}
	enum.Tag = p.Type
	enum.Content = p.data
	return json.Marshal(enum)
}

func (p Patch) Text() *PatchTextInner {
	res, _ := p.data.(*PatchTextInner)
	return res
}
func (p Patch) File() *PatchFileInner {
	res, _ := p.data.(*PatchFileInner)
	return res
}
func (p Patch) CopyFile() *PatchCopyFileInner {
	res, _ := p.data.(*PatchCopyFileInner)
	return res
}
func (p Patch) CopyDir() *PatchCopyDirInner {
	res, _ := p.data.(*PatchCopyDirInner)
	return res
}
func (p Patch) Symlink() *PatchSymlinkInner {
	res, _ := p.data.(*PatchSymlinkInner)
	return res
}
func (p Patch) Mkdir() *PatchMkdirInner {
	res, _ := p.data.(*PatchMkdirInner)
	return res
}
func (p Patch) Remove() *PatchRemoveInner {
	res, _ := p.data.(*PatchRemoveInner)
	return res
}
func (p Patch) Append() *PatchAppendInner {
	res, _ := p.data.(*PatchAppendInner)
	return res
}

func NewPatchTypeVariantText(content *PatchTextInner) Patch {
	return Patch{
		Type: PatchTypeVariantText,
		data: content,
	}
}
func NewPatchTypeVariantFile(content *PatchFileInner) Patch {
	return Patch{
		Type: PatchTypeVariantFile,
		data: content,
	}
}
func NewPatchTypeVariantCopyFile(content *PatchCopyFileInner) Patch {
	return Patch{
		Type: PatchTypeVariantCopyFile,
		data: content,
	}
}
func NewPatchTypeVariantCopyDir(content *PatchCopyDirInner) Patch {
	return Patch{
		Type: PatchTypeVariantCopyDir,
		data: content,
	}
}
func NewPatchTypeVariantSymlink(content *PatchSymlinkInner) Patch {
	return Patch{
		Type: PatchTypeVariantSymlink,
		data: content,
	}
}
func NewPatchTypeVariantMkdir(content *PatchMkdirInner) Patch {
	return Patch{
		Type: PatchTypeVariantMkdir,
		data: content,
	}
}
func NewPatchTypeVariantRemove(content *PatchRemoveInner) Patch {
	return Patch{
		Type: PatchTypeVariantRemove,
		data: content,
	}
}
func NewPatchTypeVariantAppend(content *PatchAppendInner) Patch {
	return Patch{
		Type: PatchTypeVariantAppend,
		data: content,
	}
}

// Optional guest interface overrides. Unset fields are derived from the
// sandbox slot by the local network engine. Carried in
// [`NetworkSpec::interface`].
type InterfaceOverrides struct {
	// Guest MAC address as six octets. Default: derived from slot.
	Mac *[]uint64 `json:"mac,omitempty"`
	// Interface MTU. Default: 1500.
	Mtu *int `json:"mtu,omitempty"`
	// Guest IPv4 address (e.g. `172.16.0.2`). Default: derived from slot.
	Ipv4Address *string `json:"ipv4_address,omitempty"`
	// Guest IPv4 pool CIDR (e.g. `"172.16.0.0/12"`). Default: derived from slot.
	Ipv4Pool *string `json:"ipv4_pool,omitempty"`
	// Guest IPv6 address. Default: derived from slot.
	Ipv6Address *string `json:"ipv6_address,omitempty"`
	// Guest IPv6 pool CIDR. Default: derived from slot.
	Ipv6Pool *string `json:"ipv6_pool,omitempty"`
}

// Transport protocol for a published port.
type PortProtocol string

const (
	// TCP.
	PortProtocolTcp PortProtocol = "tcp"
	// UDP.
	PortProtocolUdp PortProtocol = "udp"
)

// A published port mapping between host and guest.
type PublishedPortSpec struct {
	// Host-side port to bind.
	HostPort int `json:"host_port"`
	// Guest-side port to forward to.
	GuestPort int `json:"guest_port"`
	// Transport protocol.
	Protocol *PortProtocol `json:"protocol,omitempty"`
	// Host address to bind. Defaults to loopback.
	HostBind string `json:"host_bind"`
}

// Action to take on traffic matched by a [`Rule`] (or a policy default).
type Action string

const (
	// Allow the traffic.
	ActionAllow Action = "allow"
	// Silently drop the traffic.
	ActionDeny Action = "deny"
)

// Direction a [`Rule`] applies to.
type Direction string

const (
	// Outbound: guest → destination.
	DirectionEgress Direction = "egress"
	// Inbound: peer → guest.
	DirectionIngress Direction = "ingress"
	// Either direction.
	DirectionAny Direction = "any"
)

// Traffic destination filter for a [`Rule`].
//
// The `Cidr`, `Domain`, and `DomainSuffix` leaves carry their canonical
// string form (e.g. `"10.0.0.0/8"`, `"example.com"`); the local network
// engine re-parses and validates them into its richer internal types at
// load time.
type DestinationTypes string

const (
	// Match any destination.
	DestinationTypeVariantAny DestinationTypes = "any"
	// IP address or CIDR block (e.g. `"1.2.3.4"`, `"10.0.0.0/8"`).
	DestinationTypeVariantCidr DestinationTypes = "cidr"
	// Exact domain name (e.g. `"example.com"`).
	DestinationTypeVariantDomain DestinationTypes = "domain"
	// Domain suffix — the apex and any subdomain of it.
	DestinationTypeVariantDomainSuffix DestinationTypes = "domain_suffix"
	// A pre-defined destination group.
	DestinationTypeVariantGroup DestinationTypes = "group"
)

type Destination struct {
	Type DestinationTypes `json:"type"`
	data interface{}
}

func (d *Destination) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     DestinationTypes `json:"type"`
		Content json.RawMessage  `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	d.Type = enum.Tag
	switch d.Type {
	case DestinationTypeVariantAny:
		return nil
	case DestinationTypeVariantCidr:
		var res string
		d.data = &res
	case DestinationTypeVariantDomain:
		var res string
		d.data = &res
	case DestinationTypeVariantDomainSuffix:
		var res string
		d.data = &res
	case DestinationTypeVariantGroup:
		var res DestinationGroup
		d.data = &res

	}
	if err := json.Unmarshal(enum.Content, &d.data); err != nil {
		return err
	}

	return nil
}

func (d Destination) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     DestinationTypes `json:"type"`
		Content interface{}      `json:"data,omitempty"`
	}
	enum.Tag = d.Type
	enum.Content = d.data
	return json.Marshal(enum)
}

func (d Destination) Cidr() string {
	res, _ := d.data.(*string)
	return *res
}
func (d Destination) Domain() string {
	res, _ := d.data.(*string)
	return *res
}
func (d Destination) DomainSuffix() string {
	res, _ := d.data.(*string)
	return *res
}
func (d Destination) Group() DestinationGroup {
	res, _ := d.data.(*DestinationGroup)
	return *res
}

func NewDestinationTypeVariantAny() Destination {
	return Destination{
		Type: DestinationTypeVariantAny,
	}
}
func NewDestinationTypeVariantCidr(content string) Destination {
	return Destination{
		Type: DestinationTypeVariantCidr,
		data: &content,
	}
}
func NewDestinationTypeVariantDomain(content string) Destination {
	return Destination{
		Type: DestinationTypeVariantDomain,
		data: &content,
	}
}
func NewDestinationTypeVariantDomainSuffix(content string) Destination {
	return Destination{
		Type: DestinationTypeVariantDomainSuffix,
		data: &content,
	}
}
func NewDestinationTypeVariantGroup(content DestinationGroup) Destination {
	return Destination{
		Type: DestinationTypeVariantGroup,
		data: &content,
	}
}

// Protocol filter for a [`Rule`].
type Protocol string

const (
	// TCP.
	ProtocolTcp Protocol = "tcp"
	// UDP.
	ProtocolUdp Protocol = "udp"
	// ICMPv4.
	ProtocolIcmpv4 Protocol = "icmpv4"
	// ICMPv6.
	ProtocolIcmpv6 Protocol = "icmpv6"
)

// Inclusive guest-side port range for a [`Rule`] match.
type PortRange struct {
	// Start port (inclusive).
	Start int `json:"start"`
	// End port (inclusive).
	End int `json:"end"`
}

// A single egress/ingress policy rule. Evaluated first-match-wins per
// direction.
type Rule struct {
	// Direction this rule applies to.
	Direction Direction `json:"direction"`
	// Destination filter (direction-dependent interpretation).
	Destination Destination `json:"destination"`
	// Protocol set; empty matches any protocol.
	Protocols *[]Protocol `json:"protocols,omitempty"`
	// Guest-side port-range set; empty matches any port.
	Ports *[]PortRange `json:"ports,omitempty"`
	// Action to take on a match.
	Action Action `json:"action"`
}

// Egress/ingress network policy: an ordered [`Rule`] list plus a
// per-direction default [`Action`]. Carried in [`NetworkSpec::policy`].
type NetworkPolicy struct {
	// Default action for egress traffic matching no rule. Default: `Deny`.
	DefaultEgress Action `json:"default_egress"`
	// Default action for ingress traffic matching no rule. Default: `Deny`.
	DefaultIngress Action `json:"default_ingress"`
	// Ordered rules, evaluated first-match-wins per direction.
	Rules *[]Rule `json:"rules,omitempty"`
}

// DNS interception and filtering settings. Carried in [`NetworkSpec::dns`].
type DnsConfig struct {
	// Whether DNS-rebinding protection is enabled. Default: true.
	RebindProtection bool `json:"rebind_protection"`
	// Upstream nameservers as `IP`, `IP:PORT`, `HOST`, or `HOST:PORT`
	// strings. Empty falls back to the host's `/etc/resolv.conf`.
	Nameservers []string `json:"nameservers"`
	// Per-query timeout in milliseconds. Default: 5000.
	QueryTimeoutMs uint64 `json:"query_timeout_ms"`
}

// A CA certificate PEM file trusted only for matching upstream hosts.
type ScopedUpstreamCaCert struct {
	// Host pattern this CA applies to. Supports exact hosts and `*.suffix` wildcards.
	Pattern string `json:"pattern"`
	// Path to the CA certificate PEM file.
	Path string `json:"path"`
}

// An upstream certificate verification override for matching hosts.
type ScopedVerifyUpstream struct {
	// Host pattern this override applies to. Supports exact hosts and `*.suffix` wildcards.
	Pattern string `json:"pattern"`
	// Whether to verify matching upstream server certificates.
	Verify bool `json:"verify"`
}

// Certificate authority configuration for TLS interception.
type InterceptCaConfig struct {
	// Path to an existing CA certificate PEM file. If `None`, a CA is
	// auto-generated and persisted.
	CertPath *string `json:"cert_path,omitempty"`
	// Path to an existing CA private key PEM file. If `None`, a key is
	// auto-generated and persisted.
	KeyPath *string `json:"key_path,omitempty"`
}

// TLS interception configuration. Carried in [`NetworkSpec::tls`](NetworkSpec).
//
// The local network engine terminates TCP at its in-process stack, so TLS MITM
// is handled by proxy tasks — these fields configure which ports/domains are
// intercepted and how the interception CA is sourced.
type TlsConfig struct {
	// Whether TLS interception is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// TCP ports subject to TLS interception (default: `[443]`).
	InterceptedPorts []int `json:"intercepted_ports"`
	// Domains to bypass (no MITM). Supports exact match and `*.suffix` wildcards.
	Bypass *[]string `json:"bypass,omitempty"`
	// Whether to verify the upstream server's TLS certificate.
	VerifyUpstream bool `json:"verify_upstream"`
	// Drop UDP to intercepted ports when TLS interception is active, forcing
	// QUIC traffic to fall back to TCP/TLS.
	BlockQuicOnIntercept bool `json:"block_quic_on_intercept"`
	// CA certificate PEM files to trust for upstream server verification.
	UpstreamCaCert *[]string `json:"upstream_ca_cert,omitempty"`
	// Host-scoped CA certificate PEM files to trust for upstream server verification.
	ScopedUpstreamCaCert *[]ScopedUpstreamCaCert `json:"scoped_upstream_ca_cert,omitempty"`
	// Host-scoped upstream verification overrides.
	ScopedVerifyUpstream *[]ScopedVerifyUpstream `json:"scoped_verify_upstream,omitempty"`
	// Interception CA configuration. The TLS proxy uses this CA to sign
	// per-domain certs it presents to the guest during interception.
	InterceptCa *InterceptCaConfig `json:"intercept_ca,omitempty"`
	// Per-domain certificate cache configuration.
	Cache *CertCacheConfig `json:"cache,omitempty"`
}

// Host pattern for a secret allowlist.
type HostPatternTypes string

const (
	// Exact hostname match.
	HostPatternTypeVariantExact HostPatternTypes = "exact"
	// Wildcard match (e.g., `*.openai.com`).
	HostPatternTypeVariantWildcard HostPatternTypes = "wildcard"
	// Any host (dangerous — secret can be exfiltrated).
	HostPatternTypeVariantAny HostPatternTypes = "any"
)

type HostPattern struct {
	Type HostPatternTypes `json:"type"`
	data interface{}
}

func (h *HostPattern) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     HostPatternTypes `json:"type"`
		Content json.RawMessage  `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	h.Type = enum.Tag
	switch h.Type {
	case HostPatternTypeVariantExact:
		var res string
		h.data = &res
	case HostPatternTypeVariantWildcard:
		var res string
		h.data = &res
	case HostPatternTypeVariantAny:
		return nil

	}
	if err := json.Unmarshal(enum.Content, &h.data); err != nil {
		return err
	}

	return nil
}

func (h HostPattern) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     HostPatternTypes `json:"type"`
		Content interface{}      `json:"data,omitempty"`
	}
	enum.Tag = h.Type
	enum.Content = h.data
	return json.Marshal(enum)
}

func (h HostPattern) Exact() string {
	res, _ := h.data.(*string)
	return *res
}
func (h HostPattern) Wildcard() string {
	res, _ := h.data.(*string)
	return *res
}

func NewHostPatternTypeVariantExact(content string) HostPattern {
	return HostPattern{
		Type: HostPatternTypeVariantExact,
		data: &content,
	}
}
func NewHostPatternTypeVariantWildcard(content string) HostPattern {
	return HostPattern{
		Type: HostPatternTypeVariantWildcard,
		data: &content,
	}
}
func NewHostPatternTypeVariantAny() HostPattern {
	return HostPattern{
		Type: HostPatternTypeVariantAny,
	}
}

// Where in the HTTP request a secret can be injected.
type SecretInjection struct {
	// Substitute in HTTP headers (default: true).
	Headers bool `json:"headers"`
	// Substitute in HTTP Basic Auth (default: true).
	BasicAuth bool `json:"basic_auth"`
	// Substitute in URL query parameters (default: false).
	QueryParams *bool `json:"query_params,omitempty"`
	// Substitute in request body (default: false).
	//
	// Fixed-length HTTP/1 bodies up to 16 MiB update `Content-Length`;
	// larger fixed-length bodies are blocked. Chunked HTTP/1 bodies are
	// decoded and re-encoded with fresh chunk sizes. Encoded bodies pass
	// through unchanged. HTTP/2 DATA-frame body substitution is not
	// supported; matching body placeholders are blocked.
	Body *bool `json:"body,omitempty"`
}

// Action when a secret placeholder is detected going to a disallowed host.
type ViolationActionTypes string

const (
	// Block the request silently.
	ViolationActionTypeVariantBlock ViolationActionTypes = "block"
	// Block and log (default).
	ViolationActionTypeVariantBlockAndLog ViolationActionTypes = "block_and_log"
	// Block and terminate the sandbox.
	ViolationActionTypeVariantBlockAndTerminate ViolationActionTypes = "block_and_terminate"
	// Forward the request with the placeholder unchanged for matching hosts.
	ViolationActionTypeVariantPassthrough ViolationActionTypes = "passthrough"
)

type ViolationAction struct {
	Type ViolationActionTypes `json:"type"`
	data interface{}
}

func (v *ViolationAction) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     ViolationActionTypes `json:"type"`
		Content json.RawMessage      `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	v.Type = enum.Tag
	switch v.Type {
	case ViolationActionTypeVariantBlock:
		return nil
	case ViolationActionTypeVariantBlockAndLog:
		return nil
	case ViolationActionTypeVariantBlockAndTerminate:
		return nil
	case ViolationActionTypeVariantPassthrough:
		var res []HostPattern
		v.data = &res

	}
	if err := json.Unmarshal(enum.Content, &v.data); err != nil {
		return err
	}

	return nil
}

func (v ViolationAction) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     ViolationActionTypes `json:"type"`
		Content interface{}          `json:"data,omitempty"`
	}
	enum.Tag = v.Type
	enum.Content = v.data
	return json.Marshal(enum)
}

func (v ViolationAction) Passthrough() []HostPattern {
	res, _ := v.data.(*[]HostPattern)
	return *res
}

func NewViolationActionTypeVariantBlock() ViolationAction {
	return ViolationAction{
		Type: ViolationActionTypeVariantBlock,
	}
}
func NewViolationActionTypeVariantBlockAndLog() ViolationAction {
	return ViolationAction{
		Type: ViolationActionTypeVariantBlockAndLog,
	}
}
func NewViolationActionTypeVariantBlockAndTerminate() ViolationAction {
	return ViolationAction{
		Type: ViolationActionTypeVariantBlockAndTerminate,
	}
}
func NewViolationActionTypeVariantPassthrough(content []HostPattern) ViolationAction {
	return ViolationAction{
		Type: ViolationActionTypeVariantPassthrough,
		data: &content,
	}
}

// A single secret entry.
//
// `value` is the sensitive material — it never enters the sandbox and is
// redacted by the [`Debug`](fmt::Debug) impl.
type SecretEntry struct {
	// Environment variable name exposed to the sandbox (holds the placeholder).
	//
	// Must be non-empty and must not contain `=` or NUL. microsandbox does
	// not require shell-identifier syntax because Linux environment entries
	// only require a `NAME=value` shape.
	EnvVar string `json:"env_var"`
	// The actual secret value (never enters the sandbox).
	Value string `json:"value"`
	// Placeholder string the sandbox sees instead of the real value.
	//
	// Must be non-empty, no longer than [`MAX_SECRET_PLACEHOLDER_BYTES`], and
	// must not contain NUL, CR, or LF.
	Placeholder string `json:"placeholder"`
	// Hosts allowed to receive this secret.
	AllowedHosts *[]HostPattern `json:"allowed_hosts,omitempty"`
	// Where the secret can be injected.
	Injection *SecretInjection `json:"injection,omitempty"`
	// Action on a violation for this secret (overrides the config default).
	OnViolation *ViolationAction `json:"on_violation,omitempty"`
	// Require verified TLS identity before substituting (default: true).
	//
	// When true, the secret is only substituted if the connection uses TLS
	// interception (not bypass) and the SNI matches an allowed host.
	RequireTlsIdentity bool `json:"require_tls_identity"`
}

// Placeholder-based secret injection for a sandbox's TLS-intercepted egress.
//
// The sandbox only ever sees each secret's `placeholder`; the local network
// engine substitutes the real `value` into outbound requests bound for an
// allowed host (and blocks/forwards per [`ViolationAction`] otherwise). Carried
// in [`NetworkSpec::secrets`](NetworkSpec).
type SecretsConfig struct {
	// List of secrets to inject.
	Entries *[]SecretEntry `json:"entries,omitempty"`
	// Default action when a placeholder leaks to a disallowed host.
	OnViolation *ViolationAction `json:"on_violation,omitempty"`
}

// Complete network specification for a sandbox.
//
// All subdocuments are typed. The local-engine `policy`, `dns`, and
// `interface` configs are mirrored here as wire types whose leaf values
// (CIDRs, domain names, nameservers) are carried in their canonical string
// form; the network engine re-parses these into its richer internal types at
// load time, which keeps that engine's validation crates out of this shared
// contract.
type NetworkSpec struct {
	// Whether networking is enabled for this sandbox.
	Enabled bool `json:"enabled"`
	// Guest interface overrides for the local network engine.
	Interface *InterfaceOverrides `json:"interface,omitempty"`
	// Host-to-guest port mappings.
	Ports []PublishedPortSpec `json:"ports"`
	// Egress and ingress policy.
	Policy *NetworkPolicy `json:"policy,omitempty"`
	// DNS interception and filtering.
	Dns *DnsConfig `json:"dns,omitempty"`
	// TLS-interception subdocument (see [`TlsConfig`]).
	Tls *TlsConfig `json:"tls,omitempty"`
	// Placeholder-based secret-injection subdocument (see [`SecretsConfig`]).
	Secrets *SecretsConfig `json:"secrets,omitempty"`
	// Max concurrent guest connections.
	MaxConnections *uint64 `json:"max_connections,omitempty"`
	// Whether to copy trusted host CAs into the guest at boot.
	TrustHostCas bool `json:"trust_host_cas"`
}

// Fully-assembled handoff-init specification.
type HandoffInit struct {
	// Init binary: absolute path inside the guest rootfs, or the literal `auto`.
	Cmd string `json:"cmd"`
	// Supplemental argv. `argv[0]` is implicitly `cmd`.
	Args *[]string `json:"args,omitempty"`
	// Extra env vars merged on top of the inherited env.
	Env *[][]string `json:"env,omitempty"`
}

// Controls when an OCI registry is contacted for manifest freshness.
type PullPolicy string

const (
	// Use cached layers if complete, pull otherwise.
	PullPolicyIfMissing PullPolicy = "if_missing"
	// Always fetch the manifest from the registry, reusing cached layers whose digests still match.
	PullPolicyAlways PullPolicy = "always"
	// Never contact the registry. Error if the image is not fully cached locally.
	PullPolicyNever PullPolicy = "never"
)

// Sandbox-level in-guest security profile.
type SecurityProfile string

const (
	// Preserve normal guest-root semantics.
	//
	// Exec sessions do not set `no_new_privs` and keep `CAP_SYS_ADMIN`, so workflows such as `sudo`, package managers, and Docker-in-Docker work as they would in a regular VM.
	SecurityProfileDefault SecurityProfile = "default"
	// Harden guest exec sessions.
	//
	// Agentd sets `no_new_privs`, drops `CAP_SYS_ADMIN`, and forces `nosuid,nodev` on user mounts. Workloads that need privilege elevation or guest mount administration, such as `sudo` and Docker-in-Docker, are intentionally incompatible with this profile.
	SecurityProfileRestricted SecurityProfile = "restricted"
)

// Sandbox lifecycle policy.
type SandboxPolicy struct {
	// Whether the sandbox is ephemeral.
	//
	// Ephemeral sandboxes are one-off: the host runtime that owns the
	// process removes the persisted DB row and on-disk state when the VM
	// reaches a terminal status, and other host runtimes opportunistically
	// clean up ephemeral leftovers from runtimes that died before they
	// could self-clean. Defaults to `false` (persistent); named and created
	// sandboxes stay inspectable and restartable after they stop.
	Ephemeral *bool `json:"ephemeral,omitempty"`
	// Hard cap on total sandbox lifetime in seconds. `None` = run forever.
	MaxDurationSecs *uint64 `json:"max_duration_secs,omitempty"`
	// Idle timeout in seconds. `None` = no idle detection.
	IdleTimeoutSecs *uint64 `json:"idle_timeout_secs,omitempty"`
}

// Cloud sandbox specification carried on create routes.
type CloudSandboxSpec struct {
	// Unique sandbox name.
	Name string `json:"name"`
	// Root filesystem source.
	Image CloudRootfsSource `json:"image"`
	// CPU, memory, and user-facing disk resources.
	Resources CloudSandboxResources `json:"resources"`
	// Guest runtime options.
	Runtime SandboxRuntimeOptions `json:"runtime"`
	// Environment variables visible to commands in the sandbox.
	Env []EnvVar `json:"env"`
	// User-defined labels attached to the sandbox.
	Labels map[string]string `json:"labels"`
	// Sandbox-wide resource limits inherited by guest processes.
	Rlimits []Rlimit `json:"rlimits"`
	// Volume mounts.
	Mounts []VolumeMount `json:"mounts"`
	// Rootfs patches applied before VM start.
	Patches []Patch `json:"patches"`
	// Network specification.
	Network NetworkSpec `json:"network"`
	// Hand off PID 1 to a guest init binary after agentd setup.
	Init *HandoffInit `json:"init,omitempty"`
	// Pull policy for OCI images.
	PullPolicy PullPolicy `json:"pull_policy"`
	// In-guest security profile.
	SecurityProfile SecurityProfile `json:"security_profile"`
	// Sandbox lifecycle policy.
	Lifecycle SandboxPolicy `json:"lifecycle"`
}

// Wire shape of the cloud sandbox response returned by sandbox endpoints.
type CloudCreateSandboxResponse struct {
	// Server-side UUID.
	Id string `json:"id"`
	// Owning org's UUID.
	OrgId string `json:"org_id"`
	// User-facing, per-org sandbox name.
	Name string `json:"name"`
	// Canonical, resolved SSH username token.
	Slug string `json:"slug"`
	// Current lifecycle status.
	Status CloudSandboxStatus `json:"status"`
	// The sandbox spec the cloud control plane stored for this sandbox.
	Spec CloudSandboxSpec `json:"spec"`
	// Whether the sandbox should be removed when its allocation terminates.
	Ephemeral bool `json:"ephemeral"`
	// Creation timestamp.
	CreatedAt string `json:"created_at"`
	// Last start timestamp, when known.
	StartedAt *string `json:"started_at,omitempty"`
	// Last stop timestamp, when known.
	StoppedAt *string `json:"stopped_at,omitempty"`
	// Last failure reason, when any.
	LastError *string `json:"last_error,omitempty"`
}

// Nested cloud API error details.
type CloudErrorDetails struct {
	// Machine-readable error code.
	Code *string `json:"code,omitempty"`
	// Human-readable error message.
	Message *string `json:"message,omitempty"`
}

// Wire shape of the typed error body returned by cloud APIs on 4xx/5xx responses.
type CloudErrorBody struct {
	// Flat machine-readable error code, when returned in this shape.
	Code *string `json:"code,omitempty"`
	// Flat human-readable error message, when returned in this shape.
	Message *string `json:"message,omitempty"`
	// Nested error object returned by the API error responder.
	Error *CloudErrorDetails `json:"error,omitempty"`
}

// Wire shape of the message response returned by mutation endpoints.
type CloudMessageResponse struct {
	// Human-readable response message.
	Message string `json:"message"`
}

// Wire shape of paginated list responses.
type CloudPaginated[T any] struct {
	// Page of response items.
	Data []T `json:"data"`
	// Cursor for the next page, when one exists.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Guest mount behavior shared by every volume mount kind.
type MountOptions struct {
	// Whether the mount is read-only.
	//
	// Guest writes fail with the kernel's read-only filesystem behavior. Virtiofs-backed mounts also reject writes on the host-side filesystem server as defense in depth.
	Readonly bool `json:"readonly"`
	// Whether direct execution from the mount is disabled.
	//
	// This prevents `execve` of binaries or scripts located on the mount. Interpreters can still read files from the mount, for example `sh /mnt/script.sh`, because the interpreter itself executes from a different filesystem.
	Noexec bool `json:"noexec"`
	// Whether setuid and setgid privilege elevation from files on the mount is ignored.
	Nosuid bool `json:"nosuid"`
	// Whether device files on the mount are ignored.
	Nodev bool `json:"nodev"`
}

// Sandbox-time behavior for a named volume mount.
type NamedVolumeMode string

const (
	// Require the named volume to already exist.
	NamedVolumeModeExisting NamedVolumeMode = "existing"
	// Create the named volume and fail if it already exists.
	NamedVolumeModeCreate NamedVolumeMode = "create"
	// Ensure the named volume exists, or reuse a compatible existing volume.
	NamedVolumeModeEnsureExists NamedVolumeMode = "ensure_exists"
)

// Storage kind for a named volume.
type VolumeKind string

const (
	// Directory-backed named volume mounted through virtiofs.
	VolumeKindDirectory VolumeKind = "directory"
	// Raw ext4 disk-image named volume mounted through virtio-blk.
	VolumeKindDisk VolumeKind = "disk"
)

// Creation metadata for sandbox-time named volume provisioning.
type NamedVolumeCreate struct {
	// Creation behavior for this named volume mount.
	Mode NamedVolumeMode `json:"mode"`
	// Volume name to create or ensure exists.
	Name string `json:"name"`
	// Storage kind to create or ensure exists.
	Kind VolumeKind `json:"kind"`
	// Directory quota in MiB, if configured.
	QuotaMib *uint32 `json:"quota_mib,omitempty"`
	// Disk capacity in MiB, if configured.
	CapacityMib *uint32 `json:"capacity_mib,omitempty"`
	// Labels to attach to newly-created volumes.
	Labels [][]string `json:"labels"`
}

// OCI root filesystem source.
type OciRootfsSource struct {
	// OCI image reference (e.g. `python`).
	Reference string `json:"reference"`
	// Writable overlay upper size in MiB.
	UpperSizeMib *uint32 `json:"upper_size_mib,omitempty"`
}

// CPU and memory resources for a sandbox.
type SandboxResources struct {
	// Number of virtual CPUs.
	Vcpus int `json:"vcpus"`
	// Guest memory in MiB.
	MemoryMib uint32 `json:"memory_mib"`
}

// Generated type representing the anonymous struct variant `DiskImage` of the `RootfsSource` Rust enum
type RootfsSourceDiskImageInner struct {
	// Path to the disk image file on the host.
	Path string `json:"path"`
	// Disk image format.
	Format DiskImageFormat `json:"format"`
	// Inner filesystem type (optional; auto-detected if absent).
	Fstype *string `json:"fstype,omitempty"`
}

// Root filesystem source for a sandbox.
type RootfsSourceTypes string

const (
	// Use a host directory directly as the root filesystem.
	RootfsSourceTypeVariantBind RootfsSourceTypes = "bind"
	// Use an OCI image reference with an EROFS lower and ext4 overlay upper.
	RootfsSourceTypeVariantOci RootfsSourceTypes = "oci"
	// Use a disk image file as the root filesystem via virtio-blk.
	RootfsSourceTypeVariantDiskImage RootfsSourceTypes = "disk_image"
)

type RootfsSource struct {
	Type RootfsSourceTypes `json:"type"`
	data interface{}
}

func (r *RootfsSource) UnmarshalJSON(data []byte) error {
	var enum struct {
		Tag     RootfsSourceTypes `json:"type"`
		Content json.RawMessage   `json:"data"`
	}
	if err := json.Unmarshal(data, &enum); err != nil {
		return err
	}

	r.Type = enum.Tag
	switch r.Type {
	case RootfsSourceTypeVariantBind:
		var res string
		r.data = &res
	case RootfsSourceTypeVariantOci:
		var res OciRootfsSource
		r.data = &res
	case RootfsSourceTypeVariantDiskImage:
		var res RootfsSourceDiskImageInner
		r.data = &res

	}
	if err := json.Unmarshal(enum.Content, &r.data); err != nil {
		return err
	}

	return nil
}

func (r RootfsSource) MarshalJSON() ([]byte, error) {
	var enum struct {
		Tag     RootfsSourceTypes `json:"type"`
		Content interface{}       `json:"data,omitempty"`
	}
	enum.Tag = r.Type
	enum.Content = r.data
	return json.Marshal(enum)
}

func (r RootfsSource) Bind() string {
	res, _ := r.data.(*string)
	return *res
}
func (r RootfsSource) Oci() *OciRootfsSource {
	res, _ := r.data.(*OciRootfsSource)
	return res
}
func (r RootfsSource) DiskImage() *RootfsSourceDiskImageInner {
	res, _ := r.data.(*RootfsSourceDiskImageInner)
	return res
}

func NewRootfsSourceTypeVariantBind(content string) RootfsSource {
	return RootfsSource{
		Type: RootfsSourceTypeVariantBind,
		data: &content,
	}
}
func NewRootfsSourceTypeVariantOci(content *OciRootfsSource) RootfsSource {
	return RootfsSource{
		Type: RootfsSourceTypeVariantOci,
		data: content,
	}
}
func NewRootfsSourceTypeVariantDiskImage(content *RootfsSourceDiskImageInner) RootfsSource {
	return RootfsSource{
		Type: RootfsSourceTypeVariantDiskImage,
		data: content,
	}
}

// Backend-neutral sandbox task description.
//
// This is the durable contract for fields that are already shared across backends. Local-only execution state such as resolved manifest digests, snapshot upper-layer paths, registry credentials, replace flags, and backend dispatch stays outside this type.
type SandboxSpec struct {
	// Unique sandbox name.
	Name string `json:"name"`
	// Root filesystem source.
	Image RootfsSource `json:"image"`
	// CPU and memory resources.
	Resources SandboxResources `json:"resources"`
	// Guest runtime options.
	Runtime SandboxRuntimeOptions `json:"runtime"`
	// Environment variables visible to commands in the sandbox.
	Env []EnvVar `json:"env"`
	// User-defined labels attached to the sandbox.
	Labels map[string]string `json:"labels"`
	// Sandbox-wide resource limits inherited by guest processes.
	Rlimits []Rlimit `json:"rlimits"`
	// Volume mounts.
	Mounts []VolumeMount `json:"mounts"`
	// Rootfs patches applied before VM start.
	Patches []Patch `json:"patches"`
	// Network specification.
	Network NetworkSpec `json:"network"`
	// Hand off PID 1 to a guest init binary after agentd setup.
	Init *HandoffInit `json:"init,omitempty"`
	// Pull policy for OCI images.
	PullPolicy PullPolicy `json:"pull_policy"`
	// In-guest security profile.
	SecurityProfile SecurityProfile `json:"security_profile"`
	// Sandbox lifecycle policy.
	Lifecycle SandboxPolicy `json:"lifecycle"`
}

// Configuration for creating a named volume.
type VolumeSpec struct {
	// Volume name.
	Name string `json:"name"`
	// Storage kind.
	Kind VolumeKind `json:"kind"`
	// Size quota in MiB. `None` means unlimited.
	QuotaMib *uint32 `json:"quota_mib,omitempty"`
	// Disk capacity in MiB. Required for disk volumes.
	CapacityMib *uint32 `json:"capacity_mib,omitempty"`
	// Labels for organization.
	Labels [][]string `json:"labels"`
}

// Pre-defined destination category for a [`Destination::Group`] match.
type DestinationGroup string

const (
	// Public internet — any address not in another category.
	DestinationGroupPublic DestinationGroup = "public"
	// Loopback addresses (`127.0.0.0/8`, `::1`).
	DestinationGroupLoopback DestinationGroup = "loopback"
	// Private ranges (RFC 1918 / RFC 4193 ULA / CGN).
	DestinationGroupPrivate DestinationGroup = "private"
	// Link-local addresses, excluding the metadata IP.
	DestinationGroupLinkLocal DestinationGroup = "link_local"
	// Cloud metadata endpoint (`169.254.169.254`).
	DestinationGroupMetadata DestinationGroup = "metadata"
	// Multicast addresses (`224.0.0.0/4`, `ff00::/8`).
	DestinationGroupMulticast DestinationGroup = "multicast"
	// The sandbox host, reachable via the gateway IP.
	DestinationGroupHost DestinationGroup = "host"
)

// Disk image format for virtio-blk root filesystems and volume mounts.
type DiskImageFormat string

const (
	// QEMU Copy-on-Write v2.
	DiskImageFormatQcow2 DiskImageFormat = "qcow2"
	// Raw disk image.
	DiskImageFormatRaw DiskImageFormat = "raw"
	// VMware Disk (FLAT/ZERO only, no delta links).
	DiskImageFormatVmdk DiskImageFormat = "vmdk"
)

// Host permission propagation policy for a virtiofs-backed volume mount.
//
// Serializes/deserializes as the lowercase variant name (`"private"`, `"mirror"`) to align with the CLI and NAPI spellings.
type HostPermissions string

const (
	// Guest chmod stays in the metadata overlay only.
	HostPermissionsPrivate HostPermissions = "private"
	// Mirror ordinary rwx bits for regular files and directories to the host inode.
	HostPermissionsMirror HostPermissions = "mirror"
)

// Stat virtualization policy for a virtiofs-backed volume mount.
//
// Serializes/deserializes as the lowercase variant name (`"strict"`, `"relaxed"`, `"off"`) so persisted JSON aligns with the CLI grammar (`stat-virt=strict|relaxed|off`) and the NAPI string contract.
type StatVirtualization string

const (
	// Fail-closed: probe the host backing path; require xattr support.
	StatVirtualizationStrict StatVirtualization = "strict"
	// Opportunistic: apply the overlay when present; tolerate missing xattr support.
	StatVirtualizationRelaxed StatVirtualization = "relaxed"
	// Literal host metadata: do not read or apply the override xattr.
	StatVirtualizationOff StatVirtualization = "off"
)
