// @generated by microsandbox-types. Do not edit by hand.

export type DiskImageFormat = "Qcow2" | "Raw" | "Vmdk";

export interface OciRootfsSource {
  reference: string;
  upper_size_mib?: number | null;
}

export type RootfsSource =
  | { Bind: string }
  | { Oci: OciRootfsSource }
  | {
      DiskImage: {
        path: string;
        format: DiskImageFormat;
        fstype?: string | null;
      };
    };

export type StatVirtualization = "strict" | "relaxed" | "off";

export type HostPermissions = "private" | "mirror";

export type SecurityProfile = "default" | "restricted";

export interface MountOptions {
  readonly: boolean;
  noexec: boolean;
  nosuid: boolean;
  nodev: boolean;
}

export interface SandboxPolicy {
  max_duration_secs?: number | null;
  idle_timeout_secs?: number | null;
}

export type RlimitResource =
  | "Cpu"
  | "Fsize"
  | "Data"
  | "Stack"
  | "Core"
  | "Rss"
  | "Nproc"
  | "Nofile"
  | "Memlock"
  | "As"
  | "Locks"
  | "Sigpending"
  | "Msgqueue"
  | "Nice"
  | "Rtprio"
  | "Rttime";

export interface Rlimit {
  resource: RlimitResource;
  soft: number;
  hard: number;
}

export type LogSource = "stdout" | "stderr" | "output" | "system";

export interface CloudCreateSandboxRequest {
  name: string;
  image: string;
  vcpus: number;
  memory_mib: number;
  env: Record<string, string>;
  ephemeral: boolean;
  workdir?: string | null;
  shell?: string | null;
  entrypoint?: string[] | null;
  hostname?: string | null;
  user?: string | null;
  log_level?: string | null;
  scripts?: Record<string, string>;
  max_duration_secs?: number | null;
  idle_timeout_secs?: number | null;
}

export interface CloudSandbox {
  id: string;
  org_id: string;
  name: string;
  status: CloudSandboxStatus;
  config: CloudCreateSandboxRequest;
  ephemeral: boolean;
  created_at: string;
  started_at?: string | null;
  stopped_at?: string | null;
  last_error?: string | null;
}

export type CloudSandboxStatus =
  | "created"
  | "starting"
  | "running"
  | "stopping"
  | "stopped"
  | "failed";

export interface CloudPaginated<T> {
  data: T[];
  next_cursor?: string | null;
}

export interface CloudMessageResponse {
  message: string;
}

export interface CloudErrorBody {
  code?: string | null;
  message?: string | null;
  error?: CloudErrorDetails | null;
}

export interface CloudErrorDetails {
  code?: string | null;
  message?: string | null;
}
