use std::{env, path::PathBuf};

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let out_dir = PathBuf::from(&crate_dir);

    // cbindgen does not yet support the Rust 2024 `#[unsafe(no_mangle)]`
    // attribute syntax used in this crate, so we tolerate generation failures
    // here. The committed `microsandbox_go_ffi.h` in the crate root was
    // generated by temporarily using `#[no_mangle]`. Re-generate manually
    // when the signature set changes by switching back to `#[no_mangle]`,
    // running `cargo build -p microsandbox-go-ffi`, then restoring
    // `#[unsafe(no_mangle)]`.
    if let Ok(bindings) = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("MICROSANDBOX_GO_FFI_H")
        .with_autogen_warning(
            "/* THIS FILE IS AUTO-GENERATED BY cbindgen — DO NOT EDIT. \
             Run `cargo build -p microsandbox-go-ffi` to regenerate. */",
        )
        .with_documentation(true)
        .generate()
    {
        bindings.write_to_file(out_dir.join("microsandbox_go_ffi.h"));
    }

    // Re-run only when the FFI source changes.
    println!("cargo:rerun-if-changed=src/lib.rs");
}
