#ifndef MICROSANDBOX_GO_FFI_H
#define MICROSANDBOX_GO_FFI_H

/* THIS FILE IS AUTO-GENERATED BY cbindgen — DO NOT EDIT. Run `cargo build -p microsandbox-go-ffi` to regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* MICROSANDBOX_GO_FFI_H */
